//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebColiber.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebColiber.App_GlobalResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowa informacja dla realizującego zamówienie.
        /// </summary>
        internal static string additionalOrderInfo {
            get {
                return ResourceManager.GetString("additionalOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł dod..
        /// </summary>
        internal static string additionalTitle {
            get {
                return ResourceManager.GetString("additionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor dodatku.
        /// </summary>
        internal static string additionAuthor {
            get {
                return ResourceManager.GetString("additionAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł dodatku.
        /// </summary>
        internal static string additionTitle {
            get {
                return ResourceManager.GetString("additionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj do koszyka.
        /// </summary>
        internal static string addToBasket {
            get {
                return ResourceManager.GetString("addToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie zaawansowane.
        /// </summary>
        internal static string advancedSearch {
            get {
                return ResourceManager.GetString("advancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artykuły.
        /// </summary>
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł artykułu.
        /// </summary>
        internal static string articleTitle {
            get {
                return ResourceManager.GetString("articleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rosnąco.
        /// </summary>
        internal static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorzy.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko autora.
        /// </summary>
        internal static string authorsName {
            get {
                return ResourceManager.GetString("authorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zablokowany.
        /// </summary>
        internal static string banned {
            get {
                return ResourceManager.GetString("banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszyk.
        /// </summary>
        internal static string basket {
            get {
                return ResourceManager.GetString("basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszyk jest pusty.
        /// </summary>
        internal static string basketIsEmpty {
            get {
                return ResourceManager.GetString("basketIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWUMIESIĘCZNIK.
        /// </summary>
        internal static string bimonthly {
            get {
                return ResourceManager.GetString("bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWUTYGODNIK.
        /// </summary>
        internal static string biweekly {
            get {
                return ResourceManager.GetString("biweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Książki.
        /// </summary>
        internal static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wypożyczenia.
        /// </summary>
        internal static string borrowDate {
            get {
                return ResourceManager.GetString("borrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypożyczone.
        /// </summary>
        internal static string borrowed {
            get {
                return ResourceManager.GetString("borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypożyczenia.
        /// </summary>
        internal static string borrows {
            get {
                return ResourceManager.GetString("borrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz złożyć zamówienia, ponieważ zostałeś zablokowany przez pracownika Biblioteki..
        /// </summary>
        internal static string cannotOrder {
            get {
                return ResourceManager.GetString("cannotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz/Odznacz wszystko.
        /// </summary>
        internal static string checkUncheckAll {
            get {
                return ResourceManager.GetString("checkUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść kryteria.
        /// </summary>
        internal static string clearCriteria {
            get {
                return ResourceManager.GetString("clearCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współautor.
        /// </summary>
        internal static string coAuthor {
            get {
                return ResourceManager.GetString("coAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawiera.
        /// </summary>
        internal static string contains {
            get {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egzemplarze.
        /// </summary>
        internal static string copiesOf {
            get {
                return ResourceManager.GetString("copiesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egzemplarz.
        /// </summary>
        internal static string copyOf {
            get {
                return ResourceManager.GetString("copyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to egz..
        /// </summary>
        internal static string cpy {
            get {
                return ResourceManager.GetString("cpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZIENNIK.
        /// </summary>
        internal static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baza danych:.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wprowadzenia.
        /// </summary>
        internal static string dateEntererd {
            get {
                return ResourceManager.GetString("dateEntererd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczone.
        /// </summary>
        internal static string deleteChecked {
            get {
                return ResourceManager.GetString("deleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to malejąco.
        /// </summary>
        internal static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydanie.
        /// </summary>
        internal static string edition {
            get {
                return ResourceManager.GetString("edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz frazę....
        /// </summary>
        internal static string enterPhrase {
            get {
                return ResourceManager.GetString("enterPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment opisu.
        /// </summary>
        internal static string excerpt {
            get {
                return ResourceManager.GetString("excerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportuj do Word.
        /// </summary>
        internal static string exportDOC {
            get {
                return ResourceManager.GetString("exportDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole wymagane.
        /// </summary>
        internal static string fieldRequired {
            get {
                return ResourceManager.GetString("fieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki do pobrania.
        /// </summary>
        internal static string filesToDL {
            get {
                return ResourceManager.GetString("filesToDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Częstotliwość.
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opisy bibliograficzne.
        /// </summary>
        internal static string glossaryDescriptions {
            get {
                return ResourceManager.GetString("glossaryDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Półrocznik.
        /// </summary>
        internal static string halfYearly {
            get {
                return ResourceManager.GetString("halfYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posiada źródła.
        /// </summary>
        internal static string hasSources {
            get {
                return ResourceManager.GetString("hasSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instytucja sprawcza.
        /// </summary>
        internal static string institution {
            get {
                return ResourceManager.GetString("institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer inwentarzowy.
        /// </summary>
        internal static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEREGULARNE.
        /// </summary>
        internal static string irregular {
            get {
                return ResourceManager.GetString("irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string isbn {
            get {
                return ResourceManager.GetString("isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSN.
        /// </summary>
        internal static string issn {
            get {
                return ResourceManager.GetString("issn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis pozycji.
        /// </summary>
        internal static string itemDescription {
            get {
                return ResourceManager.GetString("itemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucze.
        /// </summary>
        internal static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        internal static string language_ {
            get {
                return ResourceManager.GetString("language_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język tekstu.
        /// </summary>
        internal static string languageOfText {
            get {
                return ResourceManager.GetString("languageOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasopisma.
        /// </summary>
        internal static string magazines {
            get {
                return ResourceManager.GetString("magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamów.
        /// </summary>
        internal static string makeOrder {
            get {
                return ResourceManager.GetString("makeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIESIĘCZNIK.
        /// </summary>
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje wypożyczenia.
        /// </summary>
        internal static string myBorrows {
            get {
                return ResourceManager.GetString("myBorrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje zamówienia.
        /// </summary>
        internal static string myOrders {
            get {
                return ResourceManager.GetString("myOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bez egz..
        /// </summary>
        internal static string noCpy {
            get {
                return ResourceManager.GetString("noCpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zamówień.
        /// </summary>
        internal static string noOrders {
            get {
                return ResourceManager.GetString("noOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wyników.
        /// </summary>
        internal static string noSearchResults {
            get {
                return ResourceManager.GetString("noSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieoddane wypożyczenia.
        /// </summary>
        internal static string notReturned {
            get {
                return ResourceManager.GetString("notReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość tomów.
        /// </summary>
        internal static string numberOfVolumes {
            get {
                return ResourceManager.GetString("numberOfVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numery.
        /// </summary>
        internal static string numbers {
            get {
                return ResourceManager.GetString("numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer i rok.
        /// </summary>
        internal static string numberYear {
            get {
                return ResourceManager.GetString("numberYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lub.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie zostało wysłane.
        /// </summary>
        internal static string orderAccepted {
            get {
                return ResourceManager.GetString("orderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenia zamówienia.
        /// </summary>
        internal static string orderConfirm {
            get {
                return ResourceManager.GetString("orderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówiony.
        /// </summary>
        internal static string ordered {
            get {
                return ResourceManager.GetString("ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zamówienia.
        /// </summary>
        internal static string ordersDate {
            get {
                return ResourceManager.GetString("ordersDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zamawia następujące pozycje.
        /// </summary>
        internal static string ordersFollowingItems {
            get {
                return ResourceManager.GetString("ordersFollowingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektóre pozycje mogły nie zostać zamówione, ponieważ już je posiadasz zamówione lub wypożyczone.
        /// </summary>
        internal static string ordersInfo001 {
            get {
                return ResourceManager.GetString("ordersInfo001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic nie zostało zamówione, ponieważ posiadasz już te pozycje zamówione lub wypożyczone.
        /// </summary>
        internal static string ordersInfo002 {
            get {
                return ResourceManager.GetString("ordersInfo002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówione zostały.
        /// </summary>
        internal static string ordersInfo003 {
            get {
                return ResourceManager.GetString("ordersInfo003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan zamówienia.
        /// </summary>
        internal static string orderState {
            get {
                return ResourceManager.GetString("orderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.p..
        /// </summary>
        internal static string oridinalShort {
            get {
                return ResourceManager.GetString("oridinalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strony.
        /// </summary>
        internal static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł równ..
        /// </summary>
        internal static string paralellTitle {
            get {
                return ResourceManager.GetString("paralellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraza.
        /// </summary>
        internal static string phrase {
            get {
                return ResourceManager.GetString("phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukana fraza.
        /// </summary>
        internal static string phraseSearched {
            get {
                return ResourceManager.GetString("phraseSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis fiz..
        /// </summary>
        internal static string physicalDescription {
            get {
                return ResourceManager.GetString("physicalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę czekać....
        /// </summary>
        internal static string pleaseWait {
            get {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzedni.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewidywana data zwrotu.
        /// </summary>
        internal static string providedDate {
            get {
                return ResourceManager.GetString("providedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj wydania.
        /// </summary>
        internal static string publicationCountry {
            get {
                return ResourceManager.GetString("publicationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce wydania.
        /// </summary>
        internal static string publicationPlace {
            get {
                return ResourceManager.GetString("publicationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce i data wydania.
        /// </summary>
        internal static string publicationPlaceDate {
            get {
                return ResourceManager.GetString("publicationPlaceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydawnictwo.
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWARTALNIK.
        /// </summary>
        internal static string quarterly {
            get {
                return ResourceManager.GetString("quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasoby.
        /// </summary>
        internal static string resources {
            get {
                return ResourceManager.GetString("resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data oddania.
        /// </summary>
        internal static string returnDate {
            get {
                return ResourceManager.GetString("returnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddane wypożyczenia.
        /// </summary>
        internal static string returnedBorrows {
            get {
                return ResourceManager.GetString("returnedBorrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie.
        /// </summary>
        internal static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie zasobów ze źródłami.
        /// </summary>
        internal static string searchWithSources {
            get {
                return ResourceManager.GetString("searchWithSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij zamówienie.
        /// </summary>
        internal static string sendOrder {
            get {
                return ResourceManager.GetString("sendOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seria.
        /// </summary>
        internal static string serie {
            get {
                return ResourceManager.GetString("serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż oddane.
        /// </summary>
        internal static string showReturned {
            get {
                return ResourceManager.GetString("showReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sygnatura.
        /// </summary>
        internal static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie proste.
        /// </summary>
        internal static string simpleSearch {
            get {
                return ResourceManager.GetString("simpleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortuj według.
        /// </summary>
        internal static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Źródła.
        /// </summary>
        internal static string sources {
            get {
                return ResourceManager.GetString("sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł źródła publikacji.
        /// </summary>
        internal static string sourceTitle {
            get {
                return ResourceManager.GetString("sourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekuje.
        /// </summary>
        internal static string stat_Oczekuje {
            get {
                return ResourceManager.GetString("stat_Oczekuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przygotowane.
        /// </summary>
        internal static string stat_Przygotowane {
            get {
                return ResourceManager.GetString("stat_Przygotowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnacja.
        /// </summary>
        internal static string stat_Rezygnacja {
            get {
                return ResourceManager.GetString("stat_Rezygnacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrealizowane.
        /// </summary>
        internal static string stat_Zrealizowane {
            get {
                return ResourceManager.GetString("stat_Zrealizowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podtytuł.
        /// </summary>
        internal static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streszczenia.
        /// </summary>
        internal static string summaries {
            get {
                return ResourceManager.GetString("summaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streszczenie.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawca.
        /// </summary>
        internal static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz.
        /// </summary>
        internal static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucze.
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł źródła publikacji.
        /// </summary>
        internal static string titleOfPublicationSource {
            get {
                return ResourceManager.GetString("titleOfPublicationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do usunięcia.
        /// </summary>
        internal static string toDelete {
            get {
                return ResourceManager.GetString("toDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do zamówienia.
        /// </summary>
        internal static string toOrder {
            get {
                return ResourceManager.GetString("toOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKD.
        /// </summary>
        internal static string ukd {
            get {
                return ResourceManager.GetString("ukd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyrejestrowany.
        /// </summary>
        internal static string userDeleted {
            get {
                return ResourceManager.GetString("userDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolumin.
        /// </summary>
        internal static string volumin {
            get {
                return ResourceManager.GetString("volumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYGODNIK.
        /// </summary>
        internal static string weekly {
            get {
                return ResourceManager.GetString("weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamawiający.
        /// </summary>
        internal static string whoOrders {
            get {
                return ResourceManager.GetString("whoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROCZNIK.
        /// </summary>
        internal static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok wydania.
        /// </summary>
        internal static string yearOfPublishing {
            get {
                return ResourceManager.GetString("yearOfPublishing", resourceCulture);
            }
        }
    }
}
