
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Data_uniew,Nor_nor_id) values  (5,'PN 01\0001','To jest PN','2005.08.24',77)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Data_uniew,Nor_nor_id) values  (6,'PN-70/B-01025','Rysunek budowlany.Oznaczenia graficzne na rysunkach architektoniczno-budowlanych.','2004.06.02',80)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (7,'PN-66/B-23001',82)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (8,'PN64/B-23004p.1.3; 1',82)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (9,'PN-62/B-23006 p.1.2',82)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (10,'PN-60/B-23011 p.1.2;',82)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (11,'PN-64/B23012 p.1.3;',82)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (12,'PN-66/B-01400','Centralne ogrzewanie. Oznaczenia na rysunkach.',84)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (13,'PN-66/B-23001,',86)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (14,'PN-63/B-01405','Centralne ogrzewanie.Grzejniki.Nazwy i okreœlenia.',88)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (15,'PN-60/B-01410,','Wentylacja i klimatyzacja.Rysunek techniczny.zasady wykonywania i oznaczenia.',89)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (16,'PN-84/B-01412','Wentylacja i klimatyzacja.Rysunek techniczny.zasady wykonywania i oznaczenia.',89)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (17,'PN-64/B-01420','Ciep³ownictwo.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia na mapach i planach.',90)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (18,'PN-72/B-01430','Ogrzewnictwo.Instalacje centralnego ogrzewania.Terminologia.',91)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (19,'PN-85/B-01700','Wodoci¹gi i kanalizacja.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia graficzne.',92)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (20,'PN-66/B-01701','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Oznaczenia na rysunkach.',93)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (21,'PN-64/B-02012','Obci¹¿enia budowli.Obci¹¿enia suwnicami pomostowymi,wci¹garkami.',96)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (22,'PN-72/B-02013','Obci¹¿enia budowli.Obci¹¿enia suwnicami pomostowymi,wci¹garkami.',96)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (23,'PN-64/B-02009','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enia sta³e i zmienne.',97)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (24,'PN-70/B-02010','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie œniegiem.',98)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (25,'PN-70/B-02011','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie wiatrem.',99)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (26,'PN-79/B-02151','Akustyka budowlana.Ochrona przed ha³asem pomieszczeñ w budynkach.',101)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (27,'PN-70/B-02151','Akustyka budowlana.Dopuszczalne wartoœci poziomu d¿wiêku w pomieszczeniach.',102)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (28,'PN-87/B-02151/03','Akustyka budowlana.Ochrona przed ha³asem w budynkach- izolacyjnoœc akustyczna przegród w budynkach oraz izolacyjnoœæ akustyczna elementów budowlanych.Wymagania.',105)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (29,'PN-70/B-02156','Akustyka budowlana.Metody pomiaru poziomu d¿wiêku A w budynkach',107)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (32,'PN-EN 14001:2005(U)','Systemy zarzadzania œrodowiskowego.Wymagania i wytyczne stosowania.',118)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (33,'PN-89/E-01102','Oznaczenia wielkoœci i jednostek miar u¿ywanych w elektryce.Czêœæ 2:Telekomunikacja i elektronika.',119)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (34,'PN-EN ISO 3887:2003(','Stale.Okreœlanie g³êbokoœci odwêglania.',120)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (35,'PN-EN ISO 2538:2003(','Specyfikacje geometrii wyrobów (GPS).Szeregi k¹tów i pochyleñ pryzm.',121)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (36,'PN-74/B-02402','Ogrzewnictwo.Temperatury ogrzewanych pomieszczeñ w budynkach.',122)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (37,'PN-74/B-02403','Ogrzewnictwo.Temperatury obliczeniowe zewnêtrzne.',123)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (38,'PN-62/B-02412','Zabezpieczenie utz¹dzeñ wytwarzaj¹cych parê niskoprê¿n¹.Wymagania.',125)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (39,'PN-77/B-02413','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych systemu otwartego.Wymagania.',126)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (40,'PN-91/B-02414','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych...',127)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (41,'PN-70/B-02415','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie wodnych zamkniêtych systemów ciep³owniczych.Wymagania.',128)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (42,'PN-70/B-02416','Ogrzewnictwo i ciep³ownictwo.zabezpieczenie instalacji ogrzewañ wodnych systemu zamkniêtego przy³¹czonych do sieci.',129)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (43,'PN-85/B-02421','Ogrzewnictwo i cep³ownictwo.Izolacja cieplna przewodów,armatury i urz¹dzeñ.Wymagania i badania odbiorcze.',131)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (44,'PN-69/B-02482','Fundamenty budowlane.Noœnoœæ pali i fundamentów palowych.',132)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (45,'PN-64/B-02851','Ochrona przeciwpo¿arowa budynków.Metoda badania odpornoœci ogniowej elementów budynków.',133)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (46,'PN-88/B-02854','Ochrona przeciwpo¿arowa budynków.Metoda badania rozprzestrzeniania p³omieni po posadzkach pod³ogowych.',134)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (47,'PN-67/B-02857','Przeciwpo¿arowe zbiorniki wodne.Wymagania ogólne.',135)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (48,'PN-71/B-02863','Przeciwpo¿arowe zaopatrzenie wodne.Sieæ wodoci¹gowa przeciwpo¿arowa.',136)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (49,'PN-71/B-02864','Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne...',137)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (50,'PN-72/B-02865','Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne.Instalacja wodoci¹gowa przeciwpo¿arowa.',139)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (51,'PN-81/B-03150/00','Konstrukcje drewniane.Obliczenia statyczne i projektowanie.',140)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (52,'PN-81/B-03150/01','Konstrukcje drewniane.Obliczenia statyczne i projektowanie.',140)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (53,'PN-81/B-03150/02','Konstrukcje drewniane.Obliczenia statyczne i projektowanie.',140)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (54,'PN-81/B-03150/03','Konstrukcje drewniane.Obliczenia statyczne i projektowanie.',140)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (55,'PN-80/B-03200','Konstrukcje stalowe.Obliczenia statyczne i projektowanie.',141)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (56,'PN-89/B-03340','Konstrukcje murowe zbrojone.Projektowanie i obliczanie.',143)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (57,'PN-67/B-03005','Konstrukcje murowe zbrojone.Projektowanie i obliczanie.',143)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (58,'PN-74/B-03406','Oliczanie zapotrzebowania ciep³a pomieszczeñ o kubaturze do 600 m3',144)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (59,'PN-64/B-03420','Wentylacja i klimatyzacja.Parametry obliczeniowe powietrza zewnêtrznego.',145)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (60,'PN-74/B-03430','Wentylacja w budynkach mieszkalnych zamieszkania zbiorowego i u¿ytecznoœci publicznej.Wymagania.',147)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (61,'PN-63/B-03431','Wentylacja mechaniczna w budownictwie.Wymagania.',149)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (62,'PN-80/B-03433','Wentylacja.Instalacje wentylacji mechanicznej wywiewnej w budynkach mieszkalnych wielorodzinnych.Wymagania.',151)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (63,'PN-68/B-06050','Geotechnika.Roboty ziemne.Wymagania ogólne.',152)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (64,'PN-55/B-06251','Roboty betonowe i ¿elbetowe.Wymagania techniczne.',154)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (65,'BN-69/6721-04','Kruszywa mineralne.Piaski do zapraw budowlanych.',156)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (66,'PN-62/B-09700','Tablice orientacyjne do oznaczania uzbrojenia na przewodach wodoci¹gowych.',157)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (67,'PN-53/B-02062,63','Roboty murowe z ceg³y.Wymagania i badania przy odbiorze.',158)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (68,'PN-53/B-10020,22','Roboty murowe z ceg³y.Wymagania i badania przy odbiorze.',158)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (69,'PN-58/B-10023','Roboty murowe.Konstrukcje ceglano-¿elbetowe wykonywane na budowie.Wymagania i badania przy odbiorze.',160)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (70,'PN-83/B-10085','Stolarka budowlana.Okna i drzwi.Wymagania i badania.',162)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (71,'PN-58/B-10100','Roboty tynkowe.Tynki zwyk³e.Wymagania i badania przy odbiorze.',163)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (72,'PN-59/B-10241','Roboty pokrywcze.Krycie dachówk¹ ceramiczn¹.Wymagania i badania przy odbiorze.',166)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (73,'PN-91/B-10405','Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze.',167)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (74,'BN-75/8973-10','Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze.',167)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (75,'BN-77/8973-11','Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze.',167)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (76,'PN-59/B-10425','Przewody dymowe,spalinowe i wentylacyjne murowane zceg³y.Wymagania techniczne i badania przy odbiorze.',169)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (77,'PN-59/B-10700','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania.',170)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (78,'PN-59/B-10701','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania.',170)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (79,'PN-71/B-10420','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania.',170)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (80,'PN-72/B-10722','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania.',170)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (81,'PN-59/B-10700','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne.',171)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (82,'PN-59/B-10701','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne.',171)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (83,'PN-72/B-10722','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne.',171)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (84,'PN-59/B-10700','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody ciep³ej z rur stalowych ocynkowanych.',172)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (85,'PN-59/B-10701','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody ciep³ej z rur stalowych ocynkowanych.',172)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (86,'PN-71/B-10420','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody ciep³ej z rur stalowych ocynkowanych.',172)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (87,'PN-72/B-10722','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody zimnej z polichlorku winylu i polietylenu.',173)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (88,'PN-85/B-10702','Wodoci¹gi i kanalizacja.Zbiorniki.Wymagania i badania.',174)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (89,'PN-92/B-10729','Kanalizacja.Studzienki kanalizacyjne.',176)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (90,'PN-69/B-10740','Stacje hydroforowe.Wymagania i badania przy odbiorze.',177)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (91,'PN-70/B-12003','Ceg³y pe³ne i bloki dr¹¿one wapienno-piaskowe.',178)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (92,'PN-62/B-12019','Ceg³a termalitowa.',179)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (93,'PN-65/C-12330','Porcelanowy sprzêt laboratoryjny.Wymagania i badania.',183)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (94,'BN-64/7027-01','Porcelanowy sprzêt laboratoryjny.Tygle.',184)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (95,'BN-64/7027-02','Porcelanowy sprzêt laboratoryjny.Parownice.',185)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (96,'BN-63/6851-06','Szklany sprzêt laboratoryjny.Kolby destylacyjne.',186)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (97,'PN-57/C-13000','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.',187)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (98,'PN-61/C-13008','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.',187)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (99,'BN-63/6851-03','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.',187)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (100,'BN-63/6851-04','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.',187)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (101,'BN-67/6851-13','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.',187)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (102,'BN-63/6851-04','Szklany sprzêt laboratoryjny.Kolby wieloszyjkowe.',188)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (103,'BN-63/6851-05','Szklany sprzêt laboratoryjny.Kolby wieloszyjkowe.',188)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (104,'PN-71/B-02864','Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne.',196)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (105,'PN-63/C-13011','Szlify sto¿kowe z³¹czy szklanych.',197)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (106,'PN-68/C-13027','Szklany sprzêt laboratoryjny.Naczynia ppomiarowe.Mikrobiurety Banga.',199)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (107,'PN-57/C-13031','Szklany sprzêt laboratoryjny.Lejki.',200)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (108,'PN/C-13030','Szklany sprzêt laboratoryjny.Lejki rozdzielcze.',201)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (109,'PN/C-13035','Szklany sprzêt laboratoryjny.Lejki rozdzielcze.',201)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (110,'PN-57/C-13039','Szklany sprzêt laboratoryjny.Eksykatory.',202)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (111,'PN-64/C-13200','Wady szk³a i wyrobów szklanych.Podzia³, nazwy i okreœlenia.',203)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (112,'PN-67/B-23100','Materia³y do izolacji cieplnej z w³ókien nieorganicznych.We³na mineralna.',204)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (113,'PN-74/B-24620','Lepiki, masy i roztwory asfaltowe stosowane na zimno.',205)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (114,'PN-74/B-24622','Lepiki, masy i roztwory asfaltowe stosowane na zimno.',205)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (115,'PN-76/B-24628','Lepiki, masy i roztwory asfaltowe stosowane na zimno.',205)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (116,'PN-64/B-24624','Lepik asfaltowy do posadzki deszczu³kowej.',206)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (117,'BN-88/6751-03','Papa asfaltowa na welonie z w³ókien szklanych.',207)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (118,'BN-80/6733-09','Spoiwa gipsowe.Gips szpachlowy, gips tynkarski i klej gipsowy.',208)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (119,'BN-85/6753-02','Kity budowlane trwale plastyczne-olejowy i polistyrenowy.',209)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (120,'BN-78/6753-05','Kit tiokolowy.',210)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (121,'BN-85/6753-07','Kity budowlane kauczukowe i asfaltowo-kauczukowe uszczelniaj¹ce.',211)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (122,'BN-85/6753-08','Kity budowlane kauczukowe i asfaltowo-kauczukowe uszczelniaj¹ce.',211)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (123,'PN-75/B-89020','Wyroby budowlane z tworzyw sztucznych.Ok³adzina porêczowa z polichlorku winylu.',212)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (124,'PN-66/B-91003','Drzwi.Zasady ustalania wymiarów skoordynowanych modularnie.',213)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (125,'PN-64/B-94053','Okucia budowlane.Zawiasy czopowe dwuskszyd³owe rozwierane ze skszyde³kami prostymi do wpuszczania.',222)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (126,'PN-64/B-94054','Okucia budowlane.zawiasy czopowe dwuskrzyd³owe rozwierane ze skrzyde³kami odgiêtymi.',223)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (127,'PN-64/B-94058','Okucia budowlane.Zawiasy wahad³owe.',226)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (128,'PN-60/B-94144','Okucia budowlane.Zasuwy wierzchnie i wpuszczane.',228)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (129,'PN-60/B-94145','Okucia budowlane.Zasuwy wierzchnie i wpuszczane.',228)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (130,'PN-63/B-94146','Okucia budowlane.Zasuwy wierzchnie i wpuszczane.',228)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (131,'PN-64/B-94451','Okucia budowlane.Zamki wierzchnie bêbenkowe.Konstrukcje.',229)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (132,'PN-64/B-94452','Okucia budowlane.Zamki wierzchnie bêbenkowe.Konstrukcje.',229)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (133,'PN-64/B-94461.1.3','Okucia budowlane.Wk³adki bêbenkowe profilowe.Okreœlenia i podzia³.',231)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (134,'PN-75/B-94461.03','Okucia budowlane.Wk³adki bêbenkowe profilowe.Wk³adki jednostronne.',232)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (135,'PN-C-01000:1952','Zwi¹zki organiczne.Zasady budowy nazw.',233)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (136,'PN-67/C-01055','Analiza chemiczna.Wytyczne wykonywania badañ.',236)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (137,'PN-65/C-01060','Oznaczenia stopni czystoœci surowców i produktów przemys³u chemicznego.',237)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (138,'PN-81/C-01604/01','Guma.Terminologia.Podzia³, nazwy i symbole kauczuków.',240)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (139,'PN-61/C-04000','Ropa naftowa i przetwory naftowe.Pobieranie próbek.',242)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (140,'PN-65/C-04008','Przetwory naftowe.Oznaczenia temperatury zap³onu w tyglu otwartym metod¹ Marcussona.',243)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (141,'PN-C-04014','Przetwory hnaftowe.Oznaczanie lepkoœci wzglêdnej lepkoœciomierzem.Englera.',245)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (142,'PN/C-04015','Przetwory naftowe.Obliczanie wska¿nika lepkoœci na podstawie lepkoœci kinematycznej w 37,78,98,89 C.',246)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (143,'PN-66/C-04017','Przetwory naftowe.Oznaczanie temperatury mêtnienia i pocz¹tku krystalizacji paliw silnikowych.',248)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (144,'PN/C-04018','Przetwory naftowe.Oznaczanie temperatury krzepniêcia metod¹ ¯ukowa.',249)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (145,'PN-68/C-04019','Oznaczanie lepkoœci dynamicznej lepkoœciomierzem Hopplera.',250)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (146,'PN-74/C-04055','Przetwory naftowe.Oznaczanie odpornoœci olejów na pienienie.',255)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (147,'PN-53/C-04060','Przetwory naftowe w smarach plastycznych zawartoœci zanieczyszczeñ mechanicznych nierozpuszczalnych w kwasie solnym.',256)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (148,'PN-54/C-04139','Przetwory naftowe w smarach plastycznych zawartoœci zanieczyszczeñ mechanicznych nierozpuszczalnych w kwasie solnym.',256)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (149,'PN-67/C-04066','Przetwory naftowe.Oznaczanie liczby kwasowej i zasadowej oraz kwasowoœci metod¹ miareczkowania wobec wska¿ników.',259)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (150,'PN-54/C-04070','Przetwory naftowe.Oznaczanie zawartoœci chloru w olejach smarowych.',260)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (151,'PN-72/C-04071','Przetwory naftowe.Oznaczanie zawartoœci chloru w olejach smarowych.',260)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (152,'PN-73/C-04082','Przetwory naftowe.Badanie w³asnoœci przeciwkorozyjnych olejów mineralnych.',263)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (153,'PN-59/C-04087','Ropa naftowa i przetwory.Oznaczanie zawartoœci wody i sta³ych cia³ obcych metod¹ wirówkow¹.',267)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (154,'PN-59/C-04096','Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych i stabilnoœci termooksydacyjnej  olejów smarowych.',269)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (155,'BN-69/0536-12','Przetwory naftowe.Badanie odpornoœci smarów plastycznych na wymywanie wod¹, metod¹ dynamiczn¹.',271)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (156,'BN-72/0536-16','Przetwory naftowe.Badanie sk³onnoœci do wydzielania siê smarów plastycznych z ³o¿ysk kó³ samochodowych.',273)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (157,'PN-63/C-04109','Przetwory naftowe.Oznaczanie zawartoœci parafiny w olejach.',274)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (158,'PN-70/C-04028','Przetwory naftowe.Oznaczanie policyklicznych wêglowodorów aromatycznych w parafinie metod¹ fluorescyjn¹.',275)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (159,'PN-79/C-04133','Przetwory naftowe.Pomiar penetracji smarów plastycznych i petrolatum penetrometrem ze sto¿kiem.',276)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (160,'PN-71/C-04135','Przetwory naftowe.Pomiar penetracji smarów plastycznych i petrolatum penetrometrem ze sto¿kiem.',276)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (161,'PN-73/C-04148','Przetwory naftowe.Oznaczanie odpornoœci na utlenianie olejów turbinowych z dodatkami.',282)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (162,'PN-54/C-04152','Przetwory naftowe.Oznaczanie zawartoœci wolnych zasad i wolnych kwasów organicznych w smarach sta³ych.',283)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (163,'PN-60/C-04160','Przetwory naftowe.Oznaczanie zawartoœci oleju w parafinie, cerezynie i petrolatum.',287)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (164,'PN-60/C-04161','Przetwory naftowe.Pomiar penetracji parafin i cerezyn.',288)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (165,'PN-81/C-04178','Przetwory naftowe.Oznaczanie zawartoœci sta³ych cia³ obcych w olejach smarowych i hydraulicznych na s¹czku membranowym.',296)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (166,'PN-74/C-96072p.3.5','Przetwory naftowe.Badanie odpornoœci olejów do sprê¿arek ch³odniczych na dzia³anie czynników ch³odniczych.',297)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (167,'PN-70/C-96032p.2.2.6','Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych w olejach lotniczych metod¹ dynamiczn¹.',301)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (168,'PN-56/C-04214','Guma.Oznaczanie temperatury kruchoœci metod¹ uderzeniow¹.',306)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (169,'PN-71/C-04238','Guma.Oznaczanie twardoœci wg metody Shorea.',308)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (170,'PN-56/C-04243','Tworzywa sztuczne.Oznaczanie wytrzyma³oœci na zginanie za pomoc¹ aparatu-typ Dynstat.',309)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (171,'PN-69/C-04244','Guma.Oznaczanie zawartoœci siarki.',310)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (172,'PN-70/C-04252','Guma.Oznaczanie wytrzyma³oœci po³¹czeñ guma-metal.',311)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (173,'PN-65/C-04265','Guma.Oznaczanie wytrzyma³oœci na rozwarstwianie po³¹czeñ gumy, gumy z tkanin¹ i tkaniny gumowanej z tkanin¹ gumow¹.',316)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (174,'PN-78/C-04281','Produkty chemiczne organiczne.Metody badañ.Oznaczanie liczby jodowej.',318)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (175,'PN-71/C-04338','Guma.Oznaczanie odpornoœci na wielokrotne rozci¹ganie.',319)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (176,'PN/C-04504','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.',320)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (177,'PN/C-04505','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.',320)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (178,'PN/C-04506','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.',320)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (179,'PN/C-04507','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.',320)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (180,'PN/C-04508','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.',320)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (181,'PN-56/C-04501','Analiza sitowa.Wytyczne wykonywania.',321)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (182,'PN-68/C-04502','Analiza chemiczna.Oznaczanie ma³ych zawartoœci wêglanów.',322)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (183,'PN-68/C-04503','Analiza chemiczna.Oznaczanie ma³ych zawartoœci fosforanów w bezbarwnych roztworach metod¹ kolorymetryczn¹.',324)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (184,'PN-81/C-04504','Analiza chemiczna.Oznaczanie gêstoœci produktów chemicznych ciek³ych i sta³ych w postaci proszku.',325)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (185,'PN-68/C-04509','Analiza chemiczna.Oznaczanie ma³ych zawartoœci azotanów.',327)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (186,'PN-75/C-04511','Analiza chemiczna.Oznaczanie ma³ych zawartoœci arsenu.',328)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (187,'PN-79/C-04512','Produkty chemiczne organiczne.Oznaczanie granic temperatury wrzenia.',329)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (188,'PN-76/C-04513','Oznaczanie granic temperatury topnienia lub temperatury rozk³adu substancji organicznych.',330)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (189,'PN-75/C--04514','Oznaczanie temperatury krystalizacji substancji organicznych.',331)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (190,'PN-68/C-04515','Analiza chemiczna.Oznaczanie ma³ych zawartoœci metali ciê¿kich.',332)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (191,'PN-68/C-04519','Analiza chemiczna.Oznaczanie ma³ych zawartoœci siarczanów w bezbarwnych roztworach metod¹ turbidynamiczn¹.',334)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (192,'PN-68/C-04520','Produkty chemiczne.Oznaczanie liczby bromowej metod¹ miareczkowania biamperometrycznego.',336)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (193,'PN-75/C-04521.00','Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza.Postanowienia ogólne i zakres normy.',339)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (194,'PN-75/C-04521.01','Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem batofenantroliny.',340)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (195,'PN-75/C-04521.02','Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem 2,2-dwupirydylu.',342)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (196,'PN-75/C-04521.03','Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem tiocyjanianu (rodanku) amonowego.',343)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (197,'PN-68/C-04522','Analiza chemiczna.Oznaczanie ma³ych zawartoœci kwasu krzemowego w bezbarwnych roztworach metod¹ kolorymetryczn¹.',346)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (198,'PN-68/C-04525','Analiza chemiczna.Oznaczanie ma³ych zawartoœci amonu.',347)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (199,'PN-68/C-04527','Analiza chemiczna.Oznaczanie azotu ogólnego metod¹ destylacyjn¹.',349)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (200,'PN-75/C-04528','Analiza chemiczna.Oznaczanie fosforanów metod¹ miareczkow¹ chino-linowo-molibdenianow¹.',350)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (201,'PN-58/C-04529','Analiza chemiczna.Oznaczanie krzemu metod¹ wagow¹.',351)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (202,'BN-70/6020-02','Analiza chemiczna.Oznaczanie barwy produktów chemicznych za pomoc¹ skali Hazena(skala platynowo-kobaltowa)',364)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (203,'PN-82/C-04534.02','Analiza chemiczna.Oznaczanie barwy, produktów chemicznych za pomoc¹ skali jodowej.',365)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (204,'BN-79/6110-37','Analiza chemiczna.Oznaczanie barwy produktów chemicznych wed³ug skali Gardnera.',368)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (205,'PN-68/C-04538','Analiza chemiczna.Oznaczanie ma³ych zawartoœci miedzi.',371)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (206,'PN-62/C-04539','Rozpuszczalniki i rozcieñczalniki lakiernicze.Metody badañ.',372)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (207,'PN-74/C-04540.00','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Postanowienia ogólne i zakres normy.',373)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (208,'PN-74/C-04540.01','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH wód i œcieków o przewodnoœci elektrolitycznej w³aœciwej 10uS/cm',374)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (209,'PN-74/C-04540.01','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania potencjometrycznego.',375)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (210,'PN-74/C-04540.03','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania wobec wska¿ników.',376)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (211,'PN-75/C-04540.04','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci ogónej w œciekach zawieraj¹cych du¿e iloœci ¿elaza i glinu.',377)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (212,'PN-75/C-04540.05','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci mineralnej i ogólnej w osadach...',378)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (213,'BN-70/6212-12','Woda i œcieki.Badania zawartoœci i zapotrzebowania ozonu.Oznaczanie ozonu w wodzie metod¹ kolorymetryczn¹ z kompleksem.',380)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (214,'PN-80/C-04544.01','Woda i œcieki.Badania zawartoœci wielopierœcieniowych wêglowodorów aromatycznych.',381)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (215,'PN-57/C-04598','Woda i œcieki.Badania zawartoœci dwutlenku wêgla.Oznaczanie agresywnego dwutlenku wêgla w wodzie.',385)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (216,'PN-79/C-04560.01','Woda i œcieki.Badania zawartoœci kadmu.Oznaczanie kadmu metod¹ ditizonow¹.',390)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (217,'PN-79/C-04564.00','Woda i œcieki.Oznaczanie zawartoœci molibdenu metod¹ kolorymetryczn¹ z toluenu-3,4-ditiolem.',393)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (218,'PN-79/C--04564.01','Woda i œcieki.Oznaczanie zawartoœci molibdenu metod¹ kolorymetryczn¹ z toluenu-3,4-ditiolem.',393)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (219,'PN-74/C-04566.10','Woda i œcieki.Badania zawartoœci siarki i jej zwi¹zków.Oznaczanie siarczanów metod¹ turbidymetryczn¹.',395)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (220,'PN-81/C-04570.02','Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie cynku miedzi, o³owiu, kadmu..',397)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (221,'PN-74/C-04571','Woda i œcieki.Oznaczanie zawartoœci srebra.',403)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (222,'PN-78/C-04573.01','Woda i œcieki.Badania zawartoœci subs.ekstrahuj¹cych siê rozpuszczalnikami organ.Oznaczanie ca³kowitej zawart.sub.organ.ekstrahuj¹cych siê eterem.',406)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (223,'PN-82/C-04573.03','Woda i œcieki.Badania zawartoœci subst. ekstrahuj¹cych siê rozpuszczalnikami organicznymi.Oznaczanie ca³kowitej...',407)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (224,'PN-75/C-04574','Woda i œcieki.Oznaczanie zawartoœci antymonu metod¹ kolorymetryczn¹ z rodamin¹ B.',408)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (225,'PN-73/C-04576.08','Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu azotanowego metod¹ kolorymetryczn¹ z salicylanem sodowym.',413)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (226,'BN-70/6215-38','Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu organicznego w osadach œcieków.',416)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (227,'BN-66/6215-28','Woda i œcieki.Badania zapotrzebowania tlenu i zawartoœci wêgla organicznego.Oznaczanie chemicznego zapotrzebowania tlenu (ChZT) metod¹ dwuchromianow¹.',418)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (228,'BN-68/6215-34','Woda i œcieki.Badania zapotrzebowania tlenu i zawartoœci wêgla organicznego.Oznaczanie chemicznego zapotrzebowania tlenu (ChZT) metod¹ dwuchromianow¹.',418)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (229,'BN-71/6191-95','Woda i œcieki.Woda stosowana do celów analitycznych w laboratoriach wodno-œciekowych.Wymagania jakoœciowe i metody badañ.',419)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (230,'PN-73/C-04586.02','Woda i œcieki.Badanie zawartoœci ¿elaza...',421)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (231,'PN-73/C-04586.04','Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza ogólnego rozpuszczonego metod¹  spektrofotometryczn¹ z sol¹ dwusodow¹ kwasu batofenantrolinodwusulfonowego.',422)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (232,'PN-73/C-04586.05','Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza metod¹ wersenianow¹.',423)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (233,'PN-75/C-04590.00','Woda i œcieki.Badania zawartoœci manganu.Postanowienia ogólne.',425)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (234,'PN-75/C-04590.01','Woda i œcieki.Badania zawartoœci manganu.Oznaczanie manganu metod¹ nadmanganianow¹.',426)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (235,'PN-84/C-04590.02','Woda i œcieki.Badania zawartoœci manganu metod¹ formaldoksymow¹.',427)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (236,'PN-79/C-04595.02','Woda i i œcieki.Badania zawartoœci o³owiu.Oznaczanie o³owiu metod¹ ditizonow¹.',428)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (237,'PN-79/C-04596.01','Woda i œcieki.Badania zawartoœci cynku.Oznaczanie cynku metod¹ ditizonow¹.',429)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (238,'PN-79/C-04596.02','Woda i œcieki.Badania zawartoœci cynku metod¹ cynkonow¹.',430)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (239,'PN-75/C-04600.10','Badania zawartoœci chloru i jego zwi¹zków oraz zapotrzebowania chloru.Oznaczanie zazpotrzebowania chloru.',431)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (240,'EN ISO 1127:1996','Rury ze stali nierdzewnych.Wymiary,tolerancje i teoretyczne masy na jednostkê.',436)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (241,'PN-EN ISO 1101:2006(','Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia.',437)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (242,'PN-87/M-01145','Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia.',437)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (243,'PN-80/M-02138','Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia.',437)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (244,'PN-78/M-02137','Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia.',437)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (245,'PN-EN 55020:2003(U)','Odbiorniki radiofoniczne i telewizyjne i ich uzr¹dzenia dodatkowe.Charakterystyki odpornoœci.Poziomy dopuszczalne i metody pomiarów.',438)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (246,'PN-EN 55020:1996','Odbiorniki radiofoniczne i telewizyjne i ich uzr¹dzenia dodatkowe.Charakterystyki odpornoœci.Poziomy dopuszczalne i metody pomiarów.',438)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (247,'PN-EN 15038:2006(U)','Us³ugi t³umaczeniowe.Wymagania dotycz¹ce œwiadczenia us³ug.',439)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (248,'PN-EN 10224:2004','Rury i z³¹czki ze stali niestopowej do transportu wody i innych p³ynów wodnych.Warunki tachniczne dostawy.',440)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (249,'PN-EN 10224:2004/A1:','Rury i z³¹czki ze stali niestopowej do transportu wody i innych p³ynów wodnych.Warunki tachniczne dostawy.',440)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (250,'PN-EN 1540:2002(U)','Powietrze na stanowiskach pracy.Terminologia.',446)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (251,'PN-EN ISO/IEC 17011:','Ocena zgodnoœci.Wymagania ogólne dla jednostek akredytuj¹cych prowadz¹cych akredytacjê jednostek oceniaj¹cych zgodnoœæ.',447)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (252,'PN-EN ISO 14122-4:20','Bezpieczeñstwo maszyn.Sta³e œrodki dostêpu do maszyn.Czêœæ 4: Drabiny sta³e.',448)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (253,'PN-EN 1780-2:2003(U)','Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia z aluminium stopowego, stopów wstêpnych i odlewów.Czêœæ 2: System oznaczeñ na podstawie symboli chemicznych.',449)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (254,'PN-EN 573-2:1997','Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia z aluminium stopowego, stopów wstêpnych i odlewów.Czêœæ 2: System oznaczeñ na podstawie symboli chemicznych.',449)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (255,'PN-EN 1780-2:1999','Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia z aluminium stopowego, stopów wstêpnych i odlewów.Czêœæ 2: System oznaczeñ na podstawie symboli chemicznych.',449)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (256,'PN-EN 45010:2000','Ocena zgodnoœci.Wymagania ogólne dla jednostek akredytuj¹cych prowadz¹cych akredytacjê jednostek oceniaj¹cych zgodnoœæ.',447)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Uwagi,Nor_nor_id) values  (257,'PN-80/M-49060','Bezpieczeñstwo maszyn.Sta³e œrodki dostêpu do maszyn.Czêœæ 4: Drabiny sta³e.','egz.1 zagubiony.',448)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (258,'PN-EN 1067:2006(U)','Kleje.Ocena i przygotowanie próbek do badañ.',450)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (259,'PN-EN 1067:1999','Kleje.Ocena i przygotowanie próbek do badañ.',450)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (260,'PN-EN 1047-1:2006(U)','Pomieszczenia i urz¹dzenia do przechowywania wartoœci.Klasyfikacja i metody badañ odpornoœci ogniowej.Czêœæ 1: Szafy na noœniki danych i wk³adki na dyskietki.',451)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (261,'PN-EN 1047-1:1999','Pomieszczenia i urz¹dzenia do przechowywania wartoœci.Klasyfikacja i metody badañ odpornoœci ogniowej.Czêœæ 1: Szafy na noœniki danych i wk³adki na dyskietki.',451)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (262,'PN-EN 827:2006(U)','Kleje.Oznaczanie umownej i sta³ej zawartoœci suchej substancji.',452)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (263,'PN-EN 827:1996','Kleje.Oznaczanie umownej i sta³ej zawartoœci suchej substancji.',452)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (264,'PN-80/Z-04108.02','Ochrona czystoœci powietrz.Badania zawartoœci olejów.Czêœæ 6: Oznaczanie oleju mineralnego(faza ciek³a aerozolu) na stanowiskach pracy metod¹ spektrometrii absorpcyjnej w nadfiolecie.',453)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (265,'AQAP 2110 wyd.1','Wymagania NATO dotycz¹ce zapewnienia jakoœci w projektowaniu, pracach rozwojowych i produkcji.',456)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (266,'AQAP 2130 wyd.1','Wymagania NATO dotycz¹ce zapewnienia jakoœci w kontroli i badaniach.',457)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (267,'PN-EN 559:1998','Sprzêt do spawania gazowego.Wê¿e gumowe stosowane pzry spawaniu,ciêciu i procesach pokrewnych.',458)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (268,'PN-EN 10108:2005(U)','Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje.',459)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (269,'PN-75/H-93200-03','Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje.',459)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (270,'PN-75/H-93200-05','Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje.',459)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (271,'PN-89/E-06702','Maszyny elektryczne wiruj¹ce.Metody wyznaczania strat i sprawnoœci na podstawie badañ (z wyj¹tkiem maszyn pojazdów trakcyjnych)',460)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (272,'PN-EN 60034-5:2002(U','Maszyny elektryczne wiruj¹ce.Czêœæ 5:Stopnie ochrony zapewniane przez rozwi¹zania konstrukcyjne maszyn elektrycznych wiruj¹cych (kod IP).Klasyfikacja.',461)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (273,'PN-IEC 34-6:1994','Maszyny elektryczne wiruj¹ce.Sposoby ch³odzenia (kod IC)',462)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (274,'PN-EN 60034-7:1998','Maszyny elektryczne wiruj¹ce.Czêœæ 7:Klasyfikacja form wykonania,sposobów monta¿u i umiejscowienia skrzynki zaciskowej (kod IM)',463)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (275,'PN-EN 60034-7:1998/A','Maszyny elektryczne wiruj¹ce.Czêœæ 7:Klasyfikacja form wykonania,sposobów monta¿u i umiejscowienia skrzynki zaciskowej (kod IM)',463)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (276,'PN-90/E-06722','Maszyny elektryczne wiruj¹ce.Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Rozmiar obudowy od 56 do 400 i rozmiar ko³nierzy od 55 do 1080',465)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (277,'PN-90/E-06723','Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Czêœæ 2:Rozmiary obudowy od 355 do 1000 i rozmiary ko³nierza od 1180 do 2360.',466)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (278,'PN-89/E-05012','Urz¹dzenia elektroenergetyczne.Dobór silników elektrycznych i ich instalowanie.Ogólne wymagania i odbiór techniczny.',467)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (279,'BN-89/3016-01','Maszyny elektryczne wiruj¹ce.Maszyny do sterowania.Silniki pr¹du sta³ego o magnesach trwa³ych.',468)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (280,'PN-64/E-04252','Maszyny elektryczne wiruj¹ce.Wyznaczanie momentu bezw³adnoœci czêœci wiruj¹cych.',470)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (281,'PN-ISO/IEC 17799:200','Technika informatyczna.Techniki bezpieczeñstwa.Praktyczne zasady zarz¹dzania bezpieczeñstwem infomacji.',477)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (282,'PN-EN 10002-1:2002(U','Metale.Próba rozci¹gania.Czêœæ 1:Metoda badania w temperaturze otoczenia.',478)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (283,'PN-I-07799-2:2005','Technika informatyczna.Techniki bezpieczeñstwa.Systemy zarz¹dzania bezpieczeñstwem informacji.Wymagania.',479)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (284,'PN-71/Z-04061/01','Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej.',480)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (285,'PN-71/Z-04061/02','Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej.',480)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (286,'PN-71/Z-04061/03','Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej.',480)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (287,'PN-73/C-04603.01','Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych,zwi¹zanych i ogólnych metod¹ kolorymetryczn¹ z kwasem barbiturowym i pirydyn¹.',482)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (288,'PN-73/C-04603.02','Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych zwi¹zanych i ogólnych metod¹ miareczkow¹,argenometryczn¹',483)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (289,'PN-72/C-04604.01','Woda i œcieki.Badania zawartoœci chromu.Postanowienia ogólne i zakres normy.',486)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (290,'PN-72/C-04604.02','Woda i œcieki.Badania zawartoœci chromu metod¹ kolorymetryczn¹ z dwufenylokarbazydem.',487)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (291,'PN-72/C-04604.08,','Woda i œcieki.Badania zawartoœci chromu.Oznaczanie chromu szeœciowartoœciowego Cr 6+ i trójwartoœciowego Cr 3+',488)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (292,'PN-72/C-04604.10','Woda i œcieki.Badania zawartoœci chromu.Oznaczanie chromu szeœciowartoœciowego Cr 6+ i trójwartoœciowego Cr 3+',488)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (293,'PN-76/C-04605.00','Woda i œcieki.Badania zawartoœci glinu.Postanowienia ogólne.',489)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (294,'PN-76/C-04605.01','Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ z eriochromocyjanin¹ R.',490)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (295,'PN-76/C-04605.03','Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ warsenianow¹.',491)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (296,'PN-72/C-04610.04','Woda i œcieki.Badania toksycznoœci zanieczyszczeñ dla organizmów wodnych.Oznaczanie toksyczniœci ostrej na gupiku...',492)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (297,'PN-80/C-04611.02','Woda i œcieki.Badania zawartoœci miedzi...',494)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (298,'PN-72/C-04611.04','Woda i œcieki.Badania zawartoœci miedzi...',494)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (299,'PN-75/C-04614.01','Woda i œcieki.Badania zawartoœci niklu.Oznaczanie niklu metod¹ kolorymetryczn¹ z furylodwuoksymem.',495)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (300,'PN-69/C-04552','Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków w wodzie metod¹ argentometrycznego miareczkowania.',499)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (301,'PN-68/C-04513','Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków w wodzie metod¹ argentometrycznego miareczkowania.',499)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (302,'PN-74/C-04620.05','Woda i œcieki,Pobieranie próbek wody i pary z urz¹dzeñ energetycznych i ruroci¹gów do analizy fizycznej i chemicznej.',503)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (303,'PN-74/C-04621','Woda i œcieki,Pobieranie próbek wody i pary z urz¹dzeñ energetycznych i ruroci¹gów do analizy fizycznej i chemicznej.',503)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (304,'BN-77/6040-02','Barwienie,barwniki,pigmenty i rozjaœniacze optyczne.Terminologia.',510)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (305,'BN-85/6045-23','Barwienie,barwniki,pigmenty i rozjaœniacze optyczne.Terminologia.',510)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (306,'PN-EN ISO 15011-2:20','Zdrowie i bezpieczeñstwo przy spawaniu i procesach pokrewnych.Metoda laboratoryjna pobierania próbek py³u i gazów powstaj¹cych podczas spawania ³ukowego.Czêœæ 2:Okreœlanie wielkoœci emisji gazów, z wyj¹tkiem ozonu.',511)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (307,'PN-EN 61160:2006(U)','Przegl¹d projektu.',512)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (308,'PN-EN 60998-2-3:2005','Osprzêt po³¹czeniowy do obwodów niskiego napiêcia do u¿ytku domowego i podobnego.Czêœæ 2-3: Wymagania szczegó³owe dotycz¹ce samodzielnych z³¹czek z ostrzowymi elementami zaciskowymi.',513)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (309,'PN-IEC 998-2-3:1997','Osprzêt po³¹czeniowy do obwodów niskiego napiêcia do u¿ytku domowego i podobnego.Czêœæ 2-3: Wymagania szczegó³owe dotycz¹ce samodzielnych z³¹czek z ostrzowymi elementami zaciskowymi.',513)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (310,'PN-EN 10088-3:2005(U','Stale odporne na korozjê.Czêœæ 3:Warunki techniczne dostawy pó³fabrykatów,prêtów,walcówki,drutu,kszta³towników i wyrobów o powierzchni jasnej ze stali nierdzewnych ogólnego przeznaczenia.',514)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (311,'PN-EN 10088-2:2005(U','Stale odporne na korozjê.Czêœæ 2: Warunki techniczne dostawy blach i taœm ze stali nierdzewnych ogólnego przeznaczenia.',515)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (312,'PN-76/C-04702','Barwniki.Ogólne metody badañ.',516)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (313,'BN-81/6041-33','Barwniki.Ogólne metody badañ.',516)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (314,'BN-86/6044-14','Barwniki.Ogólne metody badañ.',516)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (315,'BN-74/6044-13','Barwniki.Barwniki zasadowe.Metody badañ.',517)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (316,'PN-66/C-04801','Œrodki powierzchniowo czynne.Oznaczanie w³¹snoœci pianotwórczych.',519)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (317,'PN-74/C-04904','Œrodki ochrony drewna.Badanie agresywnoœci korozyjnej wobec stali metod¹ bezpoœredni¹.',522)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (318,'PN-68/C-04950','Analiza chemiczna.Kompleksometryczne metody oznaczania zawartoœci kationu g³ównego sk³adnika.',524)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (319,'PN-68/C-04951','Analiza chemiczna.Oznaczanie skrêcalnoœci w³aœciwej produktów organicznych.',526)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (320,'PN-68/C-04953',528)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (321,'PN-76/C-04957','Odczynniki.Oznaczanie pozosta³oœci nielotnej.',529)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (322,'PN-76/C-04958','Odczynniki.Oznaczanie pozosta³oœci po pra¿eniu.',530)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (323,'PN-76/C-04959','Oznaczanie zawartoœci wody metod¹ Karola Fischera w produktach organicznych i nieorganicznych.',531)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (324,'PN-77/C-04963','Analiza chemiczna.Oznaczanie pH wodnych roztworów produktów chemicznych',534)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (325,'PN-81/C-06500','Analiza chemiczna.Przygotowanie odczynników i roztworów pomocniczych',542)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (326,'PN-76/C-06501','Analiza chemiczna.Przygotowanie roztworów wska¿ników.',543)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (327,'PN-68/C-06500','Analiza chemiczna.Przygotowanie roztworów do kolorymetrii i nefelometrii',544)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (328,'PN-76/C-06501','Analiza chemiczna.Przygotowanie roztworów buforowych.',545)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (329,'PN-82/C-23050','Karbid.',550)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (330,'PN-57/C-24005','Gliceryna destylowana.',551)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (331,'PN-60/C-40006','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Wymagania i badania.',552)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (332,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Wymagania i badania.',552)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (333,'PN-60/C-40006','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pozosta³oœci po spopieleniu.',553)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (334,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pozosta³oœci po spopieleniu.',553)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (335,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury wrzenia.',554)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (336,'PN-60/C-40006','P³yny noskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pH.',555)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (337,'PN-75/C-40007','P³yny noskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pH.',555)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (338,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie rezerwy alkalicznej.',556)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (339,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie sk³onnoœci do pienienia.',557)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (340,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Badanie w³aœciwoœci korozyjnych w naczyniu szklanym.',558)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (341,'PN-75/C-40007','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury krystalizacji.',559)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (342,'PN-60/C-40006','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury krystalizacji.',559)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (343,'PN-78/C-6020-03','Glikole etylenowe.Metody badañ.',560)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (344,'BN-73/6026-61','Octan etylu technicznego.',565)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (345,'PN-74/C-97072','Wêglowodory aromatyczne.Metody badañ.Oznaczanie odczynu wyci¹gu wodnego.',567)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (346,'PN-68/C-97062','Wêglowodory aromatyczne.Metody badañ.Oznaczanie intensywnoœci zabarwienia w próbie z kwasem siarkowym wg.wzorców dwuchromianowych.',568)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (347,'BN-80/0551-02','Wêglowodory aromatyczne.Metody badañ.Oznaczanie zawartoœci siarki metod¹ redukcji niklem Raney a.',570)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (348,'PN-ISO 37:1998','Guma i kauczuk termoplastyczny.Oznaczanie w³aœciwoœci wytrzyma³oœciowych przy rozci¹ganiu.',574)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (349,'PN-EN ISO 18273:2005','Materia³y dodatkowe do spawania.Druty elektrodowe i prêty do spawania aluminium i stopów aluminium.Klasyfikacja.',575)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (350,'PN-75/M-69414','Materia³y dodatkowe do spawania.Druty elektrodowe i prêty do spawania aluminium i stopów aluminium.Klasyfikacja.',575)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (351,'PN-EN ISO 9606-2:200','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 2:Aluminium stopy aluminium.',576)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (352,'PN-EN 287-2+A1:1998','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 2:Aluminium stopy aluminium.',576)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (353,'PN-EN 60079-0:2004(U','Urz¹dzenia elektryczne w przestrzeniach zagro¿inych wybuchem gazów.Czêœæ 0:Wymagania ogólne.',577)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (354,'PN-EN 50014:2004','Urz¹dzenia elektryczne w przestrzeniach zagro¿inych wybuchem gazów.Czêœæ 0:Wymagania ogólne.',577)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (355,'PN-EN 10027-1:2005(U','Systemy oznaczania stali.Czêœæ 1:Znaki stali.',578)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (356,'PN-EN 10025-1:2005(U','Wyroby walcowane na gor¹co ze stali konstrukcyjnych .Czêœæ 1:Ogólne warunki techniczne dostawy.',579)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (357,'PN-EN 10025-2:2005(U','Wyroby walcowane na gor¹co ze stali konstrukcyjnych.Czêœæ 2:Warunki techniczne dostawy stali konstrukcyjnych niestopowych.',580)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (358,'PN-IEC 60050-826:200','Miêdzynarodowy s³ownik terminologiczny elektryki,.Czêœæ 826:Instalacje elektryczne.',581)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (359,'PN-EN 287-1:2005(U)','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 1:Stale.',582)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (360,'PN-EN 287-1:1998','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 1:Stale.',582)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (361,'PN/C-60009','Próbniki do pobierania próbek produktów bezkszta³tnych.',595)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (362,'PN/C-60010','Próbniki do pobierania próbek produktów bezkszta³tnych.',595)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (363,'PN-87/C-80001','Odczynniki i substancje specjalne czyste.Pakowanie,przechowywanie i transport.',597)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (364,'PN-88/C-80047','Odczynniki i substancje specjalne czyste.Ogólne wytyczne pobierania próbek i przygotowania...',598)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (365,'PN-72/C-81015','Biel cynkowa.',599)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (366,'PN-75/C-81505','Oznaczanie pozosta³oœci na sicie w wyrobach lakierowych i farbach graficznych',601)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (367,'BN-65/7469-05','Oznaczanie pozosta³oœci na sicie w wyrobach lakierowych i farbach graficznych',601)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (368,'PN-67/C-81507','Wyroby lakierowe.Oznaczanie rozlewnoœci.',603)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (369,'PN-79/C-81512','Wyroby lakierowane.Oznaczanie zawartoœci sk³adników podstawowych.',605)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (370,'PN-70/C-81514','Wyroby lakierowane.Sposoby otrzymywania pow³ok do badañ.',606)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (371,'PN-67/C-81516','Wyroby lakierowe.Oznaczanie œcieralnoœci pow³ok lakierowych.',608)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (372,'PN-59/C-81518','Wyroby lakierowe.Oznaczanie porowatoœci pow³ok lakierowych.',609)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (373,'PN-69/C-81519','Wtroby lakierowe.Okreœlanie stopnia wyschniêæ i czasu wysychania.',610)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (374,'PN-66/C-81521','Wyroby lakierowe.Badania odpornoœci pow³ok lakierowych na dzia³anie wody oraz oznaczanie nasi¹kliwoœci.',612)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (375,'PN-EN ISO 3613:2002(','Konwersyjne pow³oki chromianowe na cynku, kadmie oraz stopach aluminium-cynk i cynk-aluminium.Metody badañ.',613)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (376,'PN-86/J-02000','Ochrona radioplogiczna.Zamkniête ¿ród³a promieniotwórcze.Wymagania ogólne i klasyfikacja.',614)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (377,'PN-74/J-01003.13','Technika j¹drowa.Nazwy i okreœlenia.Transport materia³ów promieniotwórczych.',616)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (378,'PN-73/J-01003.04','Technika j¹drowa.Nazwy i okreœlenia.¯ród³a promieniotwórcze.',617)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (379,'PN-71/H-93451','Ceowniki ekonomiczne stalowe walcowane na gor¹co.Wymiary.',620)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (380,'PN-EN 60296:2005(U)','Ciecze stosowane w elektrotechnice.Œwie¿e mineralne oleje elektroizolacyjne do transformatorów i aparatury ³¹czeniowej.',621)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (381,'PN-EN 13247:2002(U)','Opakowania.Wymagania dla taœm opasuj¹cych stalowych do opakowañ przeznaczonych do podnoszenia, mocowania i zabezpieczania ³adunków.',622)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (382,'PN-EN 352-7:2003(U)','Ochronniki s³uchu.Wymagania bezpieczeñstwa i badania.Czêœæ 7:Wk³adki przeciwha³asowe o regulowanym t³umieniu.',624)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (383,'PN-EN 60942:2004(U)','Elektroakustyka.Kalibratory akustyczne.',625)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (384,'PN-EN ISO 7200:2005(','Dokumentacja techniczna wyrobu.Pola danych w tabliczkach rysunkowych i nag³ówkach dokumentów',627)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (385,'PN-85/M-01119','Dokumentacja techniczna wyrobu.Pola danych w tabliczkach rysunkowych i nag³ówkach dokumentów',627)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (386,'NO-10-A800:1998','Malowanie maskuj¹ce uzbrojenia i sprzêtu wojskowego.Wymagania ogólne.',628)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (387,'NO-17-A800:1998','Ochrona wojskowego sprzêtu technicznego przed korozj¹ i starzeniem.Malowanie sprzêtu lotniczego.Wymagania ogólne i badania.',629)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (388,'NO-42-A201:1998','Sprzêt do wykrywania ska¿eñ chemicznych.Urz¹dzenia wielokrotnego u¿ytku do wykrywania lub pomiaru stê¿enia substancji chemicznych w powietrzu.Klasyfikacja.',630)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (389,'NO-68-A200:1998','Bojowe œrodki truj¹ce.Wzorzec sarinu.Wymagania i badania.',631)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (390,'PN-EN 60825-1:2000','Bezpieczeñstwo urz¹dzeñ laserowych.Czêœæ 1: Klasyfikacja sprzêtu,wymagania i przewodnik u¿ytkownika.',633)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (391,'PN-EN 60825-1:2000/A','Bezpieczeñstwo urz¹dzeñ laserowych.Czêœæ 1: Klasyfikacja sprzêtu,wymagania i przewodnik u¿ytkownika.',633)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (392,'PN-93/H-92748','Aluminium i stopy aluminium.P³yty ¿eberkowe.Specyfikacje.',634)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (393,'PN-89/E-04614/07','Badanie zagro¿enia ogniowego.Czêœæ 1-3-:Wytyczne oceny zagro¿enia ogniowego wyrobów elektrotechnicznych .Stosowanie procedur doboru wstêpnego.',636)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (394,'PN-EN 60695-1-30:200','Badanie zagro¿enia ogniowego.Czêœæ 1-3-:Wytyczne oceny zagro¿enia ogniowego wyrobów elektrotechnicznych .Stosowanie procedur doboru wstêpnego.',636)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (395,'PN-EN 61000-3-2:2006','Kompatybilnoœæ elektromagnetyczna (EMC)Czêœæ 3-2:Poziomy dopuszczalne emisji harmonicznych pr¹du(fazowy pr¹d zasilaj¹cy odbiornika < 16A)',637)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (396,'PN-EN 50133-1:2000','Systemy alarmowe.Systemy kontroli dostêpu w zastosowaniach dotycz¹cych zabezpieczenia.Czêœæ 1:Wymagania systemowe.',638)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (397,'PN-ISO 10005:1998','Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce planów jakoœci.',640)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (398,'PN-EN 10210-1:2006(U','Kszta³towniki zamkniête wykonane na gor¹co ze stali konstrukcyjnych niestopowych i drobnoziarnistych.Czêœæ 1: Warunki techniczne dostawy',641)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (399,'PN-ISO 10006:2002','Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce zarz¹dzania jakoœci¹ w pzredsiêwziêciach.',642)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (400,'IPC-A-610PL:2000','Dopuszczlnoœæ zespo³ów elektrycznych.',643)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (401,'IPC J-STD-001D:2000','Requirements for Soldered Electrical and Electronic Assemblies.',649)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (402,'IPC-7095:2000','Design and Assembly Process Implementation for BGAs/',651)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (403,'PN-EN ISO 22000:2005','Systemy zarz¹dzania bezpieczeñstwem ¿ywnoœci.Wymagania dla ka¿dej organizacji naje¿¹cej do ³añcuch ¿ywnoœciowego.',652)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (404,'PN-66/C-81521','Wyroby lakierowe.Badania odpornoœci pow³ok lakierowych na dzia³anie wody oraz oznaczanie nasi¹kliwoœci.',656)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (405,'PN-78/C-81523','Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie mg³y solnej.',657)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (406,'PN-64/C-81525','Wyroby lakierowe.Badanie odpornoœci pow³ok na dzia³anie atmosfery nasyconej par¹ wodn¹.',658)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (407,'PN-73/C-81531','Wyroby lakierowe.Okreœlanie przyczepnoœci pow³ok do pod³o¿a oraz przyczepnoœci miêdzywarstwowej.',659)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (408,'PN-70/C-81536','Wyroby lakierowe.Oznaczanie krycia.',661)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (409,'PN-66/C-81539','Wyroby lakierowe.Oznaczanie œciekalnoœci.',662)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (410,'PN-67/C-81524','Wyroby lakierowe.Przybli¿one metody obliczania zu¿ycia i wydajnoœci.',663)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (411,'PN-86/C-81549/01','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Postanowienia ogólne i zakres normy.',666)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (412,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych,Sprawdzanie i przygotowywanie szk³a laboratoryjnego do oznaczeñ metod¹ spektrofotometryczn¹.',667)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (413,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci o³owiu.',668)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (414,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci antymonu.',669)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (415,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci arsenu.',670)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (416,'PN-81/C-81549','wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci kadmu.',671)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (417,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci rtêci.',673)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (418,'PN-81/C-81549','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci chromu.',674)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (419,'PN-81/C-81549','Wyroby lakieowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci baru.',677)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (420,'BN-79/7469-09.05','Oznaczanie lepkoœci wyrobów lakierowych i farb graficznych za pomoc¹ lepkoœciomierzy Rotothinner.',691)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (421,'BN-66/6110-15','Wyroby lakierowe.Badanie odpornoœci pow³ok lakierowych na dzia³anie zmiennych temperatur.',693)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (422,'BN-78/6110-02','Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie wody morskiej.',694)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (423,'BN-76/6115-05','Emalie celulozowe.',697)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (424,'BN-82/6115-29','Emalie celulozowe.',697)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (425,'BN-83/6115-66','Emalie celulozowe.',697)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (426,'BN-86/6115-71','Emalie celulozowe.',697)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Nor_nor_id) values  (427,'patrz norma',698)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (428,'BN-75/6115-02','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (429,'BN-64/6115-12','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (430,'BN-75/6115-34','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (431,'BN-75/6115-35','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (432,'BN-76/6115-38','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (433,'BN-76/6115-60','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (434,'BN-80/6115-65','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (435,'BN-78/6115-70','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.',699)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (436,'BN-76/6115-17','Emalie chlorokauczukowe.',700)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (437,'BN-73/6115-18','Emalie chlorokauczukowe.',700)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (438,'BN-80/6113-04','Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu.',703)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (439,'BN-72/6113-52','Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu.',703)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (440,'BN-83/6113-77','Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu.',703)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (441,'BN-75/6114-10','Lakiery nitrocelulozowe.',704)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (442,'BN-75/6114-29','Lakiery nitrocelulozowe.',704)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (443,'BN-75/6114-42','Lakiery nitrocelulozowe.',704)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (444,'BN-83/6114-64','Lakiery nitrocelulozowe.',704)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (445,'PN-C-81901:1997','Farby olejne i alkidowe.',705)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (446,'PN-C-81910:1997','Farby chlorokauczukowe.',706)
GO
insert into Normy_zastapione (Id_nor_zas,Sygnatura,Tytul,Nor_nor_id) values  (447,'BN-78/6113-32','Farby epoksydowe do gruntowania odporne na czynniki chemiczne.',707)
GO
