
insert into Normy_egzemplarz (Id_nor_egz,Inw_inw_id,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (33,6,76,12,3,'12')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (34,79,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (35,80,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (36,81,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (37,82,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (38,84,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (39,84,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (40,86,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Spn_spn_id,Sygnatura) values  (41,88,1,'1,2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (42,89,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (43,90,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (44,91,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (45,92,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Spn_spn_id,Sygnatura) values  (46,93,1,'1,2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (47,94,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (48,95,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (49,96,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (50,97,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Spn_spn_id,Sygnatura) values  (51,98,1,'1,2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (52,99,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (53,100,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (54,101,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (55,102,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (56,102,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (57,102,4,1,'4')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (58,98,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (59,98,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (60,93,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (61,93,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (62,88,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (63,88,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (64,105,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (65,105,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (66,105,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (67,107,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (68,108,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (69,109,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura,Uwagi) values  (70,109,1,1,'1','egz. zagubiony')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Spn_spn_id,Sygnatura) values  (71,109,1,'1(zagubiony)')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (72,109,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (76,118,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (77,118,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (78,119,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (79,120,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (80,121,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (81,122,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (82,122,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (83,123,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (84,124,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (85,125,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (86,126,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (87,127,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (88,128,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (89,129,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (90,130,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (91,131,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (92,132,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (93,133,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (94,134,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (95,135,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (96,136,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (97,137,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (98,139,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (99,140,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (100,141,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (101,142,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (102,142,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (103,143,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (104,144,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (105,145,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (106,145,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (107,146,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (108,147,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (109,147,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (110,149,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (111,149,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (112,151,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (113,152,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (114,154,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (115,155,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (116,155,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (117,156,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (118,157,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (119,158,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (120,158,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (121,160,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (122,160,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (123,161,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (124,161,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (125,162,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (126,163,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (127,163,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (128,164,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (129,164,2,3,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (130,165,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (131,166,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (132,166,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (133,167,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (134,168,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (135,169,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (136,170,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (137,171,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (138,172,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (139,173,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (140,174,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (141,175,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (142,176,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (143,177,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (144,178,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (145,179,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (146,179,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (147,182,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (148,183,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (149,184,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (150,185,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (151,186,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (152,187,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (153,188,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (154,189,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (155,192,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (156,192,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (157,195,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (158,195,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (159,196,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (160,197,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (161,198,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (162,199,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (163,200,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (164,201,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (165,202,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (166,203,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (167,204,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (168,205,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (169,206,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (170,207,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (171,208,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (172,209,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (173,210,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (174,211,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (175,212,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (176,213,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (177,214,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (178,216,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (179,217,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (180,218,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (181,219,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (182,220,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (183,221,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (184,222,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (185,222,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (186,223,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (187,225,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (188,225,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (189,226,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (190,227,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (191,228,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (192,229,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (193,230,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (194,231,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (195,231,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (196,232,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (197,233,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (198,234,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (199,235,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (200,236,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (201,237,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (202,238,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (203,239,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (204,239,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (205,240,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (206,241,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (207,241,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (208,242,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (209,243,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (210,244,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (211,245,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (212,246,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (213,247,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (214,247,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (215,248,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (216,249,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (217,249,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (218,250,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (219,251,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (220,251,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (221,252,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (222,253,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (223,254,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (224,255,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (225,256,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (226,256,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (227,258,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (228,259,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (229,260,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (230,261,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (231,262,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (232,263,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (233,264,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (234,265,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (235,265,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (236,266,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (237,266,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (238,267,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (239,268,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (240,268,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (241,268,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (242,269,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (243,270,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (244,271,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (245,273,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (246,274,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (247,275,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (248,276,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (249,277,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (250,278,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (251,278,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (252,279,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (253,279,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (254,280,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (255,281,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (256,282,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (257,283,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (258,283,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (259,285,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (260,285,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (261,286,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (262,286,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (263,287,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (264,288,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (265,289,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (266,290,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (267,291,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (268,291,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (269,292,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (270,294,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (271,295,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (272,296,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (273,297,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (274,298,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (275,299,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (276,300,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (277,300,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (278,301,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (279,301,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (280,303,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (281,304,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (282,306,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (283,307,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (284,308,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (285,308,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (286,309,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (287,310,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (288,311,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (289,312,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (290,314,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (291,315,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (292,316,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (293,317,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (294,318,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (295,319,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (296,319,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (297,320,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (298,321,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (299,322,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (300,322,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (301,324,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (302,325,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (303,326,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (304,327,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (305,328,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (306,329,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (307,330,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (308,331,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (309,332,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (310,333,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (311,334,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (312,335,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (313,336,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (314,338,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (315,339,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (316,340,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (317,342,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (318,343,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (319,344,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (320,345,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (321,346,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (322,347,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (323,349,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (324,350,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (325,351,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (326,352,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (327,353,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (328,354,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (329,355,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (330,356,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (331,357,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (332,358,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (333,359,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (334,361,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (335,362,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (336,363,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (337,365,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (338,366,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (339,367,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (340,368,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (341,369,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (342,370,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (343,371,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (344,372,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (345,373,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (346,374,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (347,375,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (348,376,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (349,377,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (350,378,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (351,380,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (352,381,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (353,382,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (354,383,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (355,385,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (356,385,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (357,386,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (358,387,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (359,388,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (360,389,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (361,390,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (362,391,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (363,392,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (364,393,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (365,394,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (366,395,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (367,396,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (368,397,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (369,398,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (370,399,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (371,400,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (372,401,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (373,402,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (374,403,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (375,405,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (376,406,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (377,407,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (378,408,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (379,409,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (380,410,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (381,412,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (382,413,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (383,414,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (384,416,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (385,417,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (386,418,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (387,418,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (388,419,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (389,421,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (390,422,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (391,423,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (392,424,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (393,425,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (394,426,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (395,427,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (396,428,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (397,429,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (398,430,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (399,431,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (400,433,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (401,435,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (402,436,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (403,437,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (404,437,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (405,437,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (406,437,4,1,'4')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (407,437,5,1,'5')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (408,437,6,1,'6')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (409,437,7,1,'7')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (410,437,8,1,'8')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (411,437,9,1,'9')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (412,437,10,1,'10')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (413,438,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (414,439,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (415,440,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (416,442,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (417,443,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (418,444,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (419,445,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (420,446,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (421,447,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (422,448,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (423,449,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (424,442,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (425,442,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (426,450,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (427,451,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (428,452,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (429,453,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (430,435,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (431,435,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (432,455,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (433,456,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (434,457,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (435,458,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (436,459,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (437,460,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (438,461,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (439,462,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (440,463,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (441,464,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (442,465,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (443,466,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (444,467,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (445,468,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (446,469,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (447,470,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (448,471,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (449,472,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (450,473,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (451,474,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (452,475,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (453,476,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (454,477,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (455,478,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (456,479,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (457,480,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (458,481,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (459,482,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (460,482,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (461,483,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (462,484,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (463,486,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (464,486,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (465,487,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (466,487,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (467,488,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (468,488,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (469,489,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (470,490,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (471,491,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (472,492,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (473,493,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (474,494,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (475,495,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (476,496,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (477,497,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (478,498,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (479,499,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (480,499,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (481,501,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (482,502,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (483,503,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (484,504,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (485,505,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (486,506,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (487,507,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (488,508,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (489,509,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (490,510,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (491,511,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (492,512,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (493,513,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (494,514,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (495,514,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (496,514,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (497,515,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (498,515,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (499,516,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (500,517,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (501,518,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (502,519,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (503,520,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (504,521,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (505,522,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (506,523,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (507,524,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (508,526,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (509,528,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (510,529,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (511,530,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (512,531,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (513,531,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (514,532,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (515,533,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (516,534,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (517,535,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (518,535,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (519,536,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (520,537,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (521,538,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (522,539,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (523,540,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (524,541,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (525,542,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (526,543,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (527,544,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (528,545,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (529,546,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (530,547,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (531,548,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (532,549,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (533,550,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (534,551,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (535,552,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (536,552,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (537,552,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (538,553,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (539,554,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (540,555,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (541,556,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (542,557,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (543,558,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (544,559,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (545,560,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (546,561,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (547,562,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (548,563,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (549,564,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (550,565,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (551,565,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (552,566,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (553,567,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (554,568,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (555,569,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (556,570,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (557,571,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (558,572,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (559,573,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (560,574,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (561,575,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (562,576,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (563,577,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (564,578,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (565,579,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (566,579,2,3,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (567,579,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (568,580,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (569,581,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (570,582,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (571,583,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (572,584,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (573,585,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (574,586,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (575,587,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (576,588,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (577,589,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (578,591,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (579,592,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (580,593,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (581,594,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (582,595,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (583,596,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (584,597,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (585,598,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (586,599,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (587,600,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (588,601,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (589,602,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (590,603,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (591,605,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (592,606,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (593,608,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (594,609,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (595,610,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (596,612,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (597,613,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (598,614,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (599,616,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (600,617,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (601,618,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (602,619,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (603,620,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (604,621,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (605,622,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (606,624,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (607,625,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (608,627,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (609,628,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (610,629,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (611,630,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (612,631,1,3,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (613,632,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (614,633,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (615,634,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (616,635,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (617,636,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (618,637,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (619,638,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (620,639,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (621,640,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (622,640,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (623,640,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (624,641,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (625,642,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (626,643,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (627,643,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (628,643,3,1,'3')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (629,644,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (630,645,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (631,646,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (632,647,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (633,649,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (634,650,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (635,651,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (636,652,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (637,653,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (638,654,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (639,655,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (640,656,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (641,657,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (642,658,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (643,659,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (644,660,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (645,659,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (646,659,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (647,661,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (648,662,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (649,663,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (650,664,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (651,665,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (652,666,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (653,667,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (654,668,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (655,669,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (656,670,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (657,671,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (658,673,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (659,674,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (660,675,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (661,676,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (662,677,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (663,678,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (664,681,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (665,682,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (666,683,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (667,684,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (668,685,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (669,686,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (670,687,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (671,688,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (672,689,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (673,690,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (674,691,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (675,692,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (676,693,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (677,694,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (678,695,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (679,696,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (680,697,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (681,697,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (682,698,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (683,698,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (684,699,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (685,699,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (686,700,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (687,700,2,1,'2')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id) values  (688,700)
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (689,701,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (690,702,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (691,703,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (692,704,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (693,705,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (694,706,1,1,'1')
GO
insert into Normy_egzemplarz (Id_nor_egz,Nor_nor_id,Nr_inwentarzowy,Spn_spn_id,Sygnatura) values  (695,707,1,1,'1')
GO
