
insert into Normy_wydawca (Id_nor_wyd,Data,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id) values  (2,'2000.08.11','Warszawa','Polski Komitet Normalizacyjny','PKN',74,4)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (3,'Warszawa','Polski Wydawca','Pw',76,34,5,9)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (4,'Warszawa','Polski Komitet Normalizacyjny','PKN',78,34,5,2)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (5,'Warszawa','Polski Komitet Normalizacyjny','PKN',79,34,4,2)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (6,'Warszawa','Polski Komitet Normalizacyjny','PKN',80,34,4,2)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (7,'Warszawa','Polski Komitet Normalizacyjny','PKN',81,34,4,2)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (8,'Warszawa','Polski Komitet Normalizacyjny','PKN',82,34,5,2)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (9,'Warszawa','Polski  Komitet Normalizacyjny','PKN',84,34,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (10,'Warszawa','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','WCNKiJ',85,34,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (11,'Polski  Komitet Normalizacyjny',86,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (12,'Polski  Komitet Normalizacyjny',88,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (13,'Polski  Komitet Normalizacyjny',89,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (14,'Polski  Komitet Normalizacyjny',90,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (15,'Polski  Komitet Normalizacyjny',91,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (16,'Polski  Komitet Normalizacyjny',92,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (17,'Polski  Komitet Normalizacyjny',93,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (18,'Polski  Komitet Normalizacyjny',94,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (19,'Polski  Komitet Normalizacyjny',95,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (20,'Polski  Komitet Normalizacyjny',96,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (21,'Polski  Komitet Normalizacyjny',97,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (22,'Polski  Komitet Normalizacyjny',98,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (23,'Polski  Komitet Normalizacyjny',99,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (24,'Polski  Komitet Normalizacyjny',100,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (25,'Polski  Komitet Normalizacyjny',101,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (26,'Polski  Komitet Normalizacyjny',102,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (27,'Polski  Komitet Normalizacyjny',105,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (28,'Polski  Komitet Normalizacyjny',107,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (29,'Polski  Komitet Normalizacyjny',108,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (30,'Polski  Komitet Normalizacyjny',109,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (33,'Polski  Komitet Normalizacyjny',118,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (34,'Polski  Komitet Normalizacyjny',119,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (35,'Polski  Komitet Normalizacyjny',120,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (36,'Polski  Komitet Normalizacyjny',121,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (37,'Polski  Komitet Normalizacyjny',122,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (38,'Polski  Komitet Normalizacyjny',123,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (39,'Polski  Komitet Normalizacyjny',124,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (40,'Polski  Komitet Normalizacyjny',125,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (41,'Polski  Komitet Normalizacyjny',126,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (42,'Polski  Komitet Normalizacyjny',127,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (43,'Polski  Komitet Normalizacyjny',128,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (44,'Polski  Komitet Normalizacyjny',129,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (45,'Polski  Komitet Normalizacyjny',130,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (46,'Polski  Komitet Normalizacyjny',131,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (47,'Polski  Komitet Normalizacyjny',132,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (48,'Polski  Komitet Normalizacyjny',133,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (49,'Polski  Komitet Normalizacyjny',134,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (50,'Polski  Komitet Normalizacyjny',135,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (51,'Polski  Komitet Normalizacyjny',136,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (52,'Polski  Komitet Normalizacyjny',137,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (53,'Polski  Komitet Normalizacyjny',139,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (54,'Polski  Komitet Normalizacyjny',140,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (55,'Polski  Komitet Normalizacyjny',141,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (56,'Polski  Komitet Normalizacyjny',142,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (57,'Polski  Komitet Normalizacyjny',143,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (58,'Polski  Komitet Normalizacyjny',144,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (59,'Polski  Komitet Normalizacyjny',145,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (60,'Polski  Komitet Normalizacyjny',146,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (61,'Polski  Komitet Normalizacyjny',147,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (62,'Polski  Komitet Normalizacyjny',149,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (63,'Polski  Komitet Normalizacyjny',151,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (64,'Polski  Komitet Normalizacyjny',152,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (65,'Polski  Komitet Normalizacyjny',154,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (66,'Polski  Komitet Normalizacyjny',155,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (67,'Polski  Komitet Normalizacyjny',156,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (68,'Polski  Komitet Normalizacyjny',157,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (69,'Polski  Komitet Normalizacyjny',158,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (70,'Polski  Komitet Normalizacyjny',160,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (71,'Polski  Komitet Normalizacyjny',161,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (72,'Polski  Komitet Normalizacyjny',162,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (73,'Polski  Komitet Normalizacyjny',163,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (74,'Polski  Komitet Normalizacyjny',164,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (75,'Polski  Komitet Normalizacyjny',165,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (76,'Polski  Komitet Normalizacyjny',166,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (77,'Polski  Komitet Normalizacyjny',167,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (78,'Polski  Komitet Normalizacyjny',168,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (79,'Polski  Komitet Normalizacyjny',169,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (80,'Polski  Komitet Normalizacyjny',170,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (81,'Polski  Komitet Normalizacyjny',171,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (82,'Polski  Komitet Normalizacyjny',172,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (83,'Polski  Komitet Normalizacyjny',173,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (84,'Polski  Komitet Normalizacyjny',174,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (85,'Polski  Komitet Normalizacyjny',175,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (86,'Polski  Komitet Normalizacyjny',176,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (87,'Polski  Komitet Normalizacyjny',177,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (88,'Polski  Komitet Normalizacyjny',178,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (89,'Polski  Komitet Normalizacyjny',179,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (90,'Polski  Komitet Normalizacyjny',182,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (91,'Polski  Komitet Normalizacyjny',183,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (92,'Polski  Komitet Normalizacyjny',184,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (93,'Polski  Komitet Normalizacyjny',185,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (94,'Polski  Komitet Normalizacyjny',186,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (95,'Polski  Komitet Normalizacyjny',187,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (96,'Polski  Komitet Normalizacyjny',188,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (97,'Polski  Komitet Normalizacyjny',189,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (98,'Polski  Komitet Normalizacyjny',192,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (99,'Polski  Komitet Normalizacyjny',195,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (100,'Polski  Komitet Normalizacyjny',196,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (101,'Polski  Komitet Normalizacyjny',197,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (102,'Polski  Komitet Normalizacyjny',198,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (103,'Polski  Komitet Normalizacyjny',199,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (104,'Polski  Komitet Normalizacyjny',200,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (105,'Polski  Komitet Normalizacyjny',201,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (106,'Polski  Komitet Normalizacyjny',202,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (107,'Polski  Komitet Normalizacyjny',203,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (108,'Polski  Komitet Normalizacyjny',204,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (109,'Polski  Komitet Normalizacyjny',205,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (110,'Polski  Komitet Normalizacyjny',206,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (111,'Polski  Komitet Normalizacyjny',207,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (112,'Polski  Komitet Normalizacyjny',208,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (113,'Polski  Komitet Normalizacyjny',209,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (114,'Polski  Komitet Normalizacyjny',210,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (115,'Polski  Komitet Normalizacyjny',211,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (116,'Polski  Komitet Normalizacyjny',212,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (117,'Polski  Komitet Normalizacyjny',213,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (118,'Polski  Komitet Normalizacyjny',214,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (119,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',216,4,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (120,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',217,4,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (121,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',218,4,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (122,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',219,4,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (123,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',220,4,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (124,'Polski  Komitet Normalizacyjny',221,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (125,'Polski  Komitet Normalizacyjny',222,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (126,'Polski  Komitet Normalizacyjny',223,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (127,'Polski  Komitet Normalizacyjny',225,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (128,'Polski  Komitet Normalizacyjny',226,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (129,'Polski  Komitet Normalizacyjny',227,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (130,'Polski  Komitet Normalizacyjny',228,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (131,'Polski  Komitet Normalizacyjny',229,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (132,'Polski  Komitet Normalizacyjny',230,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (133,'Polski  Komitet Normalizacyjny',231,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (134,'Polski  Komitet Normalizacyjny',232,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (135,'Polski  Komitet Normalizacyjny',233,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (136,'Polski  Komitet Normalizacyjny',234,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (137,'Polski  Komitet Normalizacyjny',235,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (138,'Polski  Komitet Normalizacyjny',236,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (139,'Polski  Komitet Normalizacyjny',237,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (140,'Polski  Komitet Normalizacyjny',238,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (141,'Polski  Komitet Normalizacyjny',239,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (142,'Polski  Komitet Normalizacyjny',240,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (143,'Polski  Komitet Normalizacyjny',241,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (144,'Polski  Komitet Normalizacyjny',242,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (145,'Polski  Komitet Normalizacyjny',243,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (146,'Polski  Komitet Normalizacyjny',244,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (147,'Polski  Komitet Normalizacyjny',245,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (148,'Polski  Komitet Normalizacyjny',246,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (149,'Polski  Komitet Normalizacyjny',247,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (150,'Polski  Komitet Normalizacyjny',248,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (151,'Polski  Komitet Normalizacyjny',249,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (152,'Polski  Komitet Normalizacyjny',250,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (153,'Polski  Komitet Normalizacyjny',251,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (154,'Polski  Komitet Normalizacyjny',252,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (155,'Polski  Komitet Normalizacyjny',253,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (156,'Polski  Komitet Normalizacyjny',254,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (157,'Polski  Komitet Normalizacyjny',255,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (158,'Polski  Komitet Normalizacyjny',256,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (159,'Polski  Komitet Normalizacyjny',258,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (160,'Polski  Komitet Normalizacyjny',259,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (161,'Polski  Komitet Normalizacyjny',260,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (162,'Polski  Komitet Normalizacyjny',261,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (163,'Polski  Komitet Normalizacyjny',262,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (164,'Polski  Komitet Normalizacyjny',263,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (165,'Polski  Komitet Normalizacyjny',264,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (166,'Polski  Komitet Normalizacyjny',265,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (167,'Polski  Komitet Normalizacyjny',266,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (168,'Polski  Komitet Normalizacyjny',267,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (169,'Polski  Komitet Normalizacyjny',268,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (170,'Polski  Komitet Normalizacyjny',269,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (171,'Polski  Komitet Normalizacyjny',270,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (172,'Polski  Komitet Normalizacyjny',271,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (173,'Polski  Komitet Normalizacyjny',273,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (174,'Polski  Komitet Normalizacyjny',274,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (175,'Polski  Komitet Normalizacyjny',275,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (176,'Polski  Komitet Normalizacyjny',276,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (177,'Polski  Komitet Normalizacyjny',277,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (178,'Polski  Komitet Normalizacyjny',278,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (179,'Polski  Komitet Normalizacyjny',279,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (180,'Polski  Komitet Normalizacyjny',280,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (181,'Polski  Komitet Normalizacyjny',281,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (182,'Polski  Komitet Normalizacyjny',282,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (183,'Polski  Komitet Normalizacyjny',283,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (184,'Polski  Komitet Normalizacyjny',285,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (185,'Polski  Komitet Normalizacyjny',286,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (186,'Polski  Komitet Normalizacyjny',287,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (187,'Polski  Komitet Normalizacyjny',288,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (188,'Polski  Komitet Normalizacyjny',289,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (189,'Polski  Komitet Normalizacyjny',290,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (190,'Polski  Komitet Normalizacyjny',291,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (191,'Polski  Komitet Normalizacyjny',292,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (192,'Polski  Komitet Normalizacyjny',294,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (193,'Polski  Komitet Normalizacyjny',295,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (194,'Polski  Komitet Normalizacyjny',296,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (195,'Polski  Komitet Normalizacyjny',297,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (196,'Polski  Komitet Normalizacyjny',298,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (197,'Polski  Komitet Normalizacyjny',299,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (198,'Polski  Komitet Normalizacyjny',300,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (199,'Polski  Komitet Normalizacyjny',301,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (200,'Polski  Komitet Normalizacyjny',303,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (201,'Polski  Komitet Normalizacyjny',304,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (202,'Polski  Komitet Normalizacyjny',306,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (203,'Polski  Komitet Normalizacyjny',307,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (204,'Polski  Komitet Normalizacyjny',308,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (205,'Polski  Komitet Normalizacyjny',309,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (206,'Polski  Komitet Normalizacyjny',310,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (207,'Polski  Komitet Normalizacyjny',311,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (208,'Polski  Komitet Normalizacyjny',312,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (209,'Polski  Komitet Normalizacyjny',314,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (210,'Polski  Komitet Normalizacyjny',315,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (211,'Polski  Komitet Normalizacyjny',316,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (212,'Polski  Komitet Normalizacyjny',317,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (213,'Polski  Komitet Normalizacyjny',318,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (214,'Polski  Komitet Normalizacyjny',319,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (215,'Polski  Komitet Normalizacyjny',320,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (216,'Polski  Komitet Normalizacyjny',321,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (217,'Polski  Komitet Normalizacyjny',322,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (218,'Polski  Komitet Normalizacyjny',324,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (219,'Polski  Komitet Normalizacyjny',325,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (220,'Polski  Komitet Normalizacyjny',326,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (221,'Polski  Komitet Normalizacyjny',327,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (222,'Polski  Komitet Normalizacyjny',328,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (223,'Polski  Komitet Normalizacyjny',329,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (224,'Polski  Komitet Normalizacyjny',330,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (225,'Polski  Komitet Normalizacyjny',331,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (226,'Polski  Komitet Normalizacyjny',332,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (227,'Polski  Komitet Normalizacyjny',333,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (228,'Polski  Komitet Normalizacyjny',334,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (229,'Polski  Komitet Normalizacyjny',335,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (230,'Polski  Komitet Normalizacyjny',336,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (231,'Polski  Komitet Normalizacyjny',338,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (232,'Polski  Komitet Normalizacyjny',339,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (233,'Polski  Komitet Normalizacyjny',340,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (234,'Polski  Komitet Normalizacyjny',342,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (235,'Polski  Komitet Normalizacyjny',343,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (236,'Polski  Komitet Normalizacyjny',344,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (237,'Polski  Komitet Normalizacyjny',345,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (238,'Polski  Komitet Normalizacyjny',346,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (239,'Polski  Komitet Normalizacyjny',347,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (240,'Polski  Komitet Normalizacyjny',349,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (241,'Polski  Komitet Normalizacyjny',350,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (242,'Polski  Komitet Normalizacyjny',351,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (243,'Polski  Komitet Normalizacyjny',352,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (244,'Polski  Komitet Normalizacyjny',353,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (245,'Polski  Komitet Normalizacyjny',354,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (246,'Polski  Komitet Normalizacyjny',355,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (247,'Polski  Komitet Normalizacyjny',356,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (248,'Polski  Komitet Normalizacyjny',357,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (249,'Polski  Komitet Normalizacyjny',358,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (250,'Polski  Komitet Normalizacyjny',359,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (251,'Polski  Komitet Normalizacyjny',361,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (252,'Polski  Komitet Normalizacyjny',362,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (253,'Polski  Komitet Normalizacyjny',363,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (254,'Polski  Komitet Normalizacyjny',364,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (255,'Polski  Komitet Normalizacyjny',365,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (256,'Polski  Komitet Normalizacyjny',366,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (257,'Polski  Komitet Normalizacyjny',367,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (258,'Polski  Komitet Normalizacyjny',368,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (259,'Polski  Komitet Normalizacyjny',369,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (260,'Polski  Komitet Normalizacyjny',370,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (261,'Polski  Komitet Normalizacyjny',371,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (262,'Polski  Komitet Normalizacyjny',372,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (263,'Polski  Komitet Normalizacyjny',373,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (264,'Polski  Komitet Normalizacyjny',374,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (265,'Polski  Komitet Normalizacyjny',375,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (266,'Polski  Komitet Normalizacyjny',376,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (267,'Polski  Komitet Normalizacyjny',377,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (268,'Polski  Komitet Normalizacyjny',378,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (269,'Polski  Komitet Normalizacyjny',380,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (270,'Polski  Komitet Normalizacyjny',381,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (271,'Polski  Komitet Normalizacyjny',382,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (272,'Polski  Komitet Normalizacyjny',383,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (273,'Polski  Komitet Normalizacyjny',385,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (274,'Polski  Komitet Normalizacyjny',386,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (275,'Polski  Komitet Normalizacyjny',387,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (276,'Polski  Komitet Normalizacyjny',388,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (277,'Polski  Komitet Normalizacyjny',389,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (278,'Polski  Komitet Normalizacyjny',390,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (279,'Polski  Komitet Normalizacyjny',391,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (280,'Polski  Komitet Normalizacyjny',392,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (281,'Polski  Komitet Normalizacyjny',393,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (282,'Polski  Komitet Normalizacyjny',394,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (283,'Polski  Komitet Normalizacyjny',395,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (284,'Polski  Komitet Normalizacyjny',396,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (285,'Polski  Komitet Normalizacyjny',397,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (286,'Polski  Komitet Normalizacyjny',398,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (287,'Polski  Komitet Normalizacyjny',399,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (288,'Polski  Komitet Normalizacyjny',400,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (289,'Polski  Komitet Normalizacyjny',401,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (290,'Polski  Komitet Normalizacyjny',402,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (291,'Polski  Komitet Normalizacyjny',403,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (292,'Polski  Komitet Normalizacyjny',405,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (293,'Polski  Komitet Normalizacyjny',406,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (294,'Polski  Komitet Normalizacyjny',407,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (295,'Polski  Komitet Normalizacyjny',408,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (296,'Polski  Komitet Normalizacyjny',409,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (297,'Polski  Komitet Normalizacyjny',410,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (298,'Polski  Komitet Normalizacyjny',412,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (299,'Polski  Komitet Normalizacyjny',413,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (300,'Polski  Komitet Normalizacyjny',414,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (301,'Polski  Komitet Normalizacyjny',416,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (302,'Polski  Komitet Normalizacyjny',417,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (303,'Polski  Komitet Normalizacyjny',418,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (304,'Polski  Komitet Normalizacyjny',419,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (305,'Polski  Komitet Normalizacyjny',421,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (306,'Polski  Komitet Normalizacyjny',422,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (307,'Polski  Komitet Normalizacyjny',423,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (308,'Polski  Komitet Normalizacyjny',424,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (309,'Polski  Komitet Normalizacyjny',425,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (310,'Polski  Komitet Normalizacyjny',426,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (311,'Polski  Komitet Normalizacyjny',427,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (312,'Polski  Komitet Normalizacyjny',428,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (313,'Polski  Komitet Normalizacyjny',429,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (314,'Polski  Komitet Normalizacyjny',430,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (315,'Polski  Komitet Normalizacyjny',431,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (316,'Polski  Komitet Normalizacyjny',433,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (317,'Polski  Komitet Normalizacyjny',435,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (318,'Polski  Komitet Normalizacyjny',436,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (319,'Polski  Komitet Normalizacyjny',437,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (320,'Polski  Komitet Normalizacyjny',438,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (321,'Polski  Komitet Normalizacyjny',439,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (322,'Polski  Komitet Normalizacyjny',440,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (323,'Polski  Komitet Normalizacyjny',442,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (324,'Polski  Komitet Normalizacyjny',443,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (325,'Polski  Komitet Normalizacyjny',444,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (326,'Polski  Komitet Normalizacyjny',445,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (327,'Polski  Komitet Normalizacyjny',446,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (328,'Polski  Komitet Normalizacyjny',447,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (329,'Polski  Komitet Normalizacyjny',448,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (330,'Polski  Komitet Normalizacyjny',449,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (331,'Polski  Komitet Normalizacyjny',450,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (332,'Polski  Komitet Normalizacyjny',451,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (333,'Polski  Komitet Normalizacyjny',452,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (334,'Polski  Komitet Normalizacyjny',453,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Miejsce,Nazwa,Akronim,Nor_nor_id,Wyd_mwyd_id,Wyd_rodz_id,Wyd_wyd_id) values  (335,'Warszawa','Zak³ad systemów jakoœci i zarz¹dzania','ZSJiZ',455,34,4,14)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (336,'Zak³ad systemów jakoœci i zarz¹dzania','ZSJiZ',456,4,14)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (337,'Zak³ad systemów jakoœci i zarz¹dzania','ZSJiZ',457,5,14)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (338,'Polski  Komitet Normalizacyjny',458,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (339,'Polski  Komitet Normalizacyjny',459,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (340,'Polski  Komitet Normalizacyjny',460,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (341,'Polski  Komitet Normalizacyjny',461,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (342,'Polski  Komitet Normalizacyjny',462,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (343,'Polski  Komitet Normalizacyjny',463,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (344,'Polski  Komitet Normalizacyjny',464,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (345,'Polski  Komitet Normalizacyjny',465,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (346,'Polski  Komitet Normalizacyjny',466,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (347,'Polski  Komitet Normalizacyjny',467,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (348,'Polski  Komitet Normalizacyjny',468,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (349,'Polski  Komitet Normalizacyjny',469,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (350,'Polski  Komitet Normalizacyjny',470,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (351,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',471,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (352,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',472,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (353,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',473,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (354,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',474,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (355,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',475,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (356,'Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci',476,5,12)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (357,'Polski  Komitet Normalizacyjny',477,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (358,'Polski  Komitet Normalizacyjny',478,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (359,'Polski  Komitet Normalizacyjny',479,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (360,'Polski  Komitet Normalizacyjny',480,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (361,'Zak³ad systemów jakoœci i zarz¹dzania',481,4,14)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (362,'Polski  Komitet Normalizacyjny',482,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (363,'Polski  Komitet Normalizacyjny',483,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (364,'Polski  Komitet Normalizacyjny',484,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (365,'Polski  Komitet Normalizacyjny',486,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (366,'Polski  Komitet Normalizacyjny',487,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (367,'Polski  Komitet Normalizacyjny',488,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (368,'Polski  Komitet Normalizacyjny',489,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (369,'Polski  Komitet Normalizacyjny',490,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (370,'Polski  Komitet Normalizacyjny',491,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (371,'Polski  Komitet Normalizacyjny',492,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (372,'Polski  Komitet Normalizacyjny',493,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (373,'Polski  Komitet Normalizacyjny',494,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (374,'Polski  Komitet Normalizacyjny',495,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (375,'Polski  Komitet Normalizacyjny',496,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (376,'Polski  Komitet Normalizacyjny',497,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (377,'Polski  Komitet Normalizacyjny',498,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (378,'Polski  Komitet Normalizacyjny',499,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (379,'Polski  Komitet Normalizacyjny',501,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (380,'Polski  Komitet Normalizacyjny',502,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (381,'Polski  Komitet Normalizacyjny',503,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (382,'Polski  Komitet Normalizacyjny',504,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (383,'Polski  Komitet Normalizacyjny',505,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (384,'Polski  Komitet Normalizacyjny',506,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (385,'Polski  Komitet Normalizacyjny',507,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (386,'Polski  Komitet Normalizacyjny',508,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (387,'Polski  Komitet Normalizacyjny',509,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (388,'Polski  Komitet Normalizacyjny',510,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (389,'Polski  Komitet Normalizacyjny',511,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (390,'Polski  Komitet Normalizacyjny',512,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (391,'Polski  Komitet Normalizacyjny',513,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (392,'Polski  Komitet Normalizacyjny',514,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (393,'Polski  Komitet Normalizacyjny',515,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (394,'Polski  Komitet Normalizacyjny',516,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (395,'Polski  Komitet Normalizacyjny',517,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (396,'Polski  Komitet Normalizacyjny',518,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (397,'Polski  Komitet Normalizacyjny',519,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (398,'Polski  Komitet Normalizacyjny',520,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (399,'Polski  Komitet Normalizacyjny',521,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (400,'Polski  Komitet Normalizacyjny',522,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (401,'Polski  Komitet Normalizacyjny',523,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (402,'Polski  Komitet Normalizacyjny',524,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (403,'Polski  Komitet Normalizacyjny',526,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (404,'Polski  Komitet Normalizacyjny',528,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (405,'Polski  Komitet Normalizacyjny',529,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (406,'Polski  Komitet Normalizacyjny',530,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (407,'Polski  Komitet Normalizacyjny',531,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (408,'Polski  Komitet Normalizacyjny',532,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (409,'Polski  Komitet Normalizacyjny',533,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (410,'Polski  Komitet Normalizacyjny',534,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (411,'Polski  Komitet Normalizacyjny',535,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (412,'Polski  Komitet Normalizacyjny',536,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (413,'Polski  Komitet Normalizacyjny',537,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (414,'Polski  Komitet Normalizacyjny',538,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (415,'Polski  Komitet Normalizacyjny',539,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (416,'Polski  Komitet Normalizacyjny',540,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (417,'Polski  Komitet Normalizacyjny',541,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (418,'Polski  Komitet Normalizacyjny',542,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (419,'Polski  Komitet Normalizacyjny',543,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (420,'Polski  Komitet Normalizacyjny',544,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (421,'Polski  Komitet Normalizacyjny',545,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (422,'Polski  Komitet Normalizacyjny',546,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (423,'Polski  Komitet Normalizacyjny',547,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (424,'Polski  Komitet Normalizacyjny',548,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (425,'Polski  Komitet Normalizacyjny',549,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (426,'Polski  Komitet Normalizacyjny',550,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (427,'Polski  Komitet Normalizacyjny',551,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (428,'Polski  Komitet Normalizacyjny',552,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (429,'Polski  Komitet Normalizacyjny',553,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (430,'Polski  Komitet Normalizacyjny',554,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (431,'Polski  Komitet Normalizacyjny',555,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (432,'Polski  Komitet Normalizacyjny',556,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (433,'Polski  Komitet Normalizacyjny',557,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (434,'Polski  Komitet Normalizacyjny',558,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (435,'Polski  Komitet Normalizacyjny',559,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (436,'Polski  Komitet Normalizacyjny',560,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (437,'Polski  Komitet Normalizacyjny',561,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (438,'Polski  Komitet Normalizacyjny',562,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (439,'Polski  Komitet Normalizacyjny',563,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (440,'Polski  Komitet Normalizacyjny',564,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (441,'Polski  Komitet Normalizacyjny',565,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (442,'Polski  Komitet Normalizacyjny',566,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (443,'Polski  Komitet Normalizacyjny',567,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (444,'Polski  Komitet Normalizacyjny',568,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (445,'Polski  Komitet Normalizacyjny',569,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (446,'Polski  Komitet Normalizacyjny',570,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (447,'Polski  Komitet Normalizacyjny',571,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (448,'Polski  Komitet Normalizacyjny',572,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (449,'Polski  Komitet Normalizacyjny',573,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (450,'Polski  Komitet Normalizacyjny',574,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (451,'Polski  Komitet Normalizacyjny',575,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (452,'Polski  Komitet Normalizacyjny',576,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (453,'Polski  Komitet Normalizacyjny',577,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (454,'Polski  Komitet Normalizacyjny',578,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (455,'Polski  Komitet Normalizacyjny',579,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (456,'Polski  Komitet Normalizacyjny',580,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (457,'Polski  Komitet Normalizacyjny',581,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (458,'Polski  Komitet Normalizacyjny',582,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (459,'Polski  Komitet Normalizacyjny',583,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (460,'Polski  Komitet Normalizacyjny',584,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (461,'Polski  Komitet Normalizacyjny',585,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (462,'Polski  Komitet Normalizacyjny',586,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (463,'Polski  Komitet Normalizacyjny',587,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (464,'Polski  Komitet Normalizacyjny',588,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (465,'Polski  Komitet Normalizacyjny',589,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (466,'Polski  Komitet Normalizacyjny',591,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (467,'Polski  Komitet Normalizacyjny',592,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (468,'Polski  Komitet Normalizacyjny',593,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (469,'Polski  Komitet Normalizacyjny',594,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (470,'Polski  Komitet Normalizacyjny',595,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (471,'Polski  Komitet Normalizacyjny',596,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (472,'Polski  Komitet Normalizacyjny',597,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (473,'Polski  Komitet Normalizacyjny',598,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (474,'Polski  Komitet Normalizacyjny',599,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (475,'Polski  Komitet Normalizacyjny',600,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (476,'Polski  Komitet Normalizacyjny',601,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (477,'Polski  Komitet Normalizacyjny',602,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (478,'Polski  Komitet Normalizacyjny',603,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (479,'Polski  Komitet Normalizacyjny',605,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (480,'Polski  Komitet Normalizacyjny',606,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (481,'Polski  Komitet Normalizacyjny',608,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (482,'Polski  Komitet Normalizacyjny',609,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (483,'Polski  Komitet Normalizacyjny',610,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (484,'Polski  Komitet Normalizacyjny',612,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (485,'Polski  Komitet Normalizacyjny',613,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (486,'Polski  Komitet Normalizacyjny',614,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (487,'Polski  Komitet Normalizacyjny',616,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (488,'Polski  Komitet Normalizacyjny',617,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (489,'Polski  Komitet Normalizacyjny',618,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (490,'Polski  Komitet Normalizacyjny',619,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (491,'Polski  Komitet Normalizacyjny',620,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (492,'Polski  Komitet Normalizacyjny',621,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (493,'Polski  Komitet Normalizacyjny',622,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (494,'Polski  Komitet Normalizacyjny',624,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (495,'Polski  Komitet Normalizacyjny',625,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (496,'Polski  Komitet Normalizacyjny',627,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (497,'Ministerstwo Obrony Narodowej','MON',628,5,16)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (498,'Ministerstwo Obrony Narodowej','MON',629,5,16)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (499,'Ministerstwo Obrony Narodowej','MON',630,5,16)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Akronim,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (500,'Ministerstwo Obrony Narodowej','MON',631,5,16)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (501,'Polski  Komitet Normalizacyjny',632,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (502,'Polski  Komitet Normalizacyjny',634,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (503,'Polski  Komitet Normalizacyjny',635,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (504,'Polski  Komitet Normalizacyjny',636,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (505,'Polski  Komitet Normalizacyjny',637,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (506,'Polski  Komitet Normalizacyjny',638,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (507,'Polski  Komitet Normalizacyjny',639,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (508,'Polski  Komitet Normalizacyjny',640,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (509,'Polski  Komitet Normalizacyjny',641,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (510,'Polski  Komitet Normalizacyjny',642,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (511,'IPC',643,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (512,'IPC',644,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (513,'IPC',645,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (514,'IPC',646,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (515,'IPC',647,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (516,'IPC',649,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (517,'IPC',650,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (518,'IPC',651,4,17)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (519,'Polski  Komitet Normalizacyjny',652,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (520,'Polski  Komitet Normalizacyjny',653,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (521,'Polski  Komitet Normalizacyjny',654,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (522,'Polski  Komitet Normalizacyjny',655,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (523,'Polski  Komitet Normalizacyjny',656,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (524,'Polski  Komitet Normalizacyjny',657,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (525,'Polski  Komitet Normalizacyjny',658,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (526,'Polski  Komitet Normalizacyjny',659,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (527,'Polski  Komitet Normalizacyjny',660,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (528,'Polski  Komitet Normalizacyjny',661,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (529,'Polski  Komitet Normalizacyjny',662,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (530,'Polski  Komitet Normalizacyjny',663,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (531,'Polski  Komitet Normalizacyjny',664,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (532,'Polski  Komitet Normalizacyjny',665,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (533,'Polski  Komitet Normalizacyjny',666,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (534,'Polski  Komitet Normalizacyjny',667,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (535,'Polski  Komitet Normalizacyjny',668,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (536,'Polski  Komitet Normalizacyjny',669,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (537,'Polski  Komitet Normalizacyjny',670,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (538,'Polski  Komitet Normalizacyjny',671,5,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (539,'Polski  Komitet Normalizacyjny',673,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (540,'Polski  Komitet Normalizacyjny',674,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (541,'Polski  Komitet Normalizacyjny',675,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (542,'Polski  Komitet Normalizacyjny',676,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (543,'Polski  Komitet Normalizacyjny',677,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (544,'Polski  Komitet Normalizacyjny',678,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (545,'Polski  Komitet Normalizacyjny',681,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (546,'Polski  Komitet Normalizacyjny',682,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (547,'Polski  Komitet Normalizacyjny',683,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (548,'Polski  Komitet Normalizacyjny',684,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (549,'Polski  Komitet Normalizacyjny',685,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (550,'Polski  Komitet Normalizacyjny',686,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (551,'Polski  Komitet Normalizacyjny',687,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (552,'Polski  Komitet Normalizacyjny',688,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (553,'Polski  Komitet Normalizacyjny',689,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (554,'Polski  Komitet Normalizacyjny',690,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (555,'Polski  Komitet Normalizacyjny',691,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (556,'Polski  Komitet Normalizacyjny',692,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (557,'Polski  Komitet Normalizacyjny',693,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (558,'Polski  Komitet Normalizacyjny',694,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (559,'Polski  Komitet Normalizacyjny',695,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (560,'Polski  Komitet Normalizacyjny',696,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (561,'Polski  Komitet Normalizacyjny',697,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (562,'Polski  Komitet Normalizacyjny',698,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (563,'Polski  Komitet Normalizacyjny',699,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (564,'Polski  Komitet Normalizacyjny',700,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (565,'Polski  Komitet Normalizacyjny',701,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (566,'Polski  Komitet Normalizacyjny',702,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (567,'Polski  Komitet Normalizacyjny',703,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (568,'Polski  Komitet Normalizacyjny',704,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (569,'Polski  Komitet Normalizacyjny',705,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (570,'Polski  Komitet Normalizacyjny',706,4,11)
GO
insert into Normy_wydawca (Id_nor_wyd,Nazwa,Nor_nor_id,Wyd_rodz_id,Wyd_wyd_id) values  (571,'Polski  Komitet Normalizacyjny',707,4,11)
GO
