set identity_insert normy on
insert into Normy (Id_norma,Dlugosc,Isbn,Klucze,Nor_rodz_id,Tytul,Wydawcy,Wysokosc,Data_ust,Nr_normy) values  (74,21,'83-7330-626-9','S³owo kluczowe',1,'Konstrukcje drewniane. Obliczenia statyczne i projektowanie.','Warszawa:Polski Komitet Normalizacyjny',30,'2000.08.11','PN-B-03150:2000')
GO
insert into Normy (Id_norma,Klucze,Nor_rodz_id,Tytul,Uwagi,Wydawcy,Nr_normy) values  (78,'Aluminium; Odlewy',1,'Odlewy ze stopów aluminium. Ocena porowatoœci metod¹ wizualn¹','{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fnil MS Sans Serif;}{\f1\froman\fcharset2 Symbol;}{\f2\fswiss\fcharset238 MS Sans Serif;}{\f3\fswiss Arial;}}
{\colortbl\red0\green0\blue0;}
\deflang1033\pard\qc\plain\f3\fs18 Norma unikatowa
\par }
','Warszawa:Polski Komitet Normalizacyjny','PN-ISO 10049:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (79,'1:Inwentarz ogólny',1,'Budowle magazynowe.Podzia³, nazwy i okreœlenia.','Warszawa:Polski Komitet Normalizacyjny','PN-81/B-01012')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (80,'1:Inwentarz ogólny',1,'Rysunek budowlany.Oznaczenia graficzne na rysunkach architektoniczno-budowlanych.','Warszawa:Polski Komitet Normalizacyjny','Rysunek budowlany.Oznaczenia graficzne na rysunkach architektoniczno-budowlanych. \ PN-70/B-01025','PN-B-01025:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (81,'1:Inwentarz ogólny',1,'Projekty budowlane.Oznaczenia na opracowaniach graficznych zagospodarowania placów budowy.','Warszawa:Polski Komitet Normalizacyjny','PN-62/B-01034')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (82,'1:Inwentarz ogólny',1,'Kruszywa sztuczne. Podzia³, nazwy i okreœlenia.','Warszawa:Polski Komitet Normalizacyjny','PN-78/B-01101')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (84,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Centralne ogrzewanie. Oznaczenia na rysunkach.','Warszawa:Polski  Komitet Normalizacyjny','Centralne ogrzewanie. Oznaczenia na rysunkach. \ PN-66/B-01400','PN-84/B-01400')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (88,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Centralne ogrzewanie.Grzejniki.Nazwy i okreœlenia.','Polski  Komitet Normalizacyjny','Centralne ogrzewanie.Grzejniki.Nazwy i okreœlenia. \ PN-63/B-01405','PN-74/B-01405')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (89,'1:Inwentarz ogólny',1,'Wentylacja i klimatyzacja.Rysunek techniczny.zasady wykonywania i oznaczenia.','Polski  Komitet Normalizacyjny','Wentylacja i klimatyzacja.Rysunek techniczny.zasady wykonywania i oznaczenia. \ PN-60/B-01410,; Wentylacja i klimatyzacja.Rysunek techniczny.zasady wykonywania i oznaczenia. \ PN-84/B-01412','PN-89/B-01410')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (90,'1:Inwentarz ogólny',1,'Ciep³ownictwo.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia na mapach i planach.','Polski  Komitet Normalizacyjny','Ciep³ownictwo.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia na mapach i planach. \ PN-64/B-01420','PN-75/B-01420')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (91,'1:Inwentarz ogólny',1,'Ogrzewnictwo.Instalacje centralnego ogrzewania.Terminologia.','Polski  Komitet Normalizacyjny','Ogrzewnictwo.Instalacje centralnego ogrzewania.Terminologia. \ PN-72/B-01430','PN-90/B-01430')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (92,'1:Inwentarz ogólny',1,'Wodoci¹gi i kanalizacja.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia graficzne.','Polski  Komitet Normalizacyjny','Wodoci¹gi i kanalizacja.Urz¹dzenia i sieæ zewnêtrzna.Oznaczenia graficzne. \ PN-85/B-01700','PN-B-01700:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (93,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Oznaczenia na rysunkach.','Polski  Komitet Normalizacyjny','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Oznaczenia na rysunkach. \ PN-66/B-01701','PN-84/B-01701')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (94,'1:Inwentarz ogólny',1,'Instalacje wodoci¹gowe.Wymagania w projektowaniu.','Polski  Komitet Normalizacyjny','PN-92/B-01706')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (95,'1:Inwentarz ogólny',1,'Instalacje kanalizacyjne.Wymagania w projektowaniu','Polski  Komitet Normalizacyjny','PN-92/B-01707')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (96,'1:Inwentarz ogólny',1,'Obci¹¿enia budowli.Obci¹¿enia suwnicami pomostowymi,wci¹garkami.','Polski  Komitet Normalizacyjny','Obci¹¿enia budowli.Obci¹¿enia suwnicami pomostowymi,wci¹garkami. \ PN-64/B-02012; Obci¹¿enia budowli.Obci¹¿enia suwnicami pomostowymi,wci¹garkami. \ PN-72/B-02013','PN-86/B-02005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (97,'1:Inwentarz ogólny',1,'Obci¹¿enia w obliczeniach statycznych.Obci¹¿enia sta³e i zmienne.','Polski  Komitet Normalizacyjny','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enia sta³e i zmienne. \ PN-64/B-02009','PN-74/B-02009')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (98,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie œniegiem.','Polski  Komitet Normalizacyjny','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie œniegiem. \ PN-70/B-02010','PN-80/B-02010')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (99,'1:Inwentarz ogólny',1,'Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie wiatrem.','Polski  Komitet Normalizacyjny','Obci¹¿enia w obliczeniach statycznych.Obci¹¿enie wiatrem. \ PN-70/B-02011','PN-77/B-02011')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (100,'1:Inwentarz ogólny',1,'Obci¹¿enia budowli.Obci¹¿enia zmienne œrodowiskowe.Obci¹¿enia oblodzeniem.','Polski  Komitet Normalizacyjny','PN-87/B-02013')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (101,'1:Inwentarz ogólny',1,'Akustyka budowlana.Ochrona przed ha³asem pomieszczeñ w budynkach.','Polski  Komitet Normalizacyjny','Akustyka budowlana.Ochrona przed ha³asem pomieszczeñ w budynkach. \ PN-79/B-02151','PN-87/B-02151/01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (102,'1:Inwentarz ogólny2:Inwentarz ogólny4:Inwentarz ogólny',1,'Akustyka budowlana.Dopuszczalne wartoœci poziomu d¿wiêku w pomieszczeniach.','Polski  Komitet Normalizacyjny','Akustyka budowlana.Dopuszczalne wartoœci poziomu d¿wiêku w pomieszczeniach. \ PN-70/B-02151','PN-87/B-02151/02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (105,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'Akustyka budowlana.Ochrona przed ha³asem w budynkach- izolacyjnoœc akustyczna przegród w budynkach oraz izolacyjnoœæ akustyczna elementów budowlanych.Wymagania.','Polski  Komitet Normalizacyjny','Akustyka budowlana.Ochrona przed ha³asem w budynkach- izolacyjnoœc akustyczna przegród w budynkach oraz izolacyjnoœæ akustyczna elementów budowlanych.Wymagania. \ PN-87/B-02151/03','PN-B-02151-3:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (107,'1:Inwentarz ogólny',1,'Akustyka budowlana.Metody pomiaru poziomu d¿wiêku A w budynkach','Polski  Komitet Normalizacyjny','Akustyka budowlana.Metody pomiaru poziomu d¿wiêku A w budynkach \ PN-70/B-02156','PN-87/B-02156')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (108,'1:Inwentarz ogólny',1,'Koordynacja wymiarowa w budownictwie.Oznaczenia tolerancji wymiarów elementów i tolerancji po³o¿enia elementów na rysunku.','Polski  Komitet Normalizacyjny','PN-/B-02358 proj.')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Uwagi,Wydawcy,Nr_normy) values  (109,'1:Inwentarz ogólny',1,'egz,1 zagubiony.','Oœwietlenie wnêtrz œwiat³em dziennym.Warunki ogólne.','{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fnil MS Sans Serif;}{\f1\froman\fcharset2 Symbol;}{\f2\fswiss\fcharset238 MS Sans Serif;}{\f3\fswiss Arial;}}
{\colortbl\red0\green0\blue0;}
\deflang1033\pard\plain\f3\fs18 egz.1 zagubiony
\par }
','Polski  Komitet Normalizacyjny','PN-71/B-02380')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (118,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Systemy zarzadzania œrodowiskowego.Wymagania i wytyczne stosowania.','Polski  Komitet Normalizacyjny','Systemy zarzadzania œrodowiskowego.Wymagania i wytyczne stosowania. \ PN-EN 14001:2005(U)','PN-EN ISO 14001:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (119,'1:Inwentarz ogólny',1,'Oznaczenia wielkoœci i jednostek miar u¿ywanych w elektryce.Czêœæ 2:Telekomunikacja i elektronika.','Polski  Komitet Normalizacyjny','Oznaczenia wielkoœci i jednostek miar u¿ywanych w elektryce.Czêœæ 2:Telekomunikacja i elektronika. \ PN-89/E-01102','PN-HD 60027-2:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (120,'1:Inwentarz ogólny',1,'Stale.Okreœlanie g³êbokoœci odwêglania.','Polski  Komitet Normalizacyjny','Stale.Okreœlanie g³êbokoœci odwêglania. \ PN-EN ISO 3887:2003(','PN-EN ISO 3887:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (121,'1:Inwentarz ogólny',1,'Specyfikacje geometrii wyrobów (GPS).Szeregi k¹tów i pochyleñ pryzm.','Polski  Komitet Normalizacyjny','Specyfikacje geometrii wyrobów (GPS).Szeregi k¹tów i pochyleñ pryzm. \ PN-EN ISO 2538:2003(','PN-EN ISO 2538:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (122,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Ogrzewnictwo.Temperatury ogrzewanych pomieszczeñ w budynkach.','Polski  Komitet Normalizacyjny','Ogrzewnictwo.Temperatury ogrzewanych pomieszczeñ w budynkach. \ PN-74/B-02402','PN-82/B-02402')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (123,'1:Inwentarz ogólny',1,'Ogrzewnictwo.Temperatury obliczeniowe zewnêtrzne.','Polski  Komitet Normalizacyjny','Ogrzewnictwo.Temperatury obliczeniowe zewnêtrzne. \ PN-74/B-02403','PN-82/B-02403')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (124,'1:Inwentarz ogólny',1,'Ogrzewnictwo.Kot³ownie wbudowane  na paliwo sta³e.Wymagania.','Polski  Komitet Normalizacyjny','PN-87/B-02411')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (125,'1:Inwentarz ogólny',1,'Zabezpieczenie utz¹dzeñ wytwarzaj¹cych parê niskoprê¿n¹.Wymagania.','Polski  Komitet Normalizacyjny','Zabezpieczenie utz¹dzeñ wytwarzaj¹cych parê niskoprê¿n¹.Wymagania. \ PN-62/B-02412','PN-75/B-02412')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (126,'1:Inwentarz ogólny',1,'Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych systemu otwartego.Wymagania.','Polski  Komitet Normalizacyjny','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych systemu otwartego.Wymagania. \ PN-77/B-02413','PN-91/B-02413')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (127,'1:Inwentarz ogólny',1,'Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych...','Polski  Komitet Normalizacyjny','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie instalacji ogrzewañ wodnych... \ PN-91/B-02414','PN-B-02414:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (128,'1:Inwentarz ogólny',1,'Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie wodnych zamkniêtych systemów ciep³owniczych.Wymagania.','Polski  Komitet Normalizacyjny','Ogrzewnictwo i ciep³ownictwo.Zabezpieczenie wodnych zamkniêtych systemów ciep³owniczych.Wymagania. \ PN-70/B-02415','PN-91/B-02415')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (129,'1:Inwentarz ogólny',1,'Ogrzewnictwo i ciep³ownictwo.zabezpieczenie instalacji ogrzewañ wodnych systemu zamkniêtego przy³¹czonych do sieci.','Polski  Komitet Normalizacyjny','Ogrzewnictwo i ciep³ownictwo.zabezpieczenie instalacji ogrzewañ wodnych systemu zamkniêtego przy³¹czonych do sieci. \ PN-70/B-02416','PN-91/B-02416')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (130,'1:Inwentarz ogólny',1,'Ogrzewnictwo i  ciep³ownictwo.zabezpieczenie instalacji ogrzewañ wodnych i wodnych zamkniêtych systemów ciep³owniczych.','Polski  Komitet Normalizacyjny','PN-91/B-02419')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (131,'1:Inwentarz ogólny',1,'Ogrzewnictwo i cep³ownictwo.Izolacja cieplna przewodów,armatury i urz¹dzeñ.Wymagania i badania odbiorcze.','Polski  Komitet Normalizacyjny','Ogrzewnictwo i cep³ownictwo.Izolacja cieplna przewodów,armatury i urz¹dzeñ.Wymagania i badania odbiorcze. \ PN-85/B-02421','PN-B-02421')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (132,'1:Inwentarz ogólny',1,'Fundamenty budowlane.Noœnoœæ pali i fundamentów palowych.','Polski  Komitet Normalizacyjny','Fundamenty budowlane.Noœnoœæ pali i fundamentów palowych. \ PN-69/B-02482','PN-83/B-02482')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (133,'1:Inwentarz ogólny',1,'zast¹piona czêœciowo przez PN-B-02851-1:1997','Ochrona przeciwpo¿arowa budynków.Metoda badania odpornoœci ogniowej elementów budynków.','Polski  Komitet Normalizacyjny','Ochrona przeciwpo¿arowa budynków.Metoda badania odpornoœci ogniowej elementów budynków. \ PN-64/B-02851','PN-90/B-02851')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (134,'1:Inwentarz ogólny',1,'Ochrona przeciwpo¿arowa budynków.Metoda badania rozprzestrzeniania p³omieni po posadzkach pod³ogowych.','Polski  Komitet Normalizacyjny','Ochrona przeciwpo¿arowa budynków.Metoda badania rozprzestrzeniania p³omieni po posadzkach pod³ogowych. \ PN-88/B-02854','PN-B-02854:1996')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (135,'1:Inwentarz ogólny',1,'Przeciwpo¿arowe zbiorniki wodne.Wymagania ogólne.','Polski  Komitet Normalizacyjny','Przeciwpo¿arowe zbiorniki wodne.Wymagania ogólne. \ PN-67/B-02857','PN-82/B-02857')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (136,'1:Inwentarz ogólny',1,'Przeciwpo¿arowe zaopatrzenie wodne.Sieæ wodoci¹gowa przeciwpo¿arowa.','Polski  Komitet Normalizacyjny','Przeciwpo¿arowe zaopatrzenie wodne.Sieæ wodoci¹gowa przeciwpo¿arowa. \ PN-71/B-02863','PN-B-02863:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (137,'1:Inwentarz ogólny',1,'Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne...','Polski  Komitet Normalizacyjny','Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne... \ PN-71/B-02864','PN-B-02864:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (139,'1:Inwentarz ogólny',1,'Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne.Instalacja wodoci¹gowa przeciwpo¿arowa.','Polski  Komitet Normalizacyjny','Ochrona przeciwpo¿arowa budynków.Przeciwpo¿arowe zaopatrzenie wodne.Instalacja wodoci¹gowa przeciwpo¿arowa. \ PN-72/B-02865','PN-B-02865:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (140,'1:Inwentarz ogólny',1,'zmiany-Az1; Az2; Az3','Konstrukcje drewniane.Obliczenia statyczne i projektowanie.','Polski  Komitet Normalizacyjny','Konstrukcje drewniane.Obliczenia statyczne i projektowanie. \ PN-81/B-03150/00; Konstrukcje drewniane.Obliczenia statyczne i projektowanie. \ PN-81/B-03150/01; Konstrukcje drewniane.Obliczenia statyczne i projektowanie. \ PN-81/B-03150/02; Konstrukcje dr','PN-B-03150:2000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (141,'1:Inwentarz ogólny',1,'Konstrukcje stalowe.Obliczenia statyczne i projektowanie.','Polski  Komitet Normalizacyjny','Konstrukcje stalowe.Obliczenia statyczne i projektowanie. \ PN-80/B-03200','PN-90/B-03200')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (142,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Konstukcje aluminiowe.Obliczenia statyczne i projektowanie.','Polski  Komitet Normalizacyjny','PN-64/B-03220')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (143,'1:Inwentarz ogólny',1,'zmiany-Az1:2004','Konstrukcje murowe zbrojone.Projektowanie i obliczanie.','Polski  Komitet Normalizacyjny','Konstrukcje murowe zbrojone.Projektowanie i obliczanie. \ PN-89/B-03340; Konstrukcje murowe zbrojone.Projektowanie i obliczanie. \ PN-67/B-03005','PN-B-03340:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (144,'1:Inwentarz ogólny',1,'Oliczanie zapotrzebowania ciep³a pomieszczeñ o kubaturze do 600 m3','Polski  Komitet Normalizacyjny','Oliczanie zapotrzebowania ciep³a pomieszczeñ o kubaturze do 600 m3 \ PN-74/B-03406','PN-83/B-03406')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (145,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Wentylacja i klimatyzacja.Parametry obliczeniowe powietrza zewnêtrznego.','Polski  Komitet Normalizacyjny','Wentylacja i klimatyzacja.Parametry obliczeniowe powietrza zewnêtrznego. \ PN-64/B-03420','PN-76/B-03420')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (146,'1:Inwentarz ogólny',1,'Wentylacja i klimatyzacja.Parametry obliczeniowe powietrza wew. w pomieszczeniach przeznaczonych do sta³ego przebywania ludzi.','Polski  Komitet Normalizacyjny','PN-78/B-03421')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (147,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'zmiana Az3','Wentylacja w budynkach mieszkalnych zamieszkania zbiorowego i u¿ytecznoœci publicznej.Wymagania.','Polski  Komitet Normalizacyjny','Wentylacja w budynkach mieszkalnych zamieszkania zbiorowego i u¿ytecznoœci publicznej.Wymagania. \ PN-74/B-03430','PN-83/B-03430')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (149,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Wentylacja mechaniczna w budownictwie.Wymagania.','Polski  Komitet Normalizacyjny','Wentylacja mechaniczna w budownictwie.Wymagania. \ PN-63/B-03431','PN-73/B-03431')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (151,'1:Inwentarz ogólny',1,'Wentylacja.Instalacje wentylacji mechanicznej wywiewnej w budynkach mieszkalnych wielorodzinnych.Wymagania.','Polski  Komitet Normalizacyjny','Wentylacja.Instalacje wentylacji mechanicznej wywiewnej w budynkach mieszkalnych wielorodzinnych.Wymagania. \ PN-80/B-03433','PN-87/B-03433')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (152,'1:Inwentarz ogólny',1,'Geotechnika.Roboty ziemne.Wymagania ogólne.','Polski  Komitet Normalizacyjny','Geotechnika.Roboty ziemne.Wymagania ogólne. \ PN-68/B-06050','PN-B-06050:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (154,'1:Inwentarz ogólny',1,'Roboty betonowe i ¿elbetowe.Wymagania techniczne.','Polski  Komitet Normalizacyjny','Roboty betonowe i ¿elbetowe.Wymagania techniczne. \ PN-55/B-06251','PN-63/B-06251')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (155,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty betonowe i ¿elbetowe.Konstrukcje kablobetonowe.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','PN-72/B-06270')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (156,'1:Inwentarz ogólny',1,'Kruszywa mineralne.Piaski do zapraw budowlanych.','Polski  Komitet Normalizacyjny','Kruszywa mineralne.Piaski do zapraw budowlanych. \ BN-69/6721-04','PN-79/B-06711')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (157,'1:Inwentarz ogólny',1,'Tablice orientacyjne do oznaczania uzbrojenia na przewodach wodoci¹gowych.','Polski  Komitet Normalizacyjny','Tablice orientacyjne do oznaczania uzbrojenia na przewodach wodoci¹gowych. \ PN-62/B-09700','PN-86/B-09700')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (158,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'egz. 1 zagubiony','Roboty murowe z ceg³y.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Roboty murowe z ceg³y.Wymagania i badania przy odbiorze. \ PN-53/B-02062,63; Roboty murowe z ceg³y.Wymagania i badania przy odbiorze. \ PN-53/B-10020,22','PN-68/B-10020')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (160,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty murowe.Konstrukcje ceglano-¿elbetowe wykonywane na budowie.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Roboty murowe.Konstrukcje ceglano-¿elbetowe wykonywane na budowie.Wymagania i badania przy odbiorze. \ PN-58/B-10023','PN-69/B-10023')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (161,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty murowe.Mury z drobnowymiarowych elementów z autoklawizowanych betonów  komórkowych.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','PN-68/B-10024')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (162,'1:Inwentarz ogólny',1,'Stolarka budowlana.Okna i drzwi.Wymagania i badania.','Polski  Komitet Normalizacyjny','Stolarka budowlana.Okna i drzwi.Wymagania i badania. \ PN-83/B-10085','PN-88/B-10085')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (163,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty tynkowe.Tynki zwyk³e.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Roboty tynkowe.Tynki zwyk³e.Wymagania i badania przy odbiorze. \ PN-58/B-10100','PN-70/B-10100')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (164,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty tynkowe.Tynki szlachetne.Wymagania i badania techniczne przy odbiorze.','Polski  Komitet Normalizacyjny','PN-65/B-10101')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (165,'1:Inwentarz ogólny',1,'Posadzki z p³ytek kamionkowych(terakotowych),klinkierowych i lastrykowych.Wymagania i badania techniczne przy odbiorze.','Polski  Komitet Normalizacyjny','PN-63/B-10145')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (166,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Roboty pokrywcze.Krycie dachówk¹ ceramiczn¹.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Roboty pokrywcze.Krycie dachówk¹ ceramiczn¹.Wymagania i badania przy odbiorze. \ PN-59/B-10241','PN-71/B-10241')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (167,'1:Inwentarz ogólny',1,'Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze. \ PN-91/B-10405; Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze. \ BN-75/8973-10; Ciep³ownictwo.Sieci ciep³ownicze.Wymagania i badania przy odbiorze. \ BN-77/8973-11','PN-B-10405/1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (168,'1:Inwentarz ogólny',1,'Urz¹dzenia ciep³ej wody w budynkach.Wymaganiai badania przy odbiorze.','Polski  Komitet Normalizacyjny','PN-71/B-10420')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (169,'1:Inwentarz ogólny',1,'Przewody dymowe,spalinowe i wentylacyjne murowane zceg³y.Wymagania techniczne i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Przewody dymowe,spalinowe i wentylacyjne murowane zceg³y.Wymagania techniczne i badania przy odbiorze. \ PN-59/B-10425','PN-89/B-10425')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (170,'1:Inwentarz ogólny',1,'Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania.','Polski  Komitet Normalizacyjny','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania. \ PN-59/B-10700; Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Wspólne wymagania i badania. \ PN-59/B-1','PN-81/B-10700.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (171,'1:Inwentarz ogólny',1,'Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne.','Polski  Komitet Normalizacyjny','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne. \ PN-59/B-10700; Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Instalacje kanalizacyjne. \ PN-59/B-10701;','PN-81/B-10700.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (172,'1:Inwentarz ogólny',1,'Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody ciep³ej z rur stalowych ocynkowanych.','Polski  Komitet Normalizacyjny','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody ciep³ej z rur stalowych ocynkowanych. \ PN-59/B-10700; Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody cie','PN-81/B-10700.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (173,'1:Inwentarz ogólny',1,'Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody zimnej z polichlorku winylu i polietylenu.','Polski  Komitet Normalizacyjny','Instalacje wewnêtrzne wodoci¹gowe i kanalizacyjne.Wymagania i badania przy odbiorze.Przewody wody zimnej z polichlorku winylu i polietylenu. \ PN-72/B-10722','PN-83/B-10700.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (174,'1:Inwentarz ogólny',1,'Wodoci¹gi i kanalizacja.Zbiorniki.Wymagania i badania.','Polski  Komitet Normalizacyjny','Wodoci¹gi i kanalizacja.Zbiorniki.Wymagania i badania. \ PN-85/B-10702','PN-B-10702:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (175,'1:Inwentarz ogólny',1,'Wodoci¹gi.Przewody zewnêtrzne.Wymagania i badania.','Polski  Komitet Normalizacyjny','PN-B-10725:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (176,'1:Inwentarz ogólny',1,'Kanalizacja.Studzienki kanalizacyjne.','Polski  Komitet Normalizacyjny','Kanalizacja.Studzienki kanalizacyjne. \ PN-92/B-10729','PN-B-10729:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (177,'1:Inwentarz ogólny',1,'Stacje hydroforowe.Wymagania i badania przy odbiorze.','Polski  Komitet Normalizacyjny','Stacje hydroforowe.Wymagania i badania przy odbiorze. \ PN-69/B-10740','PN-81/B-10740')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (178,'1:Inwentarz ogólny',1,'Ceg³y pe³ne i bloki dr¹¿one wapienno-piaskowe.','Polski  Komitet Normalizacyjny','Ceg³y pe³ne i bloki dr¹¿one wapienno-piaskowe. \ PN-70/B-12003','PN-75/B-12003')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (179,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Ceg³a termalitowa.','Polski  Komitet Normalizacyjny','Ceg³a termalitowa. \ PN-62/B-12019','PN-75/B-12019')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (183,'1:Inwentarz ogólny',1,'Porcelanowy sprzêt laboratoryjny.Wymagania i badania.','Polski  Komitet Normalizacyjny','Porcelanowy sprzêt laboratoryjny.Wymagania i badania. \ PN-65/C-12330','PN-78/B-12330')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (184,'1:Inwentarz ogólny',1,'Porcelanowy sprzêt laboratoryjny.Tygle.','Polski  Komitet Normalizacyjny','Porcelanowy sprzêt laboratoryjny.Tygle. \ BN-64/7027-01','PN-74/B-12331')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (185,'1:Inwentarz ogólny',1,'Porcelanowy sprzêt laboratoryjny.Parownice.','Polski  Komitet Normalizacyjny','Porcelanowy sprzêt laboratoryjny.Parownice. \ BN-64/7027-02','PN-74/B-12332')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (186,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Kolby destylacyjne.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Kolby destylacyjne. \ BN-63/6851-06','PN-75/B-13000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (187,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹. \ PN-57/C-13000; Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹. \ PN-61/C-13008; Szklany sprzêt laboratoryjny.Kolby produkowane metod¹ hutnicz¹. \ BN-63/6851-03; Szklany spr','PN-73/B-13005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (188,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Kolby wieloszyjkowe.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Kolby wieloszyjkowe. \ BN-63/6851-04; Szklany sprzêt laboratoryjny.Kolby wieloszyjkowe. \ BN-63/6851-05','PN-74/B-13006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (189,'1:Inwentarz ogólny',1,'uniewa¿niona czêœciowo dot. rozdz.4 PN-78/B-12101','Wyroby ceramiki szlachetnej i kamionki.Nazwy i okreœlenia.','Polski  Komitet Normalizacyjny','PN-68/B-12100')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (197,'1:Inwentarz ogólny',1,'uniewa¿niona, czêœciowo zast¹piona PN-92/B-13013','Szlify sto¿kowe z³¹czy szklanych.','Polski  Komitet Normalizacyjny','Szlify sto¿kowe z³¹czy szklanych. \ PN-63/C-13011','PN-74/B-13011')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (198,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Naczynia pomiarowe.Mikropipety wielomiarowe.','Polski  Komitet Normalizacyjny','PN-75/B-13022')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (199,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Naczynia ppomiarowe.Mikrobiurety Banga.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Naczynia ppomiarowe.Mikrobiurety Banga. \ PN-68/C-13027','PN-74/B-13027')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (200,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Lejki.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Lejki. \ PN-57/C-13031','PN-72/B-13031')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (201,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Lejki rozdzielcze.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Lejki rozdzielcze. \ PN/C-13030; Szklany sprzêt laboratoryjny.Lejki rozdzielcze. \ PN/C-13035','PN-74/B-13035')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (202,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.Eksykatory.','Polski  Komitet Normalizacyjny','Szklany sprzêt laboratoryjny.Eksykatory. \ PN-57/C-13039','PN-75/B-13039')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (203,'1:Inwentarz ogólny',1,'Wady szk³a i wyrobów szklanych.Podzia³, nazwy i okreœlenia.','Polski  Komitet Normalizacyjny','Wady szk³a i wyrobów szklanych.Podzia³, nazwy i okreœlenia. \ PN-64/C-13200','PN-76/B-13200')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (204,'1:Inwentarz ogólny',1,'Materia³y do izolacji cieplnej z w³ókien nieorganicznych.We³na mineralna.','Polski  Komitet Normalizacyjny','Materia³y do izolacji cieplnej z w³ókien nieorganicznych.We³na mineralna. \ PN-67/B-23100','PN-75/B-23100')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (205,'1:Inwentarz ogólny',1,'zmiana Az1:2004','Lepiki, masy i roztwory asfaltowe stosowane na zimno.','Polski  Komitet Normalizacyjny','Lepiki, masy i roztwory asfaltowe stosowane na zimno. \ PN-74/B-24620; Lepiki, masy i roztwory asfaltowe stosowane na zimno. \ PN-74/B-24622; Lepiki, masy i roztwory asfaltowe stosowane na zimno. \ PN-76/B-24628','PN-B-24620:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (206,'1:Inwentarz ogólny',1,'Lepik asfaltowy do posadzki deszczu³kowej.','Polski  Komitet Normalizacyjny','Lepik asfaltowy do posadzki deszczu³kowej. \ PN-64/B-24624','PN-71/B-24624')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (207,'1:Inwentarz ogólny',1,'Papa asfaltowa na welonie z w³ókien szklanych.','Polski  Komitet Normalizacyjny','Papa asfaltowa na welonie z w³ókien szklanych. \ BN-88/6751-03','PN-B-27620:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (208,'1:Inwentarz ogólny',1,'Spoiwa gipsowe.Gips szpachlowy, gips tynkarski i klej gipsowy.','Polski  Komitet Normalizacyjny','Spoiwa gipsowe.Gips szpachlowy, gips tynkarski i klej gipsowy. \ BN-80/6733-09','PN-B-30042:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (209,'1:Inwentarz ogólny',1,'Kity budowlane trwale plastyczne-olejowy i polistyrenowy.','Polski  Komitet Normalizacyjny','Kity budowlane trwale plastyczne-olejowy i polistyrenowy. \ BN-85/6753-02','PN-B-30150:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (210,'1:Inwentarz ogólny',1,'Kit tiokolowy.','Polski  Komitet Normalizacyjny','Kit tiokolowy. \ BN-78/6753-05','PN-B-30151:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (211,'1:Inwentarz ogólny',1,'Kity budowlane kauczukowe i asfaltowo-kauczukowe uszczelniaj¹ce.','Polski  Komitet Normalizacyjny','Kity budowlane kauczukowe i asfaltowo-kauczukowe uszczelniaj¹ce. \ BN-85/6753-07; Kity budowlane kauczukowe i asfaltowo-kauczukowe uszczelniaj¹ce. \ BN-85/6753-08','PN-B-30152:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (212,'1:Inwentarz ogólny',1,'Wyroby budowlane z tworzyw sztucznych.Ok³adzina porêczowa z polichlorku winylu.','Polski  Komitet Normalizacyjny','Wyroby budowlane z tworzyw sztucznych.Ok³adzina porêczowa z polichlorku winylu. \ PN-75/B-89020','PN-93/B-89020')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (213,'1:Inwentarz ogólny',1,'Drzwi.Zasady ustalania wymiarów skoordynowanych modularnie.','Polski  Komitet Normalizacyjny','Drzwi.Zasady ustalania wymiarów skoordynowanych modularnie. \ PN-66/B-91003','PN-89/B-91003')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (214,'1:Inwentarz ogólny',1,'Elementy i segmenty œcienne metalowe.Drzwi i wrota.Wymiary modularne.','Polski  Komitet Normalizacyjny','PN-82/B-92010')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (217,'1:Inwentarz ogólny',1,'Military Handbook.Reliability Prediction of Electronic Equipment','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','MIL-HDBK-217F-Notice 1')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (218,'1:Inwentarz ogólny',1,'Military Handbook.Reliability Prediction of Electronic Equipment','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','MIL-HDBK-217F')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (219,'1:Inwentarz ogólny',1,'Military Handbook.Reliability Prediction of Electronic Equipment','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','MIL-HDBK-217F-Notice 2')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (220,'1:Inwentarz ogólny',1,'Requirements for the control of electromagnetic interference characteristics of subsystems and equipment','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','MIL-STD-461E')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (221,'1:Inwentarz ogólny',1,'Elementy i segmenty œcienne metalowe.Drzwi o zwiêkszonej odpornoœci na w³amanie klasy C.Wymagania i badania uzupe³niaj¹ce.','Polski  Komitet Normalizacyjny','PN-90/B-92270')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (222,'1:Inwentarz ogólny3:Inwentarz ogólny',1,'brak 2 egz.','Okucia budowlane.Zawiasy czopowe dwuskrzyd³owe rozwierane ze skszyde³kami prostymi do wpuszczania.','Polski  Komitet Normalizacyjny','Okucia budowlane.Zawiasy czopowe dwuskszyd³owe rozwierane ze skszyde³kami prostymi do wpuszczania. \ PN-64/B-94053','PN-75/B-94053')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (223,'1:Inwentarz ogólny',1,'Okucia budowlane.Zawiasy czopowe dwuskrzyd³owe rozwierane ze skrzyde³kami odgiêtymi.','Polski  Komitet Normalizacyjny','Okucia budowlane.zawiasy czopowe dwuskrzyd³owe rozwierane ze skrzyde³kami odgiêtymi. \ PN-64/B-94054','PN-73/B-94054')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (225,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Okucia budowlane.Zawiasy splatane.','Polski  Komitet Normalizacyjny','PN-62/B-94055')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (226,'1:Inwentarz ogólny',1,'Okucia budowlane.Zawiasy wahad³owe.','Polski  Komitet Normalizacyjny','Okucia budowlane.Zawiasy wahad³owe. \ PN-64/B-94058','PN-81/B-94058')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (227,'1:Inwentarz ogólny',1,'Okucia budowlane.Zawiasy czopowe dwuskrzyde³kowe  rozwierane ze skrzyde³kami prostymi','Polski  Komitet Normalizacyjny','PN-73/B-94060')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (228,'1:Inwentarz ogólny',1,'Okucia budowlane.Zasuwy wierzchnie i wpuszczane.','Polski  Komitet Normalizacyjny','Okucia budowlane.Zasuwy wierzchnie i wpuszczane. \ PN-60/B-94144; Okucia budowlane.Zasuwy wierzchnie i wpuszczane. \ PN-60/B-94145; Okucia budowlane.Zasuwy wierzchnie i wpuszczane. \ PN-63/B-94146','PN-69/B-94146')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (229,'1:Inwentarz ogólny',1,'Okucia budowlane.Zamki wierzchnie bêbenkowe.Konstrukcje.','Polski  Komitet Normalizacyjny','Okucia budowlane.Zamki wierzchnie bêbenkowe.Konstrukcje. \ PN-64/B-94451; Okucia budowlane.Zamki wierzchnie bêbenkowe.Konstrukcje. \ PN-64/B-94452','PN-79/B-94450.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (230,'1:Inwentarz ogólny',1,'Okucia budowlane.Zamki wierzchnie bêbenkowe zasuwkowe.','Polski  Komitet Normalizacyjny','PN-64/B-94451')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (231,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Okucia budowlane.Wk³adki bêbenkowe profilowe.Okreœlenia i podzia³.','Polski  Komitet Normalizacyjny','Okucia budowlane.Wk³adki bêbenkowe profilowe.Okreœlenia i podzia³. \ PN-64/B-94461.1.3','PN-74/B-94461.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (232,'1:Inwentarz ogólny',1,'Okucia budowlane.Wk³adki bêbenkowe profilowe.Wk³adki jednostronne.','Polski  Komitet Normalizacyjny','Okucia budowlane.Wk³adki bêbenkowe profilowe.Wk³adki jednostronne. \ PN-75/B-94461.03','PN-83/B-94461.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (233,'1:Inwentarz ogólny',1,'Zwi¹zki organiczne.Zasady budowy nazw.','Polski  Komitet Normalizacyjny','Zwi¹zki organiczne.Zasady budowy nazw. \ PN-C-01000:1952','PN-C-01000:1994')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (234,'1:Inwentarz ogólny',1,'Produkty chemiczne stosowane w przemyœle.Pobieranie próbek.Terminologia.','Polski  Komitet Normalizacyjny','PN-92/C-01010')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (235,'1:Inwentarz ogólny',1,'Produkty chemiczne stosowane w przemyœle.Pobieranie próbek.zagadnienia bezpieczeñstwa.','Polski  Komitet Normalizacyjny','PN-93/C-01011')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (236,'1:Inwentarz ogólny',1,'Analiza chemiczna.Wytyczne wykonywania badañ.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Wytyczne wykonywania badañ. \ PN-67/C-01055','PN-81/C-01055')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (237,'1:Inwentarz ogólny',1,'Oznaczenia stopni czystoœci surowców i produktów przemys³u chemicznego.','Polski  Komitet Normalizacyjny','Oznaczenia stopni czystoœci surowców i produktów przemys³u chemicznego. \ PN-65/C-01060','PN-68/C-01060')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (238,'1:Inwentarz ogólny',1,'Analiza gazów.Sporz¹dzanie mieszanin gazów do wzorcowania.Metody wagowe.','Polski  Komitet Normalizacyjny','PN-88/C-01300')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (239,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Wa¿niejsze wielkoœci i jednostki u¿ywane w chemii fizycznej.Oznaczenia.','Polski  Komitet Normalizacyjny','PN-53/C-01370')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (240,'1:Inwentarz ogólny',1,'Guma.Terminologia.Podzia³, nazwy i symbole kauczuków.','Polski  Komitet Normalizacyjny','Guma.Terminologia.Podzia³, nazwy i symbole kauczuków. \ PN-81/C-01604/01','PN-92/C-01604/01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (241,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Kleje.Zasady podzia³u.','Polski  Komitet Normalizacyjny','PN-68/C-02004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (242,'1:Inwentarz ogólny',1,'zast¹piona czêœciowo przez PN-ISO 3170:1993, PN-EN 58:1997','Ropa naftowa i przetwory naftowe.Pobieranie próbek.','Polski  Komitet Normalizacyjny','Ropa naftowa i przetwory naftowe.Pobieranie próbek. \ PN-61/C-04000','PN-66/C-04000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (243,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczenia temperatury zap³onu w tyglu otwartym metod¹ Marcussona.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczenia temperatury zap³onu w tyglu otwartym metod¹ Marcussona. \ PN-65/C-04008','PN-82/C-04008')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (244,'1:Inwentarz ogólny',1,'Przetwory naftowe.Obliczanie wska¿nika lepkoœci na podstawie lepkoœci kinematycznej w 40 i 100 C.','Polski  Komitet Normalizacyjny','PN-79/C-04013')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (245,'1:Inwentarz ogólny',1,'Przetwory hnaftowe.Oznaczanie lepkoœci wzglêdnej lepkoœciomierzem.Englera.','Polski  Komitet Normalizacyjny','Przetwory hnaftowe.Oznaczanie lepkoœci wzglêdnej lepkoœciomierzem.Englera. \ PN-C-04014','PN-77/C-04014')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (246,'1:Inwentarz ogólny',1,'Przetwory naftowe.Obliczanie wska¿nika lepkoœci na podstawie lepkoœci kinematycznej w 37,78,98,89 C.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Obliczanie wska¿nika lepkoœci na podstawie lepkoœci kinematycznej w 37,78,98,89 C. \ PN/C-04015','PN-73/C-04015')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (247,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Pomiar temperatury krzepniêcia metod¹ probówkow¹.','Polski  Komitet Normalizacyjny','PN-55/C-04016')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (248,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie temperatury mêtnienia i pocz¹tku krystalizacji paliw silnikowych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie temperatury mêtnienia i pocz¹tku krystalizacji paliw silnikowych. \ PN-66/C-04017','PN-84/C-04017')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (249,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie temperatury krzepniêcia metod¹ ¯ukowa.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie temperatury krzepniêcia metod¹ ¯ukowa. \ PN/C-04018','PN-77/C-04018')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (250,'1:Inwentarz ogólny',1,'Oznaczanie lepkoœci dynamicznej lepkoœciomierzem Hopplera.','Polski  Komitet Normalizacyjny','Oznaczanie lepkoœci dynamicznej lepkoœciomierzem Hopplera. \ PN-68/C-04019','PN-78/C-04019')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (251,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Pomiar temperatury kroplenia metod¹ Ubbelohdea.','Polski  Komitet Normalizacyjny','PN-55/C-04020')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (252,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie temperatury krzepniêcia wosków naftowych metod¹ galicyjsk¹.','Polski  Komitet Normalizacyjny','PN-82/C-04022')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (253,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie flokulacji olejów do sprê¿arek ch³odniczych.','Polski  Komitet Normalizacyjny','PN-89/C-04045')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (254,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie w³asnoœci przeciwzu¿yciowych cieczy hydraulicznej za pomoc¹ pompy ³opatkowej (próba Vickersa)','Polski  Komitet Normalizacyjny','PN-87/C-04048')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (255,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie odpornoœci olejów na pienienie.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie odpornoœci olejów na pienienie. \ PN-74/C-04055','PN-85/C-04055')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (256,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe w smarach plastycznych zawartoœci zanieczyszczeñ mechanicznych nierozpuszczalnych w kwasie solnym.','Polski  Komitet Normalizacyjny','Przetwory naftowe w smarach plastycznych zawartoœci zanieczyszczeñ mechanicznych nierozpuszczalnych w kwasie solnym. \ PN-53/C-04060; Przetwory naftowe w smarach plastycznych zawartoœci zanieczyszczeñ mechanicznych nierozpuszczalnych w kwasie solnym. \ P','PN-70/C-04060')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (258,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie w³asnoœci demulguj¹cych olejów mineralnych i cieczy hydraulicznych syntetycznych.','Polski  Komitet Normalizacyjny','PN-86/C-04065')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (259,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie liczby kwasowej i zasadowej oraz kwasowoœci metod¹ miareczkowania wobec wska¿ników.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie liczby kwasowej i zasadowej oraz kwasowoœci metod¹ miareczkowania wobec wska¿ników. \ PN-67/C-04066','PN-85/C-04066')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (260,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci chloru w olejach smarowych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci chloru w olejach smarowych. \ PN-54/C-04070; Przetwory naftowe.Oznaczanie zawartoœci chloru w olejach smarowych. \ PN-72/C-04071','PN-91/C-04071')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (261,'1:Inwentarz ogólny',1,'Badanie w³asnoœci smarnych olejów i smarów metod¹ Timkena.','Polski  Komitet Normalizacyjny','PN-86/C-04073')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (262,'1:Inwentarz ogólny',1,'Przetwory naftowe.Wykrywanie siarki aktywnej w olejach elektroizolacyjnych.','Polski  Komitet Normalizacyjny','PN-80/C-04074')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (263,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie w³asnoœci przeciwkorozyjnych olejów mineralnych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Badanie w³asnoœci przeciwkorozyjnych olejów mineralnych. \ PN-73/C-04082','PN-81/C-04082')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (264,'1:Inwentarz ogólny',1,'Oznaczanie odpornoœci hydrolitycznej cieczy hydraulicznych.','Polski  Komitet Normalizacyjny','PN-88/C-04084')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (265,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Jakoœciowe oznaczanie wody.','Polski  Komitet Normalizacyjny','PN-56/C-04085')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (266,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie odpornoœci na utlenianie olejów smarowych o podwy¿szonej zdolnoœci do przenoszenia obci¹¿eñ.','Polski  Komitet Normalizacyjny','PN-91/C-04086')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (267,'1:Inwentarz ogólny',1,'Ropa naftowa i przetwory.Oznaczanie zawartoœci wody i sta³ych cia³ obcych metod¹ wirówkow¹.','Polski  Komitet Normalizacyjny','Ropa naftowa i przetwory.Oznaczanie zawartoœci wody i sta³ych cia³ obcych metod¹ wirówkow¹. \ PN-59/C-04087','PN-89/C-04087')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (268,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci sta³ych cia³ obcych.','Polski  Komitet Normalizacyjny','PN-58/C-04089')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (269,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych i stabilnoœci termooksydacyjnej  olejów smarowych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych i stabilnoœci termooksydacyjnej  olejów smarowych. \ PN-59/C-04096','PN-62/C-04096')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (270,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie lepkoœci dynamicznej HTHS olejów silnikowych lepkoœciomierzem Ravenfielda','Polski  Komitet Normalizacyjny','PN-C-04098:1994')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (271,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie odpornoœci smarów plastycznych na wymywanie wod¹, metod¹ dynamiczn¹.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Badanie odpornoœci smarów plastycznych na wymywanie wod¹, metod¹ dynamiczn¹. \ BN-69/0536-12','PN-85/C-04099')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (273,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie sk³onnoœci do wydzielania siê smarów plastycznych z ³o¿ysk kó³ samochodowych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Badanie sk³onnoœci do wydzielania siê smarów plastycznych z ³o¿ysk kó³ samochodowych. \ BN-72/0536-16','PN-85/C-04102')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (274,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci parafiny w olejach.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci parafiny w olejach. \ PN-63/C-04109','PN-71/C-04113')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (275,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie policyklicznych wêglowodorów aromatycznych w parafinie metod¹ fluorescyjn¹.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie policyklicznych wêglowodorów aromatycznych w parafinie metod¹ fluorescyjn¹. \ PN-70/C-04028','PN-82/C-04128')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (276,'1:Inwentarz ogólny',1,'Przetwory naftowe.Pomiar penetracji smarów plastycznych i petrolatum penetrometrem ze sto¿kiem.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Pomiar penetracji smarów plastycznych i petrolatum penetrometrem ze sto¿kiem. \ PN-79/C-04133; Przetwory naftowe.Pomiar penetracji smarów plastycznych i petrolatum penetrometrem ze sto¿kiem. \ PN-71/C-04135','PN-88/C-04133')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (277,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie temperatury kroplenia smarów plastycznych.','Polski  Komitet Normalizacyjny','PN-84/C-04139')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (278,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Smary sta³e.Oznaczanie zawartoœci sta³ych cia³ obcych.','Polski  Komitet Normalizacyjny','PN-55/C-04141')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (279,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Badanie na substancje rysuj¹ce w smarach sta³ych.','Polski  Komitet Normalizacyjny','PN-58/C-04142')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (280,'1:Inwentarz ogólny',1,'Przetwory naftowe.Smary sta³e.Badanie na utlenianie.','Polski  Komitet Normalizacyjny','PN-56/C-04143')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (281,'1:Inwentarz ogólny',1,'Przetwory naftowe.Pomiar lepkoœci strukturalnej smarów sta³ych.','Polski  Komitet Normalizacyjny','PN-63/C-04146')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (282,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie odpornoœci na utlenianie olejów turbinowych z dodatkami.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie odpornoœci na utlenianie olejów turbinowych z dodatkami. \ PN-73/C-04148','PN-83/C-04148')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (283,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci wolnych zasad i wolnych kwasów organicznych w smarach sta³ych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci wolnych zasad i wolnych kwasów organicznych w smarach sta³ych. \ PN-54/C-04152','PN-68/C-04152')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (285,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Badanie sk³onnoœci do sp³ywania smarów plastycznych (sta³ych) z powierzchni metalu.','Polski  Komitet Normalizacyjny','PN-69/C-04153')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (286,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Badanie w³asnoœæi przeciwkorozyjnych ciek³ych œrodków ochrony czasowej metali w wilgotnej atmosferze.','Polski  Komitet Normalizacyjny','PN-75/C-04154')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (287,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci oleju w parafinie, cerezynie i petrolatum.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci oleju w parafinie, cerezynie i petrolatum. \ PN-60/C-04160','PN-80/C-04160')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (288,'1:Inwentarz ogólny',1,'Przetwory naftowe.Pomiar penetracji parafin i cerezyn.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Pomiar penetracji parafin i cerezyn. \ PN-60/C-04161','PN-82/C-04161')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (289,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczenie ca³kowitej liczby zasadowej metod¹ potencjometrycznego miareczkowania kwasem nadchlorowym.','Polski  Komitet Normalizacyjny','PN-76/C-04163')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (290,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie odpornoœci na œcinanie olejów smarowych i cieczy hydraulicznych w ap.ultr.','Polski  Komitet Normalizacyjny','PN-77/C-04166')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (291,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Badanie w³asnoœci przeciwrdzewnych olejów przek³adniowych.','Polski  Komitet Normalizacyjny','PN-77/C-04168')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (292,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci baru,wapnia,magnezu, fosforu i cynku w olejach smarowych i dodatkach met. spektrografii emis.','Polski  Komitet Normalizacyjny','PN-78/C-04172')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (294,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badania w³asnoœci przeciwkorozyjnych smarów plastycznych metod¹ dynamiczn¹.','Polski  Komitet Normalizacyjny','PN-79/C-04175')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (296,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci sta³ych cia³ obcych w olejach smarowych i hydraulicznych na s¹czku membranowym.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci sta³ych cia³ obcych w olejach smarowych i hydraulicznych na s¹czku membranowym. \ PN-81/C-04178','PN-91/C-04178')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (297,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie odpornoœci olejów do sprê¿arek ch³odniczych na dzia³anie czynników ch³odniczych.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Badanie odpornoœci olejów do sprê¿arek ch³odniczych na dzia³anie czynników ch³odniczych. \ PN-74/C-96072p.3.5','PN-88/C-04183')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (298,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zdolnoœci olejów smarowych do demulgowania.','Polski  Komitet Normalizacyjny','PN-90/C-04184')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (299,'1:Inwentarz ogólny',1,'Przetwory naftowe.Badanie trwa³oœci u¿ytkowej smarów plastycznych na stanowisku badawczym SKF R2F.','Polski  Komitet Normalizacyjny','PN-88/C-04185')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (300,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie szybkoœci filtrowania cieczy hydraulicznych.','Polski  Komitet Normalizacyjny','PN-90/C-04188')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (301,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych w olejach lotniczych metod¹ dynamiczn¹.','Polski  Komitet Normalizacyjny','Przetwory naftowe.Oznaczanie zawartoœci czêœci lotnych w olejach lotniczych metod¹ dynamiczn¹. \ PN-70/C-96032p.2.2.6','PN-83/C-04190')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (303,'1:Inwentarz ogólny',1,'Przetwory naftowe. Oznaczanie odpornoœci na utleniane olejów do sprê¿arek powietrza.','Polski  Komitet Normalizacyjny','PN-91/C-04191')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (304,'1:Inwentarz ogólny',1,'Przetwory naftowe.Oznaczanie zawartoœci sta³ych cia³ obcych w smarach metod¹ filtracji.','Polski  Komitet Normalizacyjny','PN-91/C-04192')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (306,'1:Inwentarz ogólny',1,'Guma.Oznaczanie temperatury kruchoœci metod¹ uderzeniow¹.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie temperatury kruchoœci metod¹ uderzeniow¹. \ PN-56/C-04214','PN-73/C-04214')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (307,'1:Inwentarz ogólny',1,'Lateks kauczuku naturalnego zatê¿any przez odwirowanie lub kremowanie.Wytyczne pakowania, przechowywania i transportu.','Polski  Komitet Normalizacyjny','PN-86/C-04230.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (308,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Guma.Oznaczanie twardoœci wg metody Shorea.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie twardoœci wg metody Shorea. \ PN-71/C-04238','PN-80/C-04238')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (309,'1:Inwentarz ogólny',1,'Tworzywa sztuczne.Oznaczanie wytrzyma³oœci na zginanie za pomoc¹ aparatu-typ Dynstat.','Polski  Komitet Normalizacyjny','Tworzywa sztuczne.Oznaczanie wytrzyma³oœci na zginanie za pomoc¹ aparatu-typ Dynstat. \ PN-56/C-04243','PN-72/C-04243')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (310,'1:Inwentarz ogólny',1,'Guma.Oznaczanie zawartoœci siarki.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie zawartoœci siarki. \ PN-69/C-04244','PN-75/C-04244')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (311,'1:Inwentarz ogólny',1,'czêœciowo uniewa¿niona-zast¹piona PN-92/C-04249, PN-93/C-04210','Guma.Oznaczanie wytrzyma³oœci po³¹czeñ guma-metal.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie wytrzyma³oœci po³¹czeñ guma-metal. \ PN-70/C-04252','PN-82/C-04252')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (312,'1:Inwentarz ogólny',1,'Wzorcowe mieszanki gumowe.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','PN-83/C-04258.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (315,'1:Inwentarz ogólny',1,'Wzorcowe mieszanki gumowe.Kauczuki metylowinylosilikonowe.Sk³ad, wykonywanie warunki wulkanizacji i badanie w³asnoœci.','Polski  Komitet Normalizacyjny','PN-91/C-04258/11')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (316,'1:Inwentarz ogólny',1,'Guma.Oznaczanie wytrzyma³oœci na rozwarstwianie po³¹czeñ gumy, gumy z tkanin¹ i tkaniny gumowanej z tkanin¹ gumow¹.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie wytrzyma³oœci na rozwarstwianie po³¹czeñ gumy, gumy z tkanin¹ i tkaniny gumowanej z tkanin¹ gumow¹. \ PN-65/C-04265','PN-74/C-04265')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (317,'1:Inwentarz ogólny',1,'Guma.Oznaczanie twardoœci metod¹ Jonesa.','Polski  Komitet Normalizacyjny','PN-55/C-04279')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (318,'1:Inwentarz ogólny',1,'Produkty chemiczne organiczne.Metody badañ.Oznaczanie liczby jodowej.','Polski  Komitet Normalizacyjny','Produkty chemiczne organiczne.Metody badañ.Oznaczanie liczby jodowej. \ PN-78/C-04281','PN-87/C--04281')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (319,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Guma.Oznaczanie odpornoœci na wielokrotne rozci¹ganie.','Polski  Komitet Normalizacyjny','Guma.Oznaczanie odpornoœci na wielokrotne rozci¹ganie. \ PN-71/C-04338','PN-78/C-04338')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (320,'1:Inwentarz ogólny',1,'zast¹piona czêœciowo przez PN-ISO 8213:1999','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek.','Polski  Komitet Normalizacyjny','Produkty chemiczne.Wytyczne pobierania i przygotowania próbek. \ PN/C-04504; Produkty chemiczne.Wytyczne pobierania i przygotowania próbek. \ PN/C-04505; Produkty chemiczne.Wytyczne pobierania i przygotowania próbek. \ PN/C-04506; Produkty chemiczne.Wyty','PN-67/C-04500')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (321,'1:Inwentarz ogólny',1,'Analiza sitowa.Wytyczne wykonywania.','Polski  Komitet Normalizacyjny','Analiza sitowa.Wytyczne wykonywania. \ PN-56/C-04501','PN-71/C-04501')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (322,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci wêglanów.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci wêglanów. \ PN-68/C-04502','PN-90/C-04502')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (324,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci fosforanów w bezbarwnych roztworach metod¹ kolorymetryczn¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci fosforanów w bezbarwnych roztworach metod¹ kolorymetryczn¹. \ PN-68/C-04503','PN-82/C-04503')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (325,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie gêstoœci produktów chemicznych ciek³ych i sta³ych w postaci proszku.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie gêstoœci produktów chemicznych ciek³ych i sta³ych w postaci proszku. \ PN-81/C-04504','PN-92/C-04504')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (326,'1:Inwentarz ogólny',1,'Produkty organiczne.Oznaczanie temperatury krzepniêcia metod¹ ¯ukowa.','Polski  Komitet Normalizacyjny','PN-84/C-04508')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (327,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci azotanów.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci azotanów. \ PN-68/C-04509','PN-81/C-04509')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (328,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci arsenu.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci arsenu. \ PN-75/C-04511','PN-81/C-04511')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (329,'1:Inwentarz ogólny',1,'Produkty chemiczne organiczne.Oznaczanie granic temperatury wrzenia.','Polski  Komitet Normalizacyjny','Produkty chemiczne organiczne.Oznaczanie granic temperatury wrzenia. \ PN-79/C-04512','PN-88/C-04512')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (330,'1:Inwentarz ogólny',1,'Oznaczanie granic temperatury topnienia lub temperatury rozk³adu substancji organicznych.','Polski  Komitet Normalizacyjny','Oznaczanie granic temperatury topnienia lub temperatury rozk³adu substancji organicznych. \ PN-76/C-04513','PN-81/C-04513')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (331,'1:Inwentarz ogólny',1,'Oznaczanie temperatury krystalizacji substancji organicznych.','Polski  Komitet Normalizacyjny','Oznaczanie temperatury krystalizacji substancji organicznych. \ PN-75/C--04514','PN-81/C-04514')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (332,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci metali ciê¿kich.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci metali ciê¿kich. \ PN-68/C-04515','PN-80/C-04515')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (333,'1:Inwentarz ogólny',1,'Oznaczanie zawartoœci substancji redukuj¹cych nadmanganian potasowy.','Polski  Komitet Normalizacyjny','PN-90/C-04516')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (334,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci siarczanów w bezbarwnych roztworach metod¹ turbidynamiczn¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci siarczanów w bezbarwnych roztworach metod¹ turbidynamiczn¹. \ PN-68/C-04519','PN-82/C-04519')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (335,'1:Inwentarz ogólny',1,'Produkty chemiczne.Oznaczanie liczby bromowej.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','PN-85/C-04520.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (336,'1:Inwentarz ogólny',1,'Produkty chemiczne.Oznaczanie liczby bromowej metod¹ miareczkowania biamperometrycznego.','Polski  Komitet Normalizacyjny','Produkty chemiczne.Oznaczanie liczby bromowej metod¹ miareczkowania biamperometrycznego. \ PN-68/C-04520','PN-85/C-04520/03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (338,'1:Inwentarz ogólny',1,'Produkty chemiczne.Oznaczanie liczby bromowej metod¹ miareczkowania potencjometrycznego.','Polski  Komitet Normalizacyjny','PN-86/C-04520.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (339,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza.Postanowienia ogólne i zakres normy. \ PN-75/C-04521.00','PN-81/C-04521.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (340,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem batofenantroliny.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem batofenantroliny. \ PN-75/C-04521.01','PN-81/C-04521.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (342,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem 2,2-dwupirydylu.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem 2,2-dwupirydylu. \ PN-75/C-04521.02','PN-81/C-04521.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (343,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem tiocyjanianu (rodanku) amonowego.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem tiocyjanianu (rodanku) amonowego. \ PN-75/C-04521.03','PN-81/C-04521.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (344,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem 1,10-fenantroliny.','Polski  Komitet Normalizacyjny','PN-81/C-04521.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (345,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie zawartoœci ¿elaza metod¹ kolorymetryczn¹ z zastosowaniem kwasu sulfosalicylowego.','Polski  Komitet Normalizacyjny','PN-81/C-04521.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (346,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci kwasu krzemowego w bezbarwnych roztworach metod¹ kolorymetryczn¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci kwasu krzemowego w bezbarwnych roztworach metod¹ kolorymetryczn¹. \ PN-68/C-04522','PN-82/C-04522')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (347,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci amonu.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci amonu. \ PN-68/C-04525','PN-81/C-04525')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (349,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie azotu ogólnego metod¹ destylacyjn¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie azotu ogólnego metod¹ destylacyjn¹. \ PN-68/C-04527','PN-81/C-04527')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (350,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie fosforanów metod¹ miareczkow¹ chino-linowo-molibdenianow¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie fosforanów metod¹ miareczkow¹ chino-linowo-molibdenianow¹. \ PN-75/C-04528','PN-90/C-04528')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (351,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie krzemu metod¹ wagow¹.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie krzemu metod¹ wagow¹. \ PN-58/C-04529','PN-90/C-04529')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (352,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie titranów(roztworów mianowanych).Postanowienia ogólne,okreœlenia i zakres normy.','Polski  Komitet Normalizacyjny','PN-81/C-04530.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (353,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie titranów(roztworów mianowanych).Roztwory stosowane w miareczkowaniach kwas-zasada(alikacymetrycznych)','Polski  Komitet Normalizacyjny','PN-81/C-04530.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (354,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie titranów(roztworów mianowanych).Roztwory stosowane w miareczkowaniach utleniaj¹co-redukuj¹cych(redoks)','Polski  Komitet Normalizacyjny','PN-81/C-04530.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (355,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie titranów (roztworów mianowanych).Roztwory stosowane w miareczkowaniach str¹ceniowych.','Polski  Komitet Normalizacyjny','PN-81/C-04530.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (356,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie titranów(roztworów mianowanych)i rozpuszczalników.','Polski  Komitet Normalizacyjny','PN-92/C-04530.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (357,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci fluoru w produktach nieorganicznych.Postanowienia ogólne i zakres.','Polski  Komitet Normalizacyjny','PN-79/C-04531.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (358,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci fluoru w produktach nieorganicznych metod¹ miareczkow¹.','Polski  Komitet Normalizacyjny','PN-79/C-04531.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (359,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci fluoru w produktach nieorganicznych met. fotokolorymetryczn¹.','Polski  Komitet Normalizacyjny','PN-79/C-04531.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (361,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci fluoru w prod. nieorg. metod¹ potencjom. z zastosow. jednoselekt. elektrody.','Polski  Komitet Normalizacyjny','PN-79/C-04531.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (362,'1:Inwentarz ogólny',1,'Oznaczanie gêstoœci nasypowej.','Polski  Komitet Normalizacyjny','PN-80/C-04532')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (363,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie barwy produktów chemicznych.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','PN-81/C-04534.00')
GO
insert into Normy (Id_norma,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (364,1,'Analiza chemiczna.Oznaczanie barwy produktów chemicznych za pomoc¹ skali Hazena(skala platynowo-kobaltowa)','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie barwy produktów chemicznych za pomoc¹ skali Hazena(skala platynowo-kobaltowa) \ BN-70/6020-02','PN-81/C-04534.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (365,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie barwy, produktów chemicznych za pomoc¹ skali jodowej.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie barwy, produktów chemicznych za pomoc¹ skali jodowej. \ PN-82/C-04534.02','PN-84/C-04534.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (366,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie zabarwienia produktów chemicznych z kwasem siarkowym za pomoc¹ skali dwuchromianowej.','Polski  Komitet Normalizacyjny','PN-82/C-04534.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (367,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie barwy produktów chemicznych za pomoc¹ skali miedziano-¿elazowo-kabaltowo-dwuchromianowej.','Polski  Komitet Normalizacyjny','PN-82/C-04534.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (368,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie barwy produktów chemicznych wed³ug skali Gardnera.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie barwy produktów chemicznych wed³ug skali Gardnera. \ BN-79/6110-37','PN-86/C-04534.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (369,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie liczby nadmanganianowej oraz zu¿ycia nadmanganianu potasowego.','Polski  Komitet Normalizacyjny','PN-86/C-04535')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (370,'1:Inwentarz ogólny',1,'Odczynnki.Oznaczanie ma³ych zawartoœci azotynów.','Polski  Komitet Normalizacyjny','PN-86/C-04536')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (371,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci miedzi.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie ma³ych zawartoœci miedzi. \ PN-68/C-04538','PN-80/C-04538')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (372,'1:Inwentarz ogólny',1,'Rozpuszczalniki i rozcieñczalniki lakiernicze.Metody badañ.','Polski  Komitet Normalizacyjny','Rozpuszczalniki i rozcieñczalniki lakiernicze.Metody badañ. \ PN-62/C-04539','PN-76/C-04539')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (373,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Postanowienia ogólne i zakres normy. \ PN-74/C-04540.00','PN-90/C-04540.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (374,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH wód i œcieków o przewodnoœci elektrolitycznej w³aœciwej 10uS/cm','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH wód i œcieków o przewodnoœci elektrolitycznej w³aœciwej 10uS/cm \ PN-74/C-04540.01','PN-90/C-04540.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (375,'1:Inwentarz ogólny',1,'norma zast¹piona czêœciowo przez PN-EN ISO 9963-1:2001','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania potencjometrycznego.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania potencjometrycznego. \ PN-74/C-04540.01','PN-90/C-04540.02+ Az1:2003')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (376,'1:Inwentarz ogólny',1,'norma czêœciowo zast¹piona przez PN-EN ISO 9963-1:2001','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania wobec wska¿ników.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie kwasowoœci i zasadowoœci mineralnej i ogólnej metod¹ miareczkowania wobec wska¿ników. \ PN-74/C-04540.03','PN-90/C-04540.03+Az1:2003')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (377,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci ogónej w œciekach zawieraj¹cych du¿e iloœci ¿elaza i glinu.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci ogónej w œciekach zawieraj¹cych du¿e iloœci ¿elaza i glinu. \ PN-75/C-04540.04','PN-91/C-04540.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (378,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci mineralnej i ogólnej w osadach...','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania pH,kwasowoœci i zasadowoœci.Oznaczanie pH,kwasowoœci i zasadowoœci mineralnej i ogólnej w osadach... \ PN-75/C-04540.05','PN-91/C-04540.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (380,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci i zapotrzebowania ozonu.Oznaczanie ozonu w wodzie metod¹ kolorymetryczn¹ z kompleksem.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci i zapotrzebowania ozonu.Oznaczanie ozonu w wodzie metod¹ kolorymetryczn¹ z kompleksem. \ BN-70/6212-12','PN-80/C-04543.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (381,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci wielopierœcieniowych wêglowodorów aromatycznych.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci wielopierœcieniowych wêglowodorów aromatycznych. \ PN-80/C-04544.01','PN-87/C-04544.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (382,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci wielopierœcieniowych wêglowodorów aromatycznych (WWA)','Polski  Komitet Normalizacyjny','PN-87/C-04544.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (383,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci rtêci.Oznaczanie rtêci metod¹ miareczkowania tiofluorescein¹.','Polski  Komitet Normalizacyjny','PN-82/C-04546.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (385,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci dwutlenku wêgla.Oznaczanie agresywnego dwutlenku wêgla w wodzie.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci dwutlenku wêgla.Oznaczanie agresywnego dwutlenku wêgla w wodzie. \ PN-57/C-04598','PN-74/C-04547.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (386,'1:Inwentarz ogólny',1,'Woda i œcieki.Badanie zawartoœci dwutlenku wêgla.','Polski  Komitet Normalizacyjny','PN-79/C-04547.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (387,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci syntet.subs.powierzchniowo czynnych oraz ich biochemicznego utleniania.Oznaczanie anionowych syntet.subs. powierzch.czynnych metod¹ miareczkow¹','Polski  Komitet Normalizacyjny','PN-85/C-04550.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (388,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci syntet. subs. powierzch. czynnych oraz ich biochem.utleniania.Oznaczanie kationowych syntet.subst.powierzch.czynnych metod¹ miareczkow¹.','Polski  Komitet Normalizacyjny','PN-85/C-04550.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (389,'1:Inwentarz ogólny',1,'Produkty chemiczne.Oznaczanie suchej pozosta³oœci.','Polski  Komitet Normalizacyjny','PN-88/C-04552')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (390,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci kadmu.Oznaczanie kadmu metod¹ ditizonow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci kadmu.Oznaczanie kadmu metod¹ ditizonow¹. \ PN-79/C-04560.01','PN-91/C-04560.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (391,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci kadmu.Oznaczanie kadmu w zakresie stê¿eñ 0,02+ 10,0 mg/dm3 metod¹ polarografii.','Polski  Komitet Normalizacyjny','PN-81/C-04560.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (392,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci kadmu.Oznaczanie kadmu metod¹ woltamperometryczn¹.','Polski  Komitet Normalizacyjny','PN-91/C-04560.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (393,'1:Inwentarz ogólny',1,'Woda i œcieki.Oznaczanie zawartoœci molibdenu metod¹ kolorymetryczn¹ z toluenu-3,4-ditiolem.','Polski  Komitet Normalizacyjny','Woda i œcieki.Oznaczanie zawartoœci molibdenu metod¹ kolorymetryczn¹ z toluenu-3,4-ditiolem. \ PN-79/C-04564.00; Woda i œcieki.Oznaczanie zawartoœci molibdenu metod¹ kolorymetryczn¹ z toluenu-3,4-ditiolem. \ PN-79/C--04564.01','PN-92/C-04564')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (394,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci siarki i jej zwi¹zków.Oznaczanie sumy siarkowodoru i siarczków rozpuszczalnych z u¿yciem elektrody jonoselektywnej.','Polski  Komitet Normalizacyjny','PN-81/C-04566.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (395,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci siarki i jej zwi¹zków.Oznaczanie siarczanów metod¹ turbidymetryczn¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci siarki i jej zwi¹zków.Oznaczanie siarczanów metod¹ turbidymetryczn¹. \ PN-74/C-04566.10','PN-79/C-04566.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (396,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci krzemionki.Oznaczanie krzemionki ogólnej zdysopcjowanej i niezdysocjowanej...','Polski  Komitet Normalizacyjny','PN-89/C-04567.09')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (397,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie cynku miedzi, o³owiu, kadmu..','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie cynku miedzi, o³owiu, kadmu.. \ PN-81/C-04570.02','PN-92/C-04570.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (398,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie baru  w  wodzie.','Polski  Komitet Normalizacyjny','PN-82/C-04570.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (399,'1:Inwentarz ogólny',1,'Woda i œcieki.Badanie zawartoœci metali metod¹ apsorp. spektrometrii atomowej.Oznaczanie miedzi,o³owiu,kadmu,niklu i kobaltu w wodzie zaw.¿elazo w il. wiêkszych ni¿ 5 mg/l...','Polski  Komitet Normalizacyjny','PN-85/C-04570.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (400,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie chromu ogólnego w wodzie z zastosowaniem  wstêpnego zagêszcz.metod¹ chelatowania i ekstrakcji.','Polski  Komitet Normalizacyjny','PN-87/C-04570.07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (401,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci metali metod¹ absorpcyjnej spektrometrii atomowej.Oznaczanie chromu szeœciowartoœciowego oraz trójwartoœciowego.','Polski  Komitet Normalizacyjny','PN-87/C-04570.09')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (402,'1:Inwentarz ogólny',1,'Badania zawartoœci metali metod¹ absorpcyjnej spektromertii atomowej.Oznaczanie miedzi, o³owiu,kadmu,niklu i kobaltu w...','Polski  Komitet Normalizacyjny','PN-88/C-04570.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (403,'1:Inwentarz ogólny',1,'Woda i œcieki.Oznaczanie zawartoœci srebra.','Polski  Komitet Normalizacyjny','Woda i œcieki.Oznaczanie zawartoœci srebra. \ PN-74/C-04571','PN-93/C-04571')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (405,'1:Inwentarz ogólny',1,'Woda i œcieki.Oznaczania zawartoœci rozpuszczonych zwi¹zków organicznych w wodzie metod¹ spektrofotometrii w nadfiolecie.','Polski  Komitet Normalizacyjny','PN-84/C-04572')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (406,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci subs.ekstrahuj¹cych siê rozpuszczalnikami organ.Oznaczanie ca³kowitej zawart.sub.organ.ekstrahuj¹cych siê eterem.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci subs.ekstrahuj¹cych siê rozpuszczalnikami organ.Oznaczanie ca³kowitej zawart.sub.organ.ekstrahuj¹cych siê eterem. \ PN-78/C-04573.01','PN-86/C-04573.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (407,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci subst. ekstrahuj¹cych siê rozpuszczalnikami organicznymi.Oznaczanie ca³kowitej...','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci subst. ekstrahuj¹cych siê rozpuszczalnikami organicznymi.Oznaczanie ca³kowitej... \ PN-82/C-04573.03','PN-88/C-04573.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (408,'1:Inwentarz ogólny',1,'Woda i œcieki.Oznaczanie zawartoœci antymonu metod¹ kolorymetryczn¹ z rodamin¹ B.','Polski  Komitet Normalizacyjny','Woda i œcieki.Oznaczanie zawartoœci antymonu metod¹ kolorymetryczn¹ z rodamin¹ B. \ PN-75/C-04574','PN-91/C-04574')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (409,'1:Inwentarz ogólny',1,'Woda i œcieki.Oznaczanie zawartoœci litu metod¹ fotometrii p³omiennej.','Polski  Komitet Normalizacyjny','PN-84/C-04575')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (410,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu amonowego metod¹ potencjometryczn¹.','Polski  Komitet Normalizacyjny','PN-80/C-04576.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (412,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu azotanowego metod¹ kolorymetryczn¹ po redukcji w kolumnie kadmowej.','Polski  Komitet Normalizacyjny','PN-87/C-04576.07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (413,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu azotanowego metod¹ kolorymetryczn¹ z salicylanem sodowym.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu azotanowego metod¹ kolorymetryczn¹ z salicylanem sodowym. \ PN-73/C-04576.08','PN-82/C-04576.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (414,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu azotanowego metod¹ potencjometryczn¹ z u¿yciem elektrody jonoselektywnej.','Polski  Komitet Normalizacyjny','PN-86/C-04576.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (416,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu organicznego w osadach œcieków.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci zwi¹zków azotu.Oznaczanie azotu organicznego w osadach œcieków. \ BN-70/6215-38','PN-75/C-04576.16')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (417,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci wêglowodorów aromatycznych.Oznaczanie benzenu,toluenu,m-ksylenu i p-ksylenu,o-ksylenu oraz styrenu metod¹ chromatografii gazowej.','Polski  Komitet Normalizacyjny','PN-85/C-04577')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (418,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zapotrzebowania tlenu i zawartoœci wêgla organicznego.Oznaczanie chemicznego zapotrzebowania tlenu (ChZT) metod¹ dwuchromianow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zapotrzebowania tlenu i zawartoœci wêgla organicznego.Oznaczanie chemicznego zapotrzebowania tlenu (ChZT) metod¹ dwuchromianow¹. \ BN-66/6215-28; Woda i œcieki.Badania zapotrzebowania tlenu i zawartoœci wêgla organicznego.Oznaczanie','PN-74/C-04578.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (419,'1:Inwentarz ogólny',1,'Woda i œcieki.Woda stosowana do celów analitycznych w laboratoriach wodno-œciekowych.Wymagania jakoœciowe i metody badañ.','Polski  Komitet Normalizacyjny','Woda i œcieki.Woda stosowana do celów analitycznych w laboratoriach wodno-œciekowych.Wymagania jakoœciowe i metody badañ. \ BN-71/6191-95','PN-85/C-04585')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (421,'1:Inwentarz ogólny',1,'Woda i œcieki.Badanie zawartoœci ¿elaza...','Polski  Komitet Normalizacyjny','Woda i œcieki.Badanie zawartoœci ¿elaza... \ PN-73/C-04586.02','PN-90/C-04586.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (422,'1:Inwentarz ogólny',1,'zmiana Az1:2003','Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza ogólnego rozpuszczonego metod¹  spektrofotometryczn¹ z sol¹ dwusodow¹ kwasu batofenantrolinodwusulfonowego.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza ogólnego rozpuszczonego metod¹  spektrofotometryczn¹ z sol¹ dwusodow¹ kwasu batofenantrolinodwusulfonowego. \ PN-73/C-04586.04','PN-90/C-04586.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (423,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza metod¹ wersenianow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci ¿elaza.Oznaczanie ¿elaza metod¹ wersenianow¹. \ PN-73/C-04586.05','PN-93/C-04586.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (424,'1:Inwentarz ogólny',1,'Woda i œcieki.Badanie zawartoœci zwi¹zków fluoru.','Polski  Komitet Normalizacyjny','PN-79/C-04588.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (425,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci manganu.Postanowienia ogólne.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci manganu.Postanowienia ogólne. \ PN-75/C-04590.00','PN-92/C-04590.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (426,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci manganu.Oznaczanie manganu metod¹ nadmanganianow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci manganu.Oznaczanie manganu metod¹ nadmanganianow¹. \ PN-75/C-04590.01','PN-92/C-04590.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (427,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci manganu metod¹ formaldoksymow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci manganu metod¹ formaldoksymow¹. \ PN-84/C-04590.02','PN-92/C-04590.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (428,'1:Inwentarz ogólny',1,'Woda i i œcieki.Badania zawartoœci o³owiu.Oznaczanie o³owiu metod¹ ditizonow¹.','Polski  Komitet Normalizacyjny','Woda i i œcieki.Badania zawartoœci o³owiu.Oznaczanie o³owiu metod¹ ditizonow¹. \ PN-79/C-04595.02','PN-90/C-04595.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (429,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci cynku.Oznaczanie cynku metod¹ ditizonow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci cynku.Oznaczanie cynku metod¹ ditizonow¹. \ PN-79/C-04596.01','PN-90/C-04596.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (430,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci cynku metod¹ cynkonow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci cynku metod¹ cynkonow¹. \ PN-79/C-04596.02','PN-90/C-04596.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (431,'1:Inwentarz ogólny',1,'Badania zawartoœci chloru i jego zwi¹zków oraz zapotrzebowania chloru.Oznaczanie zazpotrzebowania chloru.','Polski  Komitet Normalizacyjny','Badania zawartoœci chloru i jego zwi¹zków oraz zapotrzebowania chloru.Oznaczanie zazpotrzebowania chloru. \ PN-75/C-04600.10','PN-89/C-04600.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (433,'1:Inwentarz ogólny',1,'Badanie zawartoœci fenoli.Oznaczanie fenolu, krezoli ksylenoli w wodzie metod¹ chromatografii gazowej.','Polski  Komitet Normalizacyjny','PN-89/C-04602.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (435,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Systemy zarz¹dzania bezpieczeñstwem i higien¹ pracy.Wytyczne auditowania.','Polski  Komitet Normalizacyjny','PN-N-18011:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (436,'1:Inwentarz ogólny',1,'Rury ze stali nierdzewnych.Wymiary,tolerancje i teoretyczne masy na jednostkê.','Polski  Komitet Normalizacyjny','Rury ze stali nierdzewnych.Wymiary,tolerancje i teoretyczne masy na jednostkê. \ EN ISO 1127:1996','PN-EN ISO 1127:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (437,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny4:Inwentarz ogólny5:Inwentarz ogólny6:Inwentarz ogólny7:Inwentarz ogólny8:Inwentarz ogólny9:Inwentarz ogólny10:Inwentarz ogólny',1,'Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia.','Polski  Komitet Normalizacyjny','Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia. \ PN-EN ISO 1101:2006(; Specyfikacje geometrii wyrobów (GPS).-Tolerancje geometryczne.- Tolerancje kszta³tu,kierunku,po³o¿enia i bicia. \ PN-8','PN-EN ISO 1101:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (438,'1:Inwentarz ogólny',1,'Odbiorniki radiofoniczne i telewizyjne i ich uzr¹dzenia dodatkowe.Charakterystyki odpornoœci.Poziomy dopuszczalne i metody pomiarów.','Polski  Komitet Normalizacyjny','Odbiorniki radiofoniczne i telewizyjne i ich uzr¹dzenia dodatkowe.Charakterystyki odpornoœci.Poziomy dopuszczalne i metody pomiarów. \ PN-EN 55020:2003(U); Odbiorniki radiofoniczne i telewizyjne i ich uzr¹dzenia dodatkowe.Charakterystyki odpornoœci.Pozio','PN-EN 55020:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (439,'1:Inwentarz ogólny',1,'Us³ugi t³umaczeniowe.Wymagania dotycz¹ce œwiadczenia us³ug.','Polski  Komitet Normalizacyjny','Us³ugi t³umaczeniowe.Wymagania dotycz¹ce œwiadczenia us³ug. \ PN-EN 15038:2006(U)','PN-EN 15038:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (440,'1:Inwentarz ogólny',1,'Rury i z³¹czki ze stali niestopowej do transportu wody i innych p³ynów wodnych.Warunki tachniczne dostawy.','Polski  Komitet Normalizacyjny','Rury i z³¹czki ze stali niestopowej do transportu wody i innych p³ynów wodnych.Warunki tachniczne dostawy. \ PN-EN 10224:2004; Rury i z³¹czki ze stali niestopowej do transportu wody i innych p³ynów wodnych.Warunki tachniczne dostawy. \ PN-EN 10224:2004/A','PN-EN 10224:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (442,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Tworzywa sztuczne.P³yty z poliwêglanu.Typy,wymiary i charakterystyka.','Polski  Komitet Normalizacyjny','PN-EN ISO 11963:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (443,'1:Inwentarz ogólny',1,'Szk³o w budownictwie.Szyby ochronne.Badania i klasyfikacja odpornoœci na rêczny atak.','Polski  Komitet Normalizacyjny','PN-EN 356:2000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (444,'1:Inwentarz ogólny',1,'Rury ze stali nierdzewnych.Wymiary,tolerancje i teoretyczne masy na jednostkê d³ugoœci.','Polski  Komitet Normalizacyjny','PN-ISO 1127:1996')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (445,'1:Inwentarz ogólny',1,'Jakoœæ powietrza.Definicje frakcji py³u stosowane przy pobieraniu próbek do oceny zagro¿enia zdrowia.','Polski  Komitet Normalizacyjny','PN-ISO 7708:2001')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (446,'1:Inwentarz ogólny',1,'Powietrze na stanowiskach pracy.Terminologia.','Polski  Komitet Normalizacyjny','Powietrze na stanowiskach pracy.Terminologia. \ PN-EN 1540:2002(U)','PN-EN 1540:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (447,'1:Inwentarz ogólny',1,'Ocena zgodnoœci.Wymagania ogólne dla jednostek akredytuj¹cych prowadz¹cych akredytacjê jednostek oceniaj¹cych zgodnoœæ.','Polski  Komitet Normalizacyjny','Ocena zgodnoœci.Wymagania ogólne dla jednostek akredytuj¹cych prowadz¹cych akredytacjê jednostek oceniaj¹cych zgodnoœæ. \ PN-EN ISO/IEC 17011:; Ocena zgodnoœci.Wymagania ogólne dla jednostek akredytuj¹cych prowadz¹cych akredytacjê jednostek oceniaj¹cych','PN-EN ISO/IEC 17011:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (448,'1:Inwentarz ogólny',1,'Bezpieczeñstwo maszyn.Sta³e œrodki dostêpu do maszyn.Czêœæ 4: Drabiny sta³e.','Polski  Komitet Normalizacyjny','Bezpieczeñstwo maszyn.Sta³e œrodki dostêpu do maszyn.Czêœæ 4: Drabiny sta³e. \ PN-EN ISO 14122-4:20; Bezpieczeñstwo maszyn.Sta³e œrodki dostêpu do maszyn.Czêœæ 4: Drabiny sta³e. \ PN-80/M-49060','PN-EN ISO 14122-4:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (449,'1:Inwentarz ogólny',1,'Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia z aluminium stopowego, stopów wstêpnych i odlewów.Czêœæ 2: System oznaczeñ na podstawie symboli chemicznych.','Polski  Komitet Normalizacyjny','Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia z aluminium stopowego, stopów wstêpnych i odlewów.Czêœæ 2: System oznaczeñ na podstawie symboli chemicznych. \ PN-EN 1780-2:2003(U); Aluminium i stopy aluminium.Oznaczenia g¹sek do przetopienia','PN-EN 1780-2:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (450,'1:Inwentarz ogólny',1,'Kleje.Ocena i przygotowanie próbek do badañ.','Polski  Komitet Normalizacyjny','Kleje.Ocena i przygotowanie próbek do badañ. \ PN-EN 1067:2006(U); Kleje.Ocena i przygotowanie próbek do badañ. \ PN-EN 1067:1999','PN-EN 1067:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (451,'1:Inwentarz ogólny',1,'Pomieszczenia i urz¹dzenia do przechowywania wartoœci.Klasyfikacja i metody badañ odpornoœci ogniowej.Czêœæ 1: Szafy na noœniki danych i wk³adki na dyskietki.','Polski  Komitet Normalizacyjny','Pomieszczenia i urz¹dzenia do przechowywania wartoœci.Klasyfikacja i metody badañ odpornoœci ogniowej.Czêœæ 1: Szafy na noœniki danych i wk³adki na dyskietki. \ PN-EN 1047-1:2006(U); Pomieszczenia i urz¹dzenia do przechowywania wartoœci.Klasyfikacja i me','PN-EN 1047-1:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (452,'1:Inwentarz ogólny',1,'Kleje.Oznaczanie umownej i sta³ej zawartoœci suchej substancji.','Polski  Komitet Normalizacyjny','Kleje.Oznaczanie umownej i sta³ej zawartoœci suchej substancji. \ PN-EN 827:2006(U); Kleje.Oznaczanie umownej i sta³ej zawartoœci suchej substancji. \ PN-EN 827:1996','PN-EN 827:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (453,'1:Inwentarz ogólny',1,'Ochrona czystoœci powietrz.Badania zawartoœci olejów.Czêœæ 6: Oznaczanie oleju mineralnego(faza ciek³a aerozolu) na stanowiskach pracy metod¹ spektrometrii absorpcyjnej w nadfiolecie.','Polski  Komitet Normalizacyjny','Ochrona czystoœci powietrz.Badania zawartoœci olejów.Czêœæ 6: Oznaczanie oleju mineralnego(faza ciek³a aerozolu) na stanowiskach pracy metod¹ spektrometrii absorpcyjnej w nadfiolecie. \ PN-80/Z-04108.02','PN-Z-04108-6:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (455,'1:Inwentarz ogólny',1,'Wyd. 1 (grudzieñ 2005)','Wymagania NATO dotycz¹ce planów jakoœci dla wyrobu bêd¹cego przedmiotem zamówienia.','Warszawa:Zak³ad systemów jakoœci i zarz¹dzania','AQAP 2105')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (456,'1:Inwentarz ogólny',1,'wyd.2 (listopad 2006)','Wymagania NATO dotycz¹ce zapewnienia jakoœci w projektowaniu, pracach rozwojowych i produkcji.','Zak³ad systemów jakoœci i zarz¹dzania','Wymagania NATO dotycz¹ce zapewnienia jakoœci w projektowaniu, pracach rozwojowych i produkcji. \ AQAP 2110 wyd.1','AQAP 2110')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (457,'1:Inwentarz ogólny',1,'Wyd.2 (listopad 2006)','Wymagania NATO dotycz¹ce zapewnienia jakoœci w kontroli i badaniach.','Zak³ad systemów jakoœci i zarz¹dzania','Wymagania NATO dotycz¹ce zapewnienia jakoœci w kontroli i badaniach. \ AQAP 2130 wyd.1','AQAP 2130')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (458,'1:Inwentarz ogólny',1,'Sprzêt do spawania gazowego.Wê¿e gumowe stosowane pzry spawaniu,ciêciu i procesach pokrewnych.','Polski  Komitet Normalizacyjny','Sprzêt do spawania gazowego.Wê¿e gumowe stosowane pzry spawaniu,ciêciu i procesach pokrewnych. \ PN-EN 559:1998','PN-EN 559:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (459,'1:Inwentarz ogólny',1,'Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje.','Polski  Komitet Normalizacyjny','Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje. \ PN-EN 10108:2005(U); Walcówka stalowa okr¹g³a do spêczania na zimno i wyciskania na zimno.Wymiary i tolerancje. \ PN-75/H-93200-03; Walcówka stalowa okr¹g³a do s','PN-EN 10108:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (460,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Metody wyznaczania strat i sprawnoœci na podstawie badañ (z wyj¹tkiem maszyn pojazdów trakcyjnych)','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Metody wyznaczania strat i sprawnoœci na podstawie badañ (z wyj¹tkiem maszyn pojazdów trakcyjnych) \ PN-89/E-06702','PN-EN 60034-2:2000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (461,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Czêœæ 5:Stopnie ochrony zapewniane przez rozwi¹zania konstrukcyjne maszyn elektrycznych wiruj¹cych (kod IP).Klasyfikacja.','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Czêœæ 5:Stopnie ochrony zapewniane przez rozwi¹zania konstrukcyjne maszyn elektrycznych wiruj¹cych (kod IP).Klasyfikacja. \ PN-EN 60034-5:2002(U','PN-EN 60034-5:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (462,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Sposoby ch³odzenia (kod IC)','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Sposoby ch³odzenia (kod IC) \ PN-IEC 34-6:1994','PN-EN 60034-6:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (463,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Czêœæ 7:Klasyfikacja form wykonania,sposobów monta¿u i umiejscowienia skrzynki zaciskowej (kod IM)','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Czêœæ 7:Klasyfikacja form wykonania,sposobów monta¿u i umiejscowienia skrzynki zaciskowej (kod IM) \ PN-EN 60034-7:1998; Maszyny elektryczne wiruj¹ce.Czêœæ 7:Klasyfikacja form wykonania,sposobów monta¿u i umiejscowienia skrzy','PN-EN 60034-7:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (464,'1:Inwentarz ogólny',1,'Przekszta³tniki pó³przewodnikowe.Czêœæ 2:Przekszta³tniki pó³przewodnikowe o komutacji wewnêtrznej z uwzglêdnieniem bezpoœrednich przekszta³tników pr¹du sta³ego.','Polski  Komitet Normalizacyjny','PN-EN 60146-2:2001')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (465,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Rozmiar obudowy od 56 do 400 i rozmiar ko³nierzy od 55 do 1080','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Rozmiar obudowy od 56 do 400 i rozmiar ko³nierzy od 55 do 1080 \ PN-90/E-06722','PN-IEC 72-1:1996')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (466,'1:Inwentarz ogólny',1,'Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Czêœæ 2:Rozmiary obudowy od 355 do 1000 i rozmiary ko³nierza od 1180 do 2360.','Polski  Komitet Normalizacyjny','Wymiary i ci¹gi mocy maszyn elektrycznych wiruj¹cych.Czêœæ 2:Rozmiary obudowy od 355 do 1000 i rozmiary ko³nierza od 1180 do 2360. \ PN-90/E-06723','PN-IEC 60072-2:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (467,'1:Inwentarz ogólny',1,'Urz¹dzenia elektroenergetyczne.Dobór silników elektrycznych i ich instalowanie.Ogólne wymagania i odbiór techniczny.','Polski  Komitet Normalizacyjny','Urz¹dzenia elektroenergetyczne.Dobór silników elektrycznych i ich instalowanie.Ogólne wymagania i odbiór techniczny. \ PN-89/E-05012','PN-89/E-05012')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (468,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Maszyny do sterowania.Silniki pr¹du sta³ego o magnesach trwa³ych.','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Maszyny do sterowania.Silniki pr¹du sta³ego o magnesach trwa³ych. \ BN-89/3016-01','PN-E-06835:1996')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (469,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Rodzaje i programy badañ.Postanowienia ogólne.','Polski  Komitet Normalizacyjny','PN-E-06755-1:2001')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (470,'1:Inwentarz ogólny',1,'Maszyny elektryczne wiruj¹ce.Wyznaczanie momentu bezw³adnoœci czêœci wiruj¹cych.','Polski  Komitet Normalizacyjny','Maszyny elektryczne wiruj¹ce.Wyznaczanie momentu bezw³adnoœci czêœci wiruj¹cych. \ PN-64/E-04252','PN-78/E-04252')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (471,'1:Inwentarz ogólny',1,'Identyfikacja.System identyfikacji radiolokacyjnej.Wymagania ogólne.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A047:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (472,'1:Inwentarz ogólny',1,'niejawna','Identyfikacja.Sysyem identyfikacji radiolokacyjnej.Dzia³anie w warunkach przeciwadzia³ania elektronicznego.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A048:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (473,'1:Inwentarz ogólny',1,'Identyfikacja.System identyfikacji radiolokacyjnej.Charakterystyki zainstalowanego systemu identyfikacji.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A049:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (474,'1:Inwentarz ogólny',1,'Identyfikacja.System identyfikacji radiolokacyjnej.charakterystyki techniczne modu S.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A050:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (475,'1:Inwentarz ogólny',1,'niejawna','Identyfikacja.System identyfikacji radiolokacyjnej.Charakterystyki techniczne systemu Mk XIIA.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A051:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (476,'1:Inwentarz ogólny',1,'niejawna','Identyfikacja.System identyfikacji radiolokacyjnej.Niejawne aspekty dzia³ania w modzie 5.','Wojskowe Centrum Normalizacji, Kodyfikacji i Jakoœci','NO-06-A052:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (477,'1:Inwentarz ogólny',1,'Technika informatyczna.Techniki bezpieczeñstwa.Praktyczne zasady zarz¹dzania bezpieczeñstwem infomacji.','Polski  Komitet Normalizacyjny','Technika informatyczna.Techniki bezpieczeñstwa.Praktyczne zasady zarz¹dzania bezpieczeñstwem infomacji. \ PN-ISO/IEC 17799:200','PN-ISO/IEC 17799:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (478,'1:Inwentarz ogólny',1,'Metale.Próba rozci¹gania.Czêœæ 1:Metoda badania w temperaturze otoczenia.','Polski  Komitet Normalizacyjny','Metale.Próba rozci¹gania.Czêœæ 1:Metoda badania w temperaturze otoczenia. \ PN-EN 10002-1:2002(U','PN-EN 10002-1:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (479,'1:Inwentarz ogólny',1,'Technika informatyczna.Techniki bezpieczeñstwa.Systemy zarz¹dzania bezpieczeñstwem informacji.Wymagania.','Polski  Komitet Normalizacyjny','Technika informatyczna.Techniki bezpieczeñstwa.Systemy zarz¹dzania bezpieczeñstwem informacji.Wymagania. \ PN-I-07799-2:2005','PN-ISO/IEC 27001:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (480,'1:Inwentarz ogólny',1,'Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej.','Polski  Komitet Normalizacyjny','Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej. \ PN-71/Z-04061/01; Ochrona czystoœci powietrza.Oznaczania kwasu octowego na stanowiskach pracy metod¹ chromatografii gazowej. \ PN-71/Z-04061/02;','PN-Z-04323:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (481,'1:Inwentarz ogólny',1,'wydanie 2 (listopad 2006)','Wymagania NATO dotycz¹ce zapewnienia jakoœci przy kontroli koñcowej.','Zak³ad systemów jakoœci i zarz¹dzania','AQAP 2131')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (482,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych,zwi¹zanych i ogólnych metod¹ kolorymetryczn¹ z kwasem barbiturowym i pirydyn¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych,zwi¹zanych i ogólnych metod¹ kolorymetryczn¹ z kwasem barbiturowym i pirydyn¹. \ PN-73/C-04603.01','PN-80/C-04603.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (483,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych zwi¹zanych i ogólnych metod¹ miareczkow¹,argenometryczn¹','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie cyjanków wolnych zwi¹zanych i ogólnych metod¹ miareczkow¹,argenometryczn¹ \ PN-73/C-04603.02','PN-82/C-04603.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (484,'1:Inwentarz ogólny',1,'zagubiona.','Woda i œcieki.Badania zawartoœci cyjanków.Oznaczanie chlorocyjanu w œciekach metod¹ kolorymetryczn¹ z kwasem nbarbiturowym i pirydyn¹.','Polski  Komitet Normalizacyjny','PN-82/C-04603.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (486,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci chromu.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci chromu.Postanowienia ogólne i zakres normy. \ PN-72/C-04604.01','PN-77/C-04604.00')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (487,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci chromu metod¹ kolorymetryczn¹ z dwufenylokarbazydem.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci chromu metod¹ kolorymetryczn¹ z dwufenylokarbazydem. \ PN-72/C-04604.02','PN-77/C-04604.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (488,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci chromu.Oznaczanie chromu szeœciowartoœciowego Cr 6+ i trójwartoœciowego Cr 3+','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci chromu.Oznaczanie chromu szeœciowartoœciowego Cr 6+ i trójwartoœciowego Cr 3+ \ PN-72/C-04604.08,; Woda i œcieki.Badania zawartoœci chromu.Oznaczanie chromu szeœciowartoœciowego Cr 6+ i trójwartoœciowego Cr 3+ \ PN-72/C-0','PN-77/C-04604.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (489,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci glinu.Postanowienia ogólne.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci glinu.Postanowienia ogólne. \ PN-76/C-04605.00','PN-92/C-04605.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (490,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ z eriochromocyjanin¹ R.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ z eriochromocyjanin¹ R. \ PN-76/C-04605.01','PN-92/C-04605.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (491,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ warsenianow¹.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci glinu.Oznaczanie glinu metod¹ warsenianow¹. \ PN-76/C-04605.03','PN-92/C-04605.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (492,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania toksycznoœci zanieczyszczeñ dla organizmów wodnych.Oznaczanie toksyczniœci ostrej na gupiku...','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania toksycznoœci zanieczyszczeñ dla organizmów wodnych.Oznaczanie toksyczniœci ostrej na gupiku... \ PN-72/C-04610.04','PN-90/C-46010.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (493,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania toksycznoœci zanieczyszczeñ dla organizmów wodnych.Oznaczanie toksycznoœci ostrej na kie³¿u...','Polski  Komitet Normalizacyjny','PN-89/C-04610.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (494,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci miedzi...','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci miedzi... \ PN-80/C-04611.02; Woda i œcieki.Badania zawartoœci miedzi... \ PN-72/C-04611.04','PN-C-04611-2:1994')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (495,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci niklu.Oznaczanie niklu metod¹ kolorymetryczn¹ z furylodwuoksymem.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci niklu.Oznaczanie niklu metod¹ kolorymetryczn¹ z furylodwuoksymem. \ PN-75/C-04614.01','PN-91/C-04614.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (496,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania mikrobiologiczne.Oznaczanie paciorkowców ka³owych metod¹ filtrów membranowych (FM) i metod¹ probówkow¹.','Polski  Komitet Normalizacyjny','PN-82/C-04615.25')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (497,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania mikrobiologiczne.Oznaczanie bakterii.Pseudomonas aeruginosa metod¹ hodowli na po¿ywkach p³ynnych.','Polski  Komitet Normalizacyjny','PN-81/C-04615.26')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (498,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania specjalne osadów.Oznaczanie aktywnoœci dehydrogenaz w osadzie czynnym metod¹ spektrofotometryczn¹ z TTC.','Polski  Komitet Normalizacyjny','PN-82/C-04616.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (499,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'zast¹piona czêœciowo przez PN-ISO 9297:1994
egz. 1 uniewa¿.','Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków w wodzie metod¹ argentometrycznego miareczkowania.','Polski  Komitet Normalizacyjny','Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków w wodzie metod¹ argentometrycznego miareczkowania. \ PN-69/C-04552; Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków w wodzie metod¹ argentometrycznego miareczkowania. \ PN-68/C-0','PN-75/C-04617.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (501,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci chlorków.Oznaczanie chlorków bezpoœredni¹ metod¹ potencjometryczn¹ z u¿yciem elektrody jonoselektywnej.','Polski  Komitet Normalizacyjny','PN-80/C-04617.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (502,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania podatnoœci na uzdatnianie.Oznaczanie zdolnoœci powstawania trójhalometanów (ZP-THM).','Polski  Komitet Normalizacyjny','PN-89/C-04619.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (503,'1:Inwentarz ogólny',1,'Woda i œcieki,Pobieranie próbek wody i pary z urz¹dzeñ energetycznych i ruroci¹gów do analizy fizycznej i chemicznej.','Polski  Komitet Normalizacyjny','Woda i œcieki,Pobieranie próbek wody i pary z urz¹dzeñ energetycznych i ruroci¹gów do analizy fizycznej i chemicznej. \ PN-74/C-04620.05; Woda i œcieki,Pobieranie próbek wody i pary z urz¹dzeñ energetycznych i ruroci¹gów do analizy fizycznej i chemicznej','PN-88/C-04621')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (504,'1:Inwentarz ogólny',1,'Woda i œcieki.Bilans jonowy wody.Sposób obliczania bilansu jonowego wody.','Polski  Komitet Normalizacyjny','PN-89/C-04638.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (505,'1:Inwentarz ogólny',1,'Woda i œcieki.Bilans jonowy wody.Analityczna kontrola bilansu jonowego w wodzie.','Polski  Komitet Normalizacyjny','PN-88/C-04638.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (506,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zanieczyszczeñ opadów atmosferycznych.Postanowienia ogólne.','Polski  Komitet Normalizacyjny','PN-91/C-04642.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (507,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zanieczyszczeñ opadów atmosferycznych.Oznaczanie jonów siarczanowych...','Polski  Komitet Normalizacyjny','PN-91/C-04642.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (508,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zanieczyszczeñ opadów atmosferycznych.Oznaczanie jonów amonowych metod¹...','Polski  Komitet Normalizacyjny','PN-91/C-04642.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (509,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zanieczyszczeñ opadów atmosferycznych.Oznaczanie sumy jonów azotanowych i azotynowych...','Polski  Komitet Normalizacyjny','PN-91/C-04642.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (510,'1:Inwentarz ogólny',1,'Barwienie,barwniki,pigmenty i rozjaœniacze optyczne.Terminologia.','Polski  Komitet Normalizacyjny','Barwienie,barwniki,pigmenty i rozjaœniacze optyczne.Terminologia. \ BN-77/6040-02; Barwienie,barwniki,pigmenty i rozjaœniacze optyczne.Terminologia. \ BN-85/6045-23','PN-92/C-04701')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (511,'1:Inwentarz ogólny',1,'Zdrowie i bezpieczeñstwo przy spawaniu i procesach pokrewnych.Metoda laboratoryjna pobierania próbek py³u i gazów powstaj¹cych podczas spawania ³ukowego.Czêœæ 2:Okreœlanie wielkoœci emisji gazów, z wyj¹tkiem ozonu.','Polski  Komitet Normalizacyjny','Zdrowie i bezpieczeñstwo przy spawaniu i procesach pokrewnych.Metoda laboratoryjna pobierania próbek py³u i gazów powstaj¹cych podczas spawania ³ukowego.Czêœæ 2:Okreœlanie wielkoœci emisji gazów, z wyj¹tkiem ozonu. \ PN-EN ISO 15011-2:20','PN-EN ISO 15011-2:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (512,'1:Inwentarz ogólny',1,'Przegl¹d projektu.','Polski  Komitet Normalizacyjny','Przegl¹d projektu. \ PN-EN 61160:2006(U)','PN-EN 61160:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (513,'1:Inwentarz ogólny',1,'Osprzêt po³¹czeniowy do obwodów niskiego napiêcia do u¿ytku domowego i podobnego.Czêœæ 2-3: Wymagania szczegó³owe dotycz¹ce samodzielnych z³¹czek z ostrzowymi elementami zaciskowymi.','Polski  Komitet Normalizacyjny','Osprzêt po³¹czeniowy do obwodów niskiego napiêcia do u¿ytku domowego i podobnego.Czêœæ 2-3: Wymagania szczegó³owe dotycz¹ce samodzielnych z³¹czek z ostrzowymi elementami zaciskowymi. \ PN-EN 60998-2-3:2005; Osprzêt po³¹czeniowy do obwodów niskiego napiêc','PN-EN 60998-2-3:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (514,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'Stale odporne na korozjê.Czêœæ 3:Warunki techniczne dostawy pó³fabrykatów,prêtów,walcówki,drutu,kszta³towników i wyrobów o powierzchni jasnej ze stali nierdzewnych ogólnego przeznaczenia.','Polski  Komitet Normalizacyjny','Stale odporne na korozjê.Czêœæ 3:Warunki techniczne dostawy pó³fabrykatów,prêtów,walcówki,drutu,kszta³towników i wyrobów o powierzchni jasnej ze stali nierdzewnych ogólnego przeznaczenia. \ PN-EN 10088-3:2005(U','PN-EN 10088-3:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (515,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Stale odporne na korozjê.Czêœæ 2: Warunki techniczne dostawy blach i taœm ze stali nierdzewnych ogólnego przeznaczenia.','Polski  Komitet Normalizacyjny','Stale odporne na korozjê.Czêœæ 2: Warunki techniczne dostawy blach i taœm ze stali nierdzewnych ogólnego przeznaczenia. \ PN-EN 10088-2:2005(U','PN-EN 10088-2:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (516,'1:Inwentarz ogólny',1,'Barwniki.Ogólne metody badañ.','Polski  Komitet Normalizacyjny','Barwniki.Ogólne metody badañ. \ PN-76/C-04702; Barwniki.Ogólne metody badañ. \ BN-81/6041-33; Barwniki.Ogólne metody badañ. \ BN-86/6044-14','PN-92/C--04702')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (517,'1:Inwentarz ogólny',1,'Barwniki.Barwniki zasadowe.Metody badañ.','Polski  Komitet Normalizacyjny','Barwniki.Barwniki zasadowe.Metody badañ. \ BN-74/6044-13','PN-92/C--04703')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (518,'1:Inwentarz ogólny',1,'Barwniki.Barwniki kwasowe do druku.Metody badañ.','Polski  Komitet Normalizacyjny','PN-92/C-04704')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (519,'1:Inwentarz ogólny',1,'Œrodki powierzchniowo czynne.Oznaczanie w³¹snoœci pianotwórczych.','Polski  Komitet Normalizacyjny','Œrodki powierzchniowo czynne.Oznaczanie w³¹snoœci pianotwórczych. \ PN-66/C-04801','PN-74/C-04801')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (520,'1:Inwentarz ogólny',1,'T³uszcze techniczne.Oznaczanie temperatury krzepniêcia t³uszczów i oznaczanie titru.','Polski  Komitet Normalizacyjny','PN-85/C-04831')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (521,'1:Inwentarz ogólny',1,'T³uszcze techniczne.Oznaczanie popio³u.','Polski  Komitet Normalizacyjny','PN-85/C-04832')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (522,'1:Inwentarz ogólny',1,'Œrodki ochrony drewna.Badanie agresywnoœci korozyjnej wobec stali metod¹ bezpoœredni¹.','Polski  Komitet Normalizacyjny','Œrodki ochrony drewna.Badanie agresywnoœci korozyjnej wobec stali metod¹ bezpoœredni¹. \ PN-74/C-04904','PN-87/C-04910')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (523,'1:Inwentarz ogólny',1,'Œrodki ochrony drewna przed dzia³aniem ognia.Badanie w³aœciwoœci ognioochronnych.','Polski  Komitet Normalizacyjny','PN-88/C-04911')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (524,'1:Inwentarz ogólny',1,'Analiza chemiczna.Kompleksometryczne metody oznaczania zawartoœci kationu g³ównego sk³adnika.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Kompleksometryczne metody oznaczania zawartoœci kationu g³ównego sk³adnika. \ PN-68/C-04950','PN-82/C-04950')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (526,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie skrêcalnoœci w³aœciwej produktów organicznych.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie skrêcalnoœci w³aœciwej produktów organicznych. \ PN-68/C-04951','PN-86/C-04951')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (528,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie ma³ych zawartoœci sodu, potasu, wapnia i strontu metod¹ fotometrii p³omieniowej.','Polski  Komitet Normalizacyjny','PN-88/C-04953')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (529,'1:Inwentarz ogólny',1,'Odczynniki.Oznaczanie pozosta³oœci nielotnej.','Polski  Komitet Normalizacyjny','Odczynniki.Oznaczanie pozosta³oœci nielotnej. \ PN-76/C-04957','PN-78/C-04957')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (530,'1:Inwentarz ogólny',1,'Odczynniki.Oznaczanie pozosta³oœci po pra¿eniu.','Polski  Komitet Normalizacyjny','Odczynniki.Oznaczanie pozosta³oœci po pra¿eniu. \ PN-76/C-04958','PN-78/C-04958')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (531,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Oznaczanie zawartoœci wody metod¹ Karola Fischera w produktach organicznych i nieorganicznych.','Polski  Komitet Normalizacyjny','Oznaczanie zawartoœci wody metod¹ Karola Fischera w produktach organicznych i nieorganicznych. \ PN-76/C-04959','PN-81/C-04959')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (532,'1:Inwentarz ogólny',1,'Analiza chemiczna.Chromatografia gazowa.Wytyczne ogólne opisu metody.','Polski  Komitet Normalizacyjny','PN-79/C-04960')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (533,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie zawartoœci wody w produktach organicznych metod¹ chromatografii gazowej.','Polski  Komitet Normalizacyjny','PN-77/C--04962')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (534,'1:Inwentarz ogólny',1,'Analiza chemiczna.Oznaczanie pH wodnych roztworów produktów chemicznych','Polski  Komitet Normalizacyjny','Analiza chemiczna.Oznaczanie pH wodnych roztworów produktów chemicznych \ PN-77/C-04963','PN--89/C-04963')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (535,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Odczynniki Oznaczanie zakresu pH zmiany barwy wska¿ników alkacymetrycznych.','Polski  Komitet Normalizacyjny','PN-77/C-04964')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (536,'1:Inwentarz ogólny',1,'Odczynniki.Metody oznaczania zawartoœci wody.','Polski  Komitet Normalizacyjny','PN-88/C-04970')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (537,'1:Inwentarz ogólny',1,'Woda i œcieki.Pobieranie próbek do badañ biologicznych.Pobieranie próbek fitoplanktonu.','Polski  Komitet Normalizacyjny','PN-86/C-05550.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (538,'1:Inwentarz ogólny',1,'Woda i œcieki.Pobieranie próbek do badañ biologicznych.Pobieranie próbek perifitonu.','Polski  Komitet Normalizacyjny','PN-86/C-05550.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (539,'1:Inwentarz ogólny',1,'Woda i œcieki.Badanie stopnia zanieczyszczenia wód rzecznych z zastosowaniem testu ciemnych i jasnych butelek.','Polski  Komitet Normalizacyjny','PN-88/C-05552')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (540,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania zawartoœci chlorofilu w wodach powierzchniowych.Ozn. chlorofilu w glonach...','Polski  Komitet Normalizacyjny','PN-86/C-05560.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (541,'1:Inwentarz ogólny',1,'Woda i œcieki.Badania tlenowej,biodegradacji zwi¹zków organicznych w œrodowisku wodnym w warunkach testu statycznego.','Polski  Komitet Normalizacyjny','PN-88/C-05561')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (542,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie odczynników i roztworów pomocniczych','Polski  Komitet Normalizacyjny','Analiza chemiczna.Przygotowanie odczynników i roztworów pomocniczych \ PN-81/C-06500','PN-89/C-06500')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (543,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie roztworów wska¿ników.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Przygotowanie roztworów wska¿ników. \ PN-76/C-06501','PN-81/C-06501')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (544,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie roztworów do kolorymetrii i nefelometrii','Polski  Komitet Normalizacyjny','Analiza chemiczna.Przygotowanie roztworów do kolorymetrii i nefelometrii \ PN-68/C-06500','PN-81/C-06503')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (545,'1:Inwentarz ogólny',1,'Analiza chemiczna.Przygotowanie roztworów buforowych.','Polski  Komitet Normalizacyjny','Analiza chemiczna.Przygotowanie roztworów buforowych. \ PN-76/C-06501','PN-81/C-06504')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (546,'1:Inwentarz ogólny',1,'Produkty chemiczne stosowane w przemyœle.Metoda ogólna oznaczania jonów chlorkowych.Metoda potencjometryczna.','Polski  Komitet Normalizacyjny','PN-93/C-07000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (547,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.P³uczki be³kotkowe typu Pole¿ajewa zmodyfikowane.','Polski  Komitet Normalizacyjny','PN-69/C-13046')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (548,'1:Inwentarz ogólny',1,'Szklany sprzêt laboratoryjny.P³uczki be³kotkowe ze szk³em spiekanym.','Polski  Komitet Normalizacyjny','PN-69/C-13048')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (549,'1:Inwentarz ogólny',1,'Siatki katalityczne platynowe i platynowo-rodowe.','Polski  Komitet Normalizacyjny','PN-74/C-18010')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (550,'1:Inwentarz ogólny',1,'Karbid.','Polski  Komitet Normalizacyjny','Karbid. \ PN-82/C-23050','PN-82/C-23050')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (551,'1:Inwentarz ogólny',1,'Gliceryna destylowana.','Polski  Komitet Normalizacyjny','Gliceryna destylowana. \ PN-57/C-24005','PN-76/C-24005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (552,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Wymagania i badania.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Wymagania i badania. \ PN-60/C-40006; P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Wymagania i badania. \ PN-75/C-40007','PN-C-40007:2000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (553,'1:Inwentarz ogólny',1,'P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pozosta³oœci po spopieleniu.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pozosta³oœci po spopieleniu. \ PN-60/C-40006; P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pozosta³oœci po spopieleniu. \ PN-75/C-40007','PN-92/C-40008.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (554,'1:Inwentarz ogólny',1,'P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury wrzenia.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury wrzenia. \ PN-75/C-40007','PN-92/C-40008.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (555,'1:Inwentarz ogólny',1,'P³yny noskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pH.','Polski  Komitet Normalizacyjny','P³yny noskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pH. \ PN-60/C-40006; P³yny noskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie pH. \ PN-75/C-40007','PN-92/C-40008.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (556,'1:Inwentarz ogólny',1,'P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie rezerwy alkalicznej.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie rezerwy alkalicznej. \ PN-75/C-40007','PN-93/C-40008.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (557,'1:Inwentarz ogólny',1,'zmiana Az1','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie sk³onnoœci do pienienia.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie sk³onnoœci do pienienia. \ PN-75/C-40007','PN-93/C-40008.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (558,'1:Inwentarz ogólny',1,'zmiana Az1','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Badanie w³aœciwoœci korozyjnych w naczyniu szklanym.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Badanie w³aœciwoœci korozyjnych w naczyniu szklanym. \ PN-75/C-40007','PN-93/C-40008.07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (559,'1:Inwentarz ogólny',1,'P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury krystalizacji.','Polski  Komitet Normalizacyjny','P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury krystalizacji. \ PN-75/C-40007; P³yny niskokrzepn¹ce do uk³adów ch³odzenia silników spalinowych.Oznaczanie temperatury krystalizacji. \ PN-60/C-40006','PN-93/C-40008.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (560,'1:Inwentarz ogólny',1,'Glikole etylenowe.Metody badañ.','Polski  Komitet Normalizacyjny','Glikole etylenowe.Metody badañ. \ PN-78/C-6020-03','PN-86/C-45050')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (561,'1:Inwentarz ogólny',1,'Wy¿sze alkohole t³uszczowe.Metody badañ.Oznaczanie liczby kwasowej,liczby zmydlenia i liczby estrowej.','Polski  Komitet Normalizacyjny','PN-86/C-45051.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (562,'1:Inwentarz ogólny',1,'Wy¿sze alkohole t³uszczowe.Metody badañ.Oznaczanie liczby karbonylowej metod¹ potencjometryczn¹.','Polski  Komitet Normalizacyjny','PN-86/C-45051.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (563,'1:Inwentarz ogólny',1,'Wy¿sze alkohole t³uszczowe.Metody badañ.Oznaczanie liczby jodowej.','Polski  Komitet Normalizacyjny','PN-92/C-45051.07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (564,'1:Inwentarz ogólny',1,'Wy¿sze alkohole t³uszczowe.Metody badañ.Oznaczanie liczby hydroksylowej.','Polski  Komitet Normalizacyjny','PN-93/C-45051.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (565,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Octan etylu technicznego.','Polski  Komitet Normalizacyjny','Octan etylu technicznego. \ BN-73/6026-61','PN-86/C-45100')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (566,'1:Inwentarz ogólny',1,'Wêglowodory aromatyczne.Metody badañ.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','PN-85/C-45300.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (567,'1:Inwentarz ogólny',1,'Wêglowodory aromatyczne.Metody badañ.Oznaczanie odczynu wyci¹gu wodnego.','Polski  Komitet Normalizacyjny','Wêglowodory aromatyczne.Metody badañ.Oznaczanie odczynu wyci¹gu wodnego. \ PN-74/C-97072','PN-85/C-45300.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (568,'1:Inwentarz ogólny',1,'Wêglowodory aromatyczne.Metody badañ.Oznaczanie intensywnoœci zabarwienia w próbie z kwasem siarkowym wg.wzorców dwuchromianowych.','Polski  Komitet Normalizacyjny','Wêglowodory aromatyczne.Metody badañ.Oznaczanie intensywnoœci zabarwienia w próbie z kwasem siarkowym wg.wzorców dwuchromianowych. \ PN-68/C-97062','PN-86/C-45300.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (569,'1:Inwentarz ogólny',1,'Wêglowodory aromatyczne.Metody badañ.Oznaczanie zanieczyszczeñ w benzenie metod¹ chromatografii gazowej i okreœlenie...','Polski  Komitet Normalizacyjny','PN-85/C-45300.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (570,'1:Inwentarz ogólny',1,'Wêglowodory aromatyczne.Metody badañ.Oznaczanie zawartoœci siarki metod¹ redukcji niklem Raney a.','Polski  Komitet Normalizacyjny','Wêglowodory aromatyczne.Metody badañ.Oznaczanie zawartoœci siarki metod¹ redukcji niklem Raney a. \ BN-80/0551-02','PN-85/C-45300.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (571,'1:Inwentarz ogólny',1,'Oznaczanie zanieczyszczeñ w toluenie metod¹ chromatografii gazowej i okreœlenie zawartoœci toluenu.','Polski  Komitet Normalizacyjny','PN-89/C-45300.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (572,'1:Inwentarz ogólny',1,'Technika wojskowa.In¿ynieria œrodowiskowa.Badania laboratoryjne.','Polski  Komitet Normalizacyjny','PN-V-04061:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (573,'1:Inwentarz ogólny',1,'Ocena zgodnoœci.Podstawy certyfikacji wyrobu.','Polski  Komitet Normalizacyjny','PKN-ISO/IEC Guide 67:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (574,'1:Inwentarz ogólny',1,'Guma i kauczuk termoplastyczny.Oznaczanie w³aœciwoœci wytrzyma³oœciowych przy rozci¹ganiu.','Polski  Komitet Normalizacyjny','Guma i kauczuk termoplastyczny.Oznaczanie w³aœciwoœci wytrzyma³oœciowych przy rozci¹ganiu. \ PN-ISO 37:1998','PN-ISO 37:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (575,'1:Inwentarz ogólny',1,'Materia³y dodatkowe do spawania.Druty elektrodowe i prêty do spawania aluminium i stopów aluminium.Klasyfikacja.','Polski  Komitet Normalizacyjny','Materia³y dodatkowe do spawania.Druty elektrodowe i prêty do spawania aluminium i stopów aluminium.Klasyfikacja. \ PN-EN ISO 18273:2005; Materia³y dodatkowe do spawania.Druty elektrodowe i prêty do spawania aluminium i stopów aluminium.Klasyfikacja. \ PN','PN-EN ISO 18273:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (576,'1:Inwentarz ogólny',1,'Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 2:Aluminium stopy aluminium.','Polski  Komitet Normalizacyjny','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 2:Aluminium stopy aluminium. \ PN-EN ISO 9606-2:200; Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 2:Aluminium stopy aluminium. \ PN-EN 287-2+A1:1998','PN-EN ISO 9606-2:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (577,'1:Inwentarz ogólny',1,'Urz¹dzenia elektryczne w przestrzeniach zagro¿inych wybuchem gazów.Czêœæ 0:Wymagania ogólne.','Polski  Komitet Normalizacyjny','Urz¹dzenia elektryczne w przestrzeniach zagro¿inych wybuchem gazów.Czêœæ 0:Wymagania ogólne. \ PN-EN 60079-0:2004(U; Urz¹dzenia elektryczne w przestrzeniach zagro¿inych wybuchem gazów.Czêœæ 0:Wymagania ogólne. \ PN-EN 50014:2004','PN-EN 60079-0:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (578,'1:Inwentarz ogólny',1,'Systemy oznaczania stali.Czêœæ 1:Znaki stali.','Polski  Komitet Normalizacyjny','Systemy oznaczania stali.Czêœæ 1:Znaki stali. \ PN-EN 10027-1:2005(U','PN-EN 10027-1:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (579,'1:Inwentarz ogólny2:Inwentarz ogólny2:Inwentarz ogólny',1,'Wyroby walcowane na gor¹co ze stali konstrukcyjnych .Czêœæ 1:Ogólne warunki techniczne dostawy.','Polski  Komitet Normalizacyjny','Wyroby walcowane na gor¹co ze stali konstrukcyjnych .Czêœæ 1:Ogólne warunki techniczne dostawy. \ PN-EN 10025-1:2005(U','PN-EN 10025-1:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (580,'1:Inwentarz ogólny',1,'Wyroby walcowane na gor¹co ze stali konstrukcyjnych.Czêœæ 2:Warunki techniczne dostawy stali konstrukcyjnych niestopowych.','Polski  Komitet Normalizacyjny','Wyroby walcowane na gor¹co ze stali konstrukcyjnych.Czêœæ 2:Warunki techniczne dostawy stali konstrukcyjnych niestopowych. \ PN-EN 10025-2:2005(U','PN-EN 10025-2:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (581,'1:Inwentarz ogólny',1,'Miêdzynarodowy s³ownik terminologiczny elektryki,.Czêœæ 826:Instalacje elektryczne.','Polski  Komitet Normalizacyjny','Miêdzynarodowy s³ownik terminologiczny elektryki,.Czêœæ 826:Instalacje elektryczne. \ PN-IEC 60050-826:200','PN-IEC 60050-826:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (582,'1:Inwentarz ogólny',1,'Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 1:Stale.','Polski  Komitet Normalizacyjny','Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 1:Stale. \ PN-EN 287-1:2005(U); Egzamin kwalifikacyjny spawaczy.Spawanie.Czêœæ 1:Stale. \ PN-EN 287-1:1998','PN-EN 287-1:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (583,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','PN-93/C-45301.01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (584,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie wska¿nika nadmanganianowego metod¹ spektrofotometryczn¹.','Polski  Komitet Normalizacyjny','PN-93/C-45301.02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (585,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie liczby nadmanganianowej 3-procentowego roztworu wodnego metod¹ wizualn¹.','Polski  Komitet Normalizacyjny','PN-93/C-45301.03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (586,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie barwy 50% roztworu wodnego kaprolaktamu.','Polski  Komitet Normalizacyjny','PN-93/C-45301.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (587,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie absorbancji przy d³ugoœci fali 290 nm.','Polski  Komitet Normalizacyjny','PN-93/C-45301.05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (588,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie zawartoœci lotnych zasad.','Polski  Komitet Normalizacyjny','PN-93/C-45301.06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (589,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie zawartoœci lotnych zasad metod¹ destylacji z par¹ wodn¹.','Polski  Komitet Normalizacyjny','PN-93/C-45301.07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (591,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie temperatury krystalizacji.','Polski  Komitet Normalizacyjny','PN-93/C-45301.08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (592,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie kwasowoœci lub alkalicznoœci.','Polski  Komitet Normalizacyjny','PN-93/C-45301.09')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (593,'1:Inwentarz ogólny',1,'Kaprolaktam.Metody badañ.Oznaczanie zawartoœci ¿elaza.','Polski  Komitet Normalizacyjny','PN-93/C-45301.10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (594,'1:Inwentarz ogólny',1,'Produkty chemiczne organiczne.Metody badañ. Oznaczanie zanieczyszczeñ w octanie butylu metod¹ chromatografii gazowej i obliczanie...','Polski  Komitet Normalizacyjny','PN-91/C-45400')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (595,'1:Inwentarz ogólny',1,'Próbniki do pobierania próbek produktów bezkszta³tnych.','Polski  Komitet Normalizacyjny','Próbniki do pobierania próbek produktów bezkszta³tnych. \ PN/C-60009; Próbniki do pobierania próbek produktów bezkszta³tnych. \ PN/C-60010','PN-74/C-60008')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (596,'1:Inwentarz ogólny',1,'Odczynniki i substancje specjalne czyste.Oznaczanie ma³ych zawartoœci pierwiastków metod¹ atomowej spektrometrii absorbcyjnej.','Polski  Komitet Normalizacyjny','PN-92/C-80000')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (597,'1:Inwentarz ogólny',1,'Odczynniki i substancje specjalne czyste.Pakowanie,przechowywanie i transport.','Polski  Komitet Normalizacyjny','Odczynniki i substancje specjalne czyste.Pakowanie,przechowywanie i transport. \ PN-87/C-80001','PN-C-80001:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (598,'1:Inwentarz ogólny',1,'Odczynniki i substancje specjalne czyste.Ogólne wytyczne pobierania próbek i przygotowania...','Polski  Komitet Normalizacyjny','Odczynniki i substancje specjalne czyste.Ogólne wytyczne pobierania próbek i przygotowania... \ PN-88/C-80047','PN-88/C-80047')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (599,'1:Inwentarz ogólny',1,'Biel cynkowa.','Polski  Komitet Normalizacyjny','Biel cynkowa. \ PN-72/C-81015','PN-88/C-81015')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (600,'1:Inwentarz ogólny',1,'Szpachlówki i kity szpachlowe.Metody badañ.','Polski  Komitet Normalizacyjny','PN-62/C-81502')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (601,'1:Inwentarz ogólny',1,'Oznaczanie pozosta³oœci na sicie w wyrobach lakierowych i farbach graficznych','Polski  Komitet Normalizacyjny','Oznaczanie pozosta³oœci na sicie w wyrobach lakierowych i farbach graficznych \ PN-75/C-81505; Oznaczanie pozosta³oœci na sicie w wyrobach lakierowych i farbach graficznych \ BN-65/7469-05','PN-81/C-81505')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (602,'1:Inwentarz ogólny',1,'Szpachlówki i kity szpachlowe.Oznaczanie konsystencji.','Polski  Komitet Normalizacyjny','PN-65/C-81506')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (603,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie rozlewnoœci.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie rozlewnoœci. \ PN-67/C-81507','PN-89/C-81507')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (605,'1:Inwentarz ogólny',1,'zast. czêœciowo przez PN-EN ISO 3251:1999','Wyroby lakierowe.Oznaczanie zawartoœci sk³adników podstawowych.','Polski  Komitet Normalizacyjny','Wyroby lakierowane.Oznaczanie zawartoœci sk³adników podstawowych. \ PN-79/C-81512','PN-84/C-81512')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (606,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Sposoby otrzymywania pow³ok do badañ.','Polski  Komitet Normalizacyjny','Wyroby lakierowane.Sposoby otrzymywania pow³ok do badañ. \ PN-70/C-81514','PN-79/C-81514')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (608,'1:Inwentarz ogólny',1,'zast.czêœciowo przez PN-ISO 7784-1:2000','Wyroby lakierowe.Oznaczanie œcieralnoœci pow³ok lakierowych.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie œcieralnoœci pow³ok lakierowych. \ PN-67/C-81516','PN-76/C-81516')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (609,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie porowatoœci pow³ok lakierowych.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie porowatoœci pow³ok lakierowych. \ PN-59/C-81518','PN-75/C-81518')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (610,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Okreœlanie stopnia wyschniêæ i czasu wysychania.','Polski  Komitet Normalizacyjny','Wtroby lakierowe.Okreœlanie stopnia wyschniêæ i czasu wysychania. \ PN-69/C-81519','PN-79/C-81519')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (612,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Badania odpornoœci pow³ok lakierowych na dzia³anie wody oraz oznaczanie nasi¹kliwoœci.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Badania odpornoœci pow³ok lakierowych na dzia³anie wody oraz oznaczanie nasi¹kliwoœci. \ PN-66/C-81521','PN-76/C-81521')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (613,'1:Inwentarz ogólny',1,'Konwersyjne pow³oki chromianowe na cynku, kadmie oraz stopach aluminium-cynk i cynk-aluminium.Metody badañ.','Polski  Komitet Normalizacyjny','Konwersyjne pow³oki chromianowe na cynku, kadmie oraz stopach aluminium-cynk i cynk-aluminium.Metody badañ. \ PN-EN ISO 3613:2002(','PN-EN ISO 3613:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (614,'1:Inwentarz ogólny',1,'Ochrona radiologiczna.Zamkniête ¿ród³a promieniotwórcze.Wymagania ogólne i klasyfikacja.','Polski  Komitet Normalizacyjny','Ochrona radioplogiczna.Zamkniête ¿ród³a promieniotwórcze.Wymagania ogólne i klasyfikacja. \ PN-86/J-02000','PN-ISO 2919:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (616,'1:Inwentarz ogólny',1,'Technika j¹drowa.Nazwy i okreœlenia.Transport materia³ów promieniotwórczych.','Polski  Komitet Normalizacyjny','Technika j¹drowa.Nazwy i okreœlenia.Transport materia³ów promieniotwórczych. \ PN-74/J-01003.13','PN-92/J-01003.13')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (617,'1:Inwentarz ogólny',1,'Technika j¹drowa.Nazwy i okreœlenia.¯ród³a promieniotwórcze.','Polski  Komitet Normalizacyjny','Technika j¹drowa.Nazwy i okreœlenia.¯ród³a promieniotwórcze. \ PN-73/J-01003.04','PN-84/J-01003.04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (618,'1:Inwentarz ogólny',1,'Materia³y i sprzêt ochronny przed promieniowniem X i gamma.Fartuchy ochronne.','Polski  Komitet Normalizacyjny','PN-60/J-80005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (619,'1:Inwentarz ogólny',1,'Technika j¹drowa.Magazyny materia³ów promieniotwórczych.Wymagania ochrony radiologicznej.','Polski  Komitet Normalizacyjny','PN-J-05000:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (620,'1:Inwentarz ogólny',1,'Ceowniki ekonomiczne stalowe walcowane na gor¹co.Wymiary.','Polski  Komitet Normalizacyjny','Ceowniki ekonomiczne stalowe walcowane na gor¹co.Wymiary. \ PN-71/H-93451','PN-H-93451:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (621,'1:Inwentarz ogólny',1,'Ciecze stosowane w elektrotechnice.Œwie¿e mineralne oleje elektroizolacyjne do transformatorów i aparatury ³¹czeniowej.','Polski  Komitet Normalizacyjny','Ciecze stosowane w elektrotechnice.Œwie¿e mineralne oleje elektroizolacyjne do transformatorów i aparatury ³¹czeniowej. \ PN-EN 60296:2005(U)','PN-EN 60296:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (622,'1:Inwentarz ogólny',1,'Opakowania.Wymagania dla taœm opasuj¹cych stalowych do opakowañ przeznaczonych do podnoszenia, mocowania i zabezpieczania ³adunków.','Polski  Komitet Normalizacyjny','Opakowania.Wymagania dla taœm opasuj¹cych stalowych do opakowañ przeznaczonych do podnoszenia, mocowania i zabezpieczania ³adunków. \ PN-EN 13247:2002(U)','PN-EN 13247:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (624,'1:Inwentarz ogólny',1,'Ochronniki s³uchu.Wymagania bezpieczeñstwa i badania.Czêœæ 7:Wk³adki przeciwha³asowe o regulowanym t³umieniu.','Polski  Komitet Normalizacyjny','Ochronniki s³uchu.Wymagania bezpieczeñstwa i badania.Czêœæ 7:Wk³adki przeciwha³asowe o regulowanym t³umieniu. \ PN-EN 352-7:2003(U)','PN-EN 352-7:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (625,'1:Inwentarz ogólny',1,'Elektroakustyka.Kalibratory akustyczne.','Polski  Komitet Normalizacyjny','Elektroakustyka.Kalibratory akustyczne. \ PN-EN 60942:2004(U)','PN-EN 60942:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (627,'1:Inwentarz ogólny',1,'Dokumentacja techniczna wyrobu.Pola danych w tabliczkach rysunkowych i nag³ówkach dokumentów','Polski  Komitet Normalizacyjny','Dokumentacja techniczna wyrobu.Pola danych w tabliczkach rysunkowych i nag³ówkach dokumentów \ PN-EN ISO 7200:2005(; Dokumentacja techniczna wyrobu.Pola danych w tabliczkach rysunkowych i nag³ówkach dokumentów \ PN-85/M-01119','PN-EN ISO 7200:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (628,'1:Inwentarz ogólny',1,'Malowanie maskuj¹ce uzbrojenia i sprzêtu wojskowego.Wymagania ogólne.','Ministerstwo Obrony Narodowej','Malowanie maskuj¹ce uzbrojenia i sprzêtu wojskowego.Wymagania ogólne. \ NO-10-A800:1998','NO-10-A800:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (629,'1:Inwentarz ogólny',1,'Ochrona wojskowego sprzêtu technicznego przed korozj¹ i starzeniem.Malowanie sprzêtu lotniczego.Wymagania ogólne i badania.','Ministerstwo Obrony Narodowej','Ochrona wojskowego sprzêtu technicznego przed korozj¹ i starzeniem.Malowanie sprzêtu lotniczego.Wymagania ogólne i badania. \ NO-17-A800:1998','NO-17-A800:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (630,'1:Inwentarz ogólny',1,'Sprzêt do wykrywania ska¿eñ chemicznych.Urz¹dzenia wielokrotnego u¿ytku do wykrywania lub pomiaru stê¿enia substancji chemicznych w powietrzu.Klasyfikacja.','Ministerstwo Obrony Narodowej','Sprzêt do wykrywania ska¿eñ chemicznych.Urz¹dzenia wielokrotnego u¿ytku do wykrywania lub pomiaru stê¿enia substancji chemicznych w powietrzu.Klasyfikacja. \ NO-42-A201:1998','NO-42-A201:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (631,'1:Inwentarz ogólny',1,'Bojowe œrodki truj¹ce.Wzorzec sarinu.Wymagania i badania.','Ministerstwo Obrony Narodowej','Bojowe œrodki truj¹ce.Wzorzec sarinu.Wymagania i badania. \ NO-68-A200:1998','NO-68-A200:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (632,'1:Inwentarz ogólny',1,'Zarz¹dzanie ryzykiem przedsiêwziêcia.Wytyczne stosowania.','Polski  Komitet Normalizacyjny','PN-IEC 62198:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Zastapione,Nr_normy) values  (633,'1:Inwentarz ogólny',1,'Bezpieczeñstwo urz¹dzeñ laserowych.Czêœæ 1: Klasyfikacja sprzêtu,wymagania i przewodnik u¿ytkownika.','Bezpieczeñstwo urz¹dzeñ laserowych.Czêœæ 1: Klasyfikacja sprzêtu,wymagania i przewodnik u¿ytkownika. \ PN-EN 60825-1:2000; Bezpieczeñstwo urz¹dzeñ laserowych.Czêœæ 1: Klasyfikacja sprzêtu,wymagania i przewodnik u¿ytkownika. \ PN-EN 60825-1:2000/A','PN-EN 60825-1:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (634,'1:Inwentarz ogólny',1,'Aluminium i stopy aluminium.P³yty ¿eberkowe.Specyfikacje.','Polski  Komitet Normalizacyjny','Aluminium i stopy aluminium.P³yty ¿eberkowe.Specyfikacje. \ PN-93/H-92748','PN-EN 1386:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (635,'1:Inwentarz ogólny',1,'Tworzywa sztuczne.Zwi¹zki epoksydowe.Oznaczanie równowa¿nika epoksydowego.','Polski  Komitet Normalizacyjny','PN-EN ISO 3001:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (636,'1:Inwentarz ogólny',1,'Badanie zagro¿enia ogniowego.Czêœæ 1-3-:Wytyczne oceny zagro¿enia ogniowego wyrobów elektrotechnicznych .Stosowanie procedur doboru wstêpnego.','Polski  Komitet Normalizacyjny','Badanie zagro¿enia ogniowego.Czêœæ 1-3-:Wytyczne oceny zagro¿enia ogniowego wyrobów elektrotechnicznych .Stosowanie procedur doboru wstêpnego. \ PN-89/E-04614/07; Badanie zagro¿enia ogniowego.Czêœæ 1-3-:Wytyczne oceny zagro¿enia ogniowego wyrobów elektro','PN-EN 60695-1-30:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (637,'1:Inwentarz ogólny',1,'Kompatybilnoœæ elektromagnetyczna (EMC)Czêœæ 3-2:Poziomy dopuszczalne emisji harmonicznych pr¹du(fazowy pr¹d zasilaj¹cy odbiornika < 16A)','Polski  Komitet Normalizacyjny','Kompatybilnoœæ elektromagnetyczna (EMC)Czêœæ 3-2:Poziomy dopuszczalne emisji harmonicznych pr¹du(fazowy pr¹d zasilaj¹cy odbiornika < 16A) \ PN-EN 61000-3-2:2006','PN-EN 61000-3-2:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (638,'1:Inwentarz ogólny',1,'Systemy alarmowe.Systemy kontroli dostêpu w zastosowaniach dotycz¹cych zabezpieczenia.Czêœæ 1:Wymagania systemowe.','Polski  Komitet Normalizacyjny','Systemy alarmowe.Systemy kontroli dostêpu w zastosowaniach dotycz¹cych zabezpieczenia.Czêœæ 1:Wymagania systemowe. \ PN-EN 50133-1:2000','PN-EN 50133-1:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (639,'1:Inwentarz ogólny',1,'Jakoœæ wody.Oznaczanie indeksu chemocznego zapotrzebowania tlenu (SP-ChZT).Metoda zminiaturyzowana z zastosowaniem szczelnych probówek.','Polski  Komitet Normalizacyjny','PN-ISO 15705:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (640,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce planów jakoœci.','Polski  Komitet Normalizacyjny','Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce planów jakoœci. \ PN-ISO 10005:1998','PN-ISO 10005:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (641,'1:Inwentarz ogólny',1,'Kszta³towniki zamkniête wykonane na gor¹co ze stali konstrukcyjnych niestopowych i drobnoziarnistych.Czêœæ 1: Warunki techniczne dostawy','Polski  Komitet Normalizacyjny','Kszta³towniki zamkniête wykonane na gor¹co ze stali konstrukcyjnych niestopowych i drobnoziarnistych.Czêœæ 1: Warunki techniczne dostawy \ PN-EN 10210-1:2006(U','PN-EN 10210-1:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (642,'1:Inwentarz ogólny',1,'Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce zarz¹dzania jakoœci¹ w pzredsiêwziêciach.','Polski  Komitet Normalizacyjny','Systemy zarz¹dzania jakoœci¹.Wytyczne dotycz¹ce zarz¹dzania jakoœci¹ w pzredsiêwziêciach. \ PN-ISO 10006:2002','PN-ISO 10006:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (643,'1:Inwentarz ogólny2:Inwentarz ogólny3:Inwentarz ogólny',1,'Dopuszczalnoœæ zespo³ów elektrycznych.','IPC','Dopuszczlnoœæ zespo³ów elektrycznych. \ IPC-A-610PL:2000','IPC-A-610PL:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (644,'1:Inwentarz ogólny',1,'Test Methods.','IPC','IPC-TM-650')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (645,'1:Inwentarz ogólny',1,'Giudelines for Cleaning of Boards and Assemblies.','IPC','IPC-CH-65A:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (646,'1:Inwentarz ogólny',1,'Guidelines for Cleaning of Printed Board Component Mounting.','IPC','IPC-CM-770E:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Nr_normy) values  (647,'1:Inwentarz ogólny',1,'with Amendement 1','Handbook and Guide to Supplement IPC-A-610(Includes IPC-A-610 B-C-D Comparisons)','IPC','IPC-HDBK-610:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (649,'1:Inwentarz ogólny',1,'Requirements for Soldered Electrical and Electronic Assemblies.','IPC','Requirements for Soldered Electrical and Electronic Assemblies. \ IPC J-STD-001D:2000','IPC J-STD-001D:2005')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (650,'1:Inwentarz ogólny',1,'Guidelines for Electrically Conductive Surface Mount Adhesives.','IPC','IPC-3406:1996')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (651,'1:Inwentarz ogólny',1,'Design and Assembly Process Implementation for BGAs','IPC','Design and Assembly Process Implementation for BGAs/ \ IPC-7095:2000','IPC-7095A:2004')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (652,'1:Inwentarz ogólny',1,'Systemy zarz¹dzania bezpieczeñstwem ¿ywnoœci.Wymagania dla ka¿dej organizacji naje¿¹cej do ³añcuch ¿ywnoœciowego.','Polski  Komitet Normalizacyjny','Systemy zarz¹dzania bezpieczeñstwem ¿ywnoœci.Wymagania dla ka¿dej organizacji naje¿¹cej do ³añcuch ¿ywnoœciowego. \ PN-EN ISO 22000:2005','PN-EN ISO 22000:2006')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (653,'1:Inwentarz ogólny',1,'Maszyny.Bezpieczeñstwo.Minimalne odstêpy zapobiegaj¹ce zgnieceniu czêœci cia³a cz³owieka.','Polski  Komitet Normalizacyjny','PN-EN 349:1999')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (654,'1:Inwentarz ogólny',1,'In¿ynieria systemów.Procesy w cyklu ¿ycia systemów.','Polski  Komitet Normalizacyjny','PN-ISO/IEC 15288:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (655,'1:Inwentarz ogólny',1,'Technika informatyczna.Procesy cyklu ¿ycia oprogramowania.','Polski  Komitet Normalizacyjny','PN-ISO/IEC 12207:2007')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (657,'1:Inwentarz ogólny',1,'Zast. czêœæ.przez PN-ISO 7253:2000','Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie mg³y solnej.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie mg³y solnej. \ PN-78/C-81523','PN-88/C-81523')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (658,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Badanie odpornoœci pow³ok na dzia³anie atmosfery nasyconej par¹ wodn¹.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Badanie odpornoœci pow³ok na dzia³anie atmosfery nasyconej par¹ wodn¹. \ PN-64/C-81525','PN-88/C-81525')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Opis_fizyczny,Tytul,Wydawcy,Zastapione,Nr_normy) values  (659,'2:Inwentarz ogólny1:Inwentarz ogólny',1,'zast.czêœæ. przez PN-EN ISO 2409:1999, PN-EN 24624:1994','Wyroby lakierowe.Okreœlanie przyczepnoœci pow³ok do pod³o¿a oraz przyczepnoœci miêdzywarstwowej.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Okreœlanie przyczepnoœci pow³ok do pod³o¿a oraz przyczepnoœci miêdzywarstwowej. \ PN-73/C-81531','PN-80/C-81531')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (660,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie objêtoœci suchej pow³oki(substancji nielotnej) otrzymanej z danej objêtoœci ciek³ego produktu na pod³o¿u.','Polski  Komitet Normalizacyjny','PN-93/C-81533')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (661,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie krycia.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie krycia. \ PN-70/C-81536','PN-89/C-81536')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (662,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie œciekalnoœci.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie œciekalnoœci. \ PN-66/C-81539','PN-80/C-81539')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (663,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Przybli¿one metody obliczania zu¿ycia i wydajnoœci.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Przybli¿one metody obliczania zu¿ycia i wydajnoœci. \ PN-67/C-81524','PN-93/C-81542')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (664,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie tendencji do ¿ó³kniêcia bia³ych pigmentowych pow³ok lakierowych.','Polski  Komitet Normalizacyjny','PN-72/C-81546')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (665,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Wyznaczanie wspó³czynnika tiksotropii.','Polski  Komitet Normalizacyjny','PN-73/C-81547')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (666,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Postanowienia ogólne i zakres normy.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Postanowienia ogólne i zakres normy. \ PN-86/C-81549/01','PN-86/C-81549/01')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (667,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych,Sprawdzanie i przygotowywanie szk³a laboratoryjnego do oznaczeñ metod¹ spektrofotometryczn¹.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych,Sprawdzanie i przygotowywanie szk³a laboratoryjnego do oznaczeñ metod¹ spektrofotometryczn¹. \ PN-81/C-81549','PN-86/C-81549/02')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (668,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci o³owiu.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci o³owiu. \ PN-81/C-81549','PN-86/C-81549/03')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (669,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci antymonu.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci antymonu. \ PN-81/C-81549','PN-86/C-81549/04')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (670,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci arsenu.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci arsenu. \ PN-81/C-81549','PN-86/C-81549/05')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (671,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci kadmu.','Polski  Komitet Normalizacyjny','wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci kadmu. \ PN-81/C-81549','PN-86/C-81549/06')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (673,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci rtêci.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci rtêci. \ PN-81/C-81549','PN-86/C-81549/07')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (674,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci chromu.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci chromu. \ PN-81/C-81549','PN-86/C-81549/08')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (675,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci miedzi.','Polski  Komitet Normalizacyjny','PN-86/C-81549/09')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (676,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznacznie zawartoœci metali toksycznych.Oznaczanie ca³kowitej zawartoœci manganu.','Polski  Komitet Normalizacyjny','PN-86/C-81549/10')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (677,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci baru.','Polski  Komitet Normalizacyjny','Wyroby lakieowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci baru. \ PN-81/C-81549','PN-86/C-81549/11')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (678,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.?oznaczanie metali toksycznych ekstrahowalnych kwasem solnym.Przygotowanie ekstraktów.','Polski  Komitet Normalizacyjny','PN-86/C-81549/12')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (681,'1:Inwentarz ogólny',1,'Ochrona czystoœci powietrza.Badania zawartoœci azotu i jego zwi¹zków .Czêœæ 11:Oznaczanie tlenku azotu i ditlenku azotu na stanowiskach pracy metod¹ spektrofotometryczn¹.                        ///czêœæ 11:','Polski  Komitet Normalizacyjny','PN-Z-04009-11:2008')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (682,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci  metali toksycznych ekstrahowalnych kwasem solnym...','Polski  Komitet Normalizacyjny','PN-86/C-81549.13')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (683,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci antymonu.','Polski  Komitet Normalizacyjny','PN-86/C-81549.14')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (684,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci arsenu.','Polski  Komitet Normalizacyjny','PN-86/C-81549.15')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (685,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci kadmu.','Polski  Komitet Normalizacyjny','PN-86/C-81549.16')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (686,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci rtêci.','Polski  Komitet Normalizacyjny','PN-86/C-81549.17')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (687,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci chromu.','Polski  Komitet Normalizacyjny','PN-86/C-81549.18')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (688,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci miedzi.','Polski  Komitet Normalizacyjny','PN-86/C-81549.19')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (689,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metalim toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci manganu.','Polski  Komitet Normalizacyjny','PN-86/C-81549.20')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (690,'1:Inwentarz ogólny',1,'Wyroby lakierowe .Oznaczanie zawartoœci metali toksycznych.Oznaczanie zawartoœci metali toksycznych ekstrahowalnych kwasem solnym.Oznaczanie zawartoœci baru.','Polski  Komitet Normalizacyjny','PN-86/C-81549.21')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (691,'1:Inwentarz ogólny',1,'Oznaczanie lepkoœci wyrobów lakierowych i farb graficznych za pomoc¹ lepkoœciomierzy Rotothinner.','Polski  Komitet Normalizacyjny','Oznaczanie lepkoœci wyrobów lakierowych i farb graficznych za pomoc¹ lepkoœciomierzy Rotothinner. \ BN-79/7469-09.05','PN-86/C-81554')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (692,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie w³asnoœci reologicznych przy u¿yciu wiskozymetrów rotacyjnych.','Polski  Komitet Normalizacyjny','PN-86/C-81555')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (693,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Badanie odpornoœci pow³ok lakierowych na dzia³anie zmiennych temperatur.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Badanie odpornoœci pow³ok lakierowych na dzia³anie zmiennych temperatur. \ BN-66/6110-15','PN-88/C-81556')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (694,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie wody morskiej.','Polski  Komitet Normalizacyjny','Wyroby lakierowe.Oznaczanie odpornoœci pow³ok na dzia³anie wody morskiej. \ BN-78/6110-02','PN-89/C-81557')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (695,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Badania odpornoœci pow³ok na pod³o¿e alkaliczne.','Polski  Komitet Normalizacyjny','PN-92/C-81558')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (696,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Badanie przydatnoœci wyrobów lakierowych dyspersyjnych do malowania w obni¿onej temperaturze.','Polski  Komitet Normalizacyjny','PN-92/C-81559')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (697,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Emalie celulozowe.','Polski  Komitet Normalizacyjny','Emalie celulozowe. \ BN-76/6115-05; Emalie celulozowe. \ BN-82/6115-29; Emalie celulozowe. \ BN-83/6115-66; Emalie celulozowe. \ BN-86/6115-71','PN-C-81605:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (698,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Emalie ftalowe karbamidowe schn¹ce w piecu.','Polski  Komitet Normalizacyjny','PN-C-81606:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (699,'1:Inwentarz ogólny2:Inwentarz ogólny',1,'Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane.','Polski  Komitet Normalizacyjny','Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane. \ BN-75/6115-02; Emalie olejno-¿ywiczne,ftalowe,ftalowe modyfikowane i ftalowe kopolomeryzowane styrenowane. \ BN-64/6115-12; Emalie olejno-¿ywiczne,ftalowe,ftalo','PN-C-81607:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (700,'1:Inwentarz ogólny2:Inwentarz ogólnyInwentarz ogólny',1,'Emalie chlorokauczukowe.','Polski  Komitet Normalizacyjny','Emalie chlorokauczukowe. \ BN-76/6115-17; Emalie chlorokauczukowe. \ BN-73/6115-18','PN-C-81608:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (701,'1:Inwentarz ogólny',1,'Wyroby lakierowe.Oznaczanie zawartoœci cynku w farbach przeciwkorozyjnych cynkowych.','Polski  Komitet Normalizacyjny','PN-91/C-81700')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Nr_normy) values  (702,'1:Inwentarz ogólny',1,'Oznaczanie czasu wyp³ywu wyrobów lakierowych i farb graficznych za pomoc¹ kubków wyp³ywowych z dnem sto¿kowym i p³askim.','Polski  Komitet Normalizacyjny','PN-C-81701:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (703,'1:Inwentarz ogólny',1,'Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu.','Polski  Komitet Normalizacyjny','Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu. \ BN-80/6113-04; Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu. \ BN-72/6113-52; Podk³ady ftalowe karbamidowe ogólnego stosowania schn¹ce w piecu. \ BN-83/6113-77','PN-C-81751:1998')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (704,'1:Inwentarz ogólny',1,'Lakiery nitrocelulozowe.','Polski  Komitet Normalizacyjny','Lakiery nitrocelulozowe. \ BN-75/6114-10; Lakiery nitrocelulozowe. \ BN-75/6114-29; Lakiery nitrocelulozowe. \ BN-75/6114-42; Lakiery nitrocelulozowe. \ BN-83/6114-64','PN-C-81801:1997')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (705,'1:Inwentarz ogólny',1,'Farby olejne i alkidowe.','Polski  Komitet Normalizacyjny','Farby olejne i alkidowe. \ PN-C-81901:1997','PN-C-81901:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (706,'1:Inwentarz ogólny',1,'Farby chlorokauczukowe.','Polski  Komitet Normalizacyjny','Farby chlorokauczukowe. \ PN-C-81910:1997','PN-C-81910:2002')
GO
insert into Normy (Id_norma,Egzemplarze,Nor_rodz_id,Tytul,Wydawcy,Zastapione,Nr_normy) values  (707,'1:Inwentarz ogólny',1,'Farby epoksydowe do gruntowania odporne na czynniki chemiczne.','Polski  Komitet Normalizacyjny','Farby epoksydowe do gruntowania odporne na czynniki chemiczne. \ BN-78/6113-32','PN-C-81911:1997')
GO
insert into Normy (Id_norma,Nor_rodz_id) values  (708,1)
GO
set identity_insert normy off

update normy set Data_ust = getdate() - (1001 + id_norma),Data_pub = getdate() - (1000 + id_norma)
go